### ISSUE TITLE
[11.0] Issue with l10n_it_fatturapa_pec

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#1037]
After installing the module, cannot enter on configuration in any module, error

```
Errore:
TypeError: undefined is not an object (evaluating 'this.state.fields[fieldName].string')

https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1405
Traceback:
_renderTagLabel@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1405:867
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3819:376
[native code]
collect@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:13:278
_renderGenericTag@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1387:306
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3819:376
[native code]
collect@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:13:278
_renderGenericTag@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1387:306
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3819:376
[native code]
collect@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:13:278
_renderGenericTag@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1387:306
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3819:376
[native code]
collect@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:13:278
_renderGenericTag@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1387:306
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3819:376
[native code]
collect@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:13:278
_renderGenericTag@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1387:306
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3819:376
[native code]
collect@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:13:278
_renderTagForm@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1402:21
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3819:376
_renderView@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1411:1241
_render@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1349:189
_render@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:7:674
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3816:493
start@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1094:342
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3816:493
start@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:3:618
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3816:493
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:686
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
add@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:797:471
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:649
each@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:625:771
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:564
Deferred@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:803:198
then@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:533
start@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1101:664
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3816:493
start@https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:1320:1023
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3816:493
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:686
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
add@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:797:471
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:649
each@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:625:771
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:564
Deferred@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:803:198
then@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:533
https://myhostname.com/web/content/458-0de3413/web.assets_backend.js:481:321
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:686
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:874
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:803:56
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:874
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:804:502
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:803:56
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:874
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:803:56
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:874
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:874
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:804:502
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:874
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:803:56
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:3869:363
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:686
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:803:56
fire@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:796:304
fireWith@https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:801:202
https://myhostname.com/web/content/413-4dd2a28/web.assets_common.js:802:874
```

Removing the module it get back to work.

Any hint? 

# Fixes

v8: not affected
v10: not affected
v11: https://github.com/OCA/l10n-italy/pull/1038
v12: not affected

**Comment by SimoRubi** [comment]
@GSLabIt please try triggering the error while you are logged as admin in 'developer with assets' mode (note that you have 'debug=assets' in the address bar), so at least we have the name of the scripts being executed and the line where they failed.

**Comment by GSLabIt** [comment]
@SimoRubi i'm testing in local, probably the error is due by `e_invoice_user_id` related field in res.config.settings ...will get back on this in a few

**Comment by GSLabIt** [comment]
@SimoRubi here is comes error with assets debug:
```
Error:
Uncaught TypeError: Cannot read property 'string' of undefined

http://127.0.0.1:8269/web/static/src/js/views/form/form_renderer.js:651
Traceback:
TypeError: Cannot read property 'string' of undefined
    at Class._renderTagLabel (http://127.0.0.1:8269/web/static/src/js/views/form/form_renderer.js:651:49)
    at Class._renderNode [as _super] (http://127.0.0.1:8269/web/static/src/js/views/form/form_renderer.js:483:29)
    at Class._renderNode (http://127.0.0.1:8269/mail/static/src/js/form_renderer.js:83:32)
    at Class._renderNode (http://127.0.0.1:8269/web/static/src/js/core/class.js:123:38)
    at Function._.map._.collect (http://127.0.0.1:8269/web/static/lib/underscore/underscore.js:164:24)
    at Class._renderGenericTag (http://127.0.0.1:8269/web/static/src/js/views/form/form_renderer.js:330:26)
    at Class._renderNode [as _super] (http://127.0.0.1:8269/web/static/src/js/views/form/form_renderer.js:491:21)
    at Class._renderNode (http://127.0.0.1:8269/mail/static/src/js/form_renderer.js:83:32)
    at Class._renderNode (http://127.0.0.1:8269/web/static/src/js/core/class.js:123:38)
    at Function._.map._.collect (http://127.0.0.1:8269/web/static/lib/underscore/underscore.js:164:24)
```

**Comment by eLBati** [comment]
It seems only v11 is affcted. @OCA/local-italy-developers can you confirm?

**Comment by GSLabIt** [comment]
@eLBati you're right, i've tested in runbot and seems only v11.0 is affected.

**Comment by GSLabIt** [comment]
Fixed
