### ISSUE TITLE
errore installazione DDT (server error)

### ISSUE THREAD

**Issue by stesifrancesco** [OCA/l10n-italy#1222]
Versioni coinvolte: 12

Passi per riprodurre: Installare Italian Localization - DDT: Documento di trasporto 

Comportamento osservato:
Quando provo ad installare il modulo DDT ottengo sempre il seguente errore:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo-dev12/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo-dev12/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 3848, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 3762, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/home/odoo/odoo-dev12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/odoo-dev12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/odoo-dev12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 3579, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/odoo/odoo-dev12/odoo/odoo/fields.py", line 1114, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/odoo-dev12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/odoo/odoo-dev12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 3307, in write
    self._write(store_vals)
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 3440, in _write
    self._validate_fields(vals)
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/home/odoo/odoo-dev12/odoo/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.exceptions.ValidationError: ('Invalid view ddt.stock.picking.package.preparation.search\n             definition in l10n_it_ddt/views/stock_picking_package_preparation.xml', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo-dev12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-dev12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo-dev12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo-dev12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-dev12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-dev12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-dev12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-dev12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-dev12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-dev12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-dev12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo-dev12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo-dev12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/home/odoo/odoo-dev12/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/odoo-dev12/odoo/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/odoo-dev12/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/odoo-dev12/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo-dev12/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/odoo/odoo-dev12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/odoo-dev12/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/odoo/odoo-dev12/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/odoo-dev12/odoo/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/odoo-dev12/odoo/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/odoo-dev12/odoo/odoo/tools/convert.py", line 754, in parse
    self.parse(rec, mode)
  File "/home/odoo/odoo-dev12/odoo/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/home/odoo/odoo-dev12/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/odoo-dev12/odoo/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/odoo/odoo-dev12/odoo/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 3848, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 3762, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/home/odoo/odoo-dev12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/odoo-dev12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/odoo-dev12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 3579, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/odoo/odoo-dev12/odoo/odoo/fields.py", line 1114, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/odoo-dev12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/odoo/odoo-dev12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 3307, in write
    self._write(store_vals)
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 3440, in _write
    self._validate_fields(vals)
  File "/home/odoo/odoo-dev12/odoo/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/home/odoo/odoo-dev12/odoo/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view ddt.stock.picking.package.preparation.search
             definition in l10n_it_ddt/views/stock_picking_package_preparation.xml
None" while parsing /home/odoo/odoo-dev12/test-addons/l10n_it_ddt/views/stock_picking_package_preparation.xml:37, near
<record id="ddt_stock_picking_package_preparation_search" model="ir.ui.view">
            <field name="name">ddt.stock.picking.package.preparation.search
            </field>
            <field name="model">stock.picking.package.preparation</field>
            <field name="arch" type="xml">
                <search string="Search DDT">
                    <field name="ddt_number"/>
                    <field name="partner_id"/>
                    <field name="partner_shipping_id"/>
                    <field name="ddt_type_id"/>
                    <filter string="To Be Invoiced" domain="[('to_be_invoiced','=', True), ('invoice_id','=', False)]"/>
                    <filter string="Invoiced" domain="[('invoice_id','!=', False)]"/>
                    <filter string="Draft" domain="[('state','=', 'draft')]"/>
                    <field name="picking_ids"/>
                    <group expand="0" string="Group By">
                        <filter name="group_by_partner" string="Partner" domain="[]" context="{'group_by': 'partner_id'}"/>
                        <filter string="DDT Date" context="{'group_by': 'date'}"/>
                        <filter string="State" context="{'group_by': 'state'}"/>
                        <filter string="DDT Type" context="{'group_by': 'ddt_type_id'}"/>
                    </group>
                </search>
            </field>
        </record>

Qualsiasi suggerimento è il benvenuto

Grazie e buon lavoro

Francesco

**Comment by eLBati** [comment]
Ho appena provato ad installare l10n_it_ddt su un nuovo DB, con lingua italiana, e non ho ottenuto errori. Probabilmente è un problema della tua installazione.
