### ISSUE TITLE
[8.0] Problema con voucher in l10n_it_withholding_tax 

### ISSUE THREAD

**Issue by silverf0x0** [OCA/l10n-italy#1371]
Versioni coinvolte: Odoo 8.0

Passi per riprodurre:

Quando si cerca di pagare una fattura con ritenuta viene generato il seguente errore:

Traceback (most recent call last):
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/buildout/parts/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/buildout/parts/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/addons/account_voucher/account_voucher.py", line 933, in button_proforma_voucher
    self.signal_workflow(cr, uid, ids, 'proforma_voucher')
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/openerp/models.py", line 3594, in signal_workflow
    result[res_id] = workflow.trg_validate(uid, self._name, res_id, signal, cr)
  File "/opt/odoo/buildout/parts/odoo/openerp/workflow/__init__.py", line 85, in trg_validate
    return WorkflowService.new(cr, uid, res_type, res_id).validate(signal)
  File "/opt/odoo/buildout/parts/odoo/openerp/workflow/service.py", line 91, in validate
    res2 = wi.validate(signal)
  File "/opt/odoo/buildout/parts/odoo/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/opt/odoo/buildout/parts/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/opt/odoo/buildout/parts/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/opt/odoo/buildout/parts/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/opt/odoo/buildout/parts/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/opt/odoo/buildout/parts/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/opt/odoo/buildout/parts/odoo/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/opt/odoo/buildout/parts/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/opt/odoo/buildout/parts/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/opt/odoo/buildout/parts/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/buildout/parts/odoo/addons/account_voucher/account_voucher.py", line 937, in proforma_voucher
    self.action_move_line_create(cr, uid, ids, context=context)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/l10n-italy/l10n_it_withholding_tax/models/voucher.py", line 252, in action_move_line_create
    cr, uid, ids, context=None)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/addons/account_voucher/account_voucher.py", line 1414, in action_move_line_create
    line_total, rec_list_ids = self.voucher_move_line_create(cr, uid, voucher.id, line_total, move_id, company_currency, current_currency, context)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/l10n-italy/l10n_it_withholding_tax/models/voucher.py", line 235, in voucher_move_line_create
    move_line_obj.write(cr, uid, [line_payment.id], val)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/addons/account/account_move_line.py", line 1251, in write
    self._update_check(cr, uid, ids, context)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/addons/account/account_move_line.py", line 1313, in _update_check
    raise osv.except_osv(_('Error!'), _('You cannot do this modification on a confirmed entry. You can just change some non legal fields or you must unconfirm the journal entry first.\n%s.') % err_msg)
except_orm: (u'Errore!', u'Non \xe8 possibile applicare questa modifica su una registrazione confermata. \xc8 possibile solamente modificare alcuni dati non legali altrimenti \xe8 necessario annullare le registrazioni sezionali prima.\nMovimento nome (id): BNK2/2019/1535 (4633).')
Collaps.

Se si installa il modulo 'Account Voucher Payline', si riesce ad effettuare il pagamento, che però risulta di importo errato: il valore esposto per il pagamento risulta al lordo della ritenuta, e il valore della ritenuta viene impostato come sbilancio.

Comportamento osservato:

Comportamento atteso:

Video/Screenshot (opzionale):

**Comment by sergiocorato** [comment]
vedi se questa https://github.com/OCA/l10n-italy/pull/1217 risolve

**Comment by silverf0x0** [comment]
@sergiocorato si, con questo fix va tutto liscio. Grazie infinite, gentilissimo.

**Comment by sergiocorato** [comment]
prego :)
@CiroBoxHub: riesci a gestire la #1217?
