### ISSUE TITLE
l10n_it_fiscalcode - Odoo Server Error: name 'build' is not defined

### ISSUE THREAD

**Issue by ivanpug** [OCA/l10n-italy#1490]
Versioni coinvolte:
Odoo 12.0

Passi per riprodurre:
- importare modulo l10n_it_fiscalcode in extra-addons directory
- installare dipendenza python condicefiscale
- avviare odoo-bin e installare moduli contacts e fiscal_code
- cliccare su bottone "Calcola C.F." in contact form
- riempire i campi e cliccare Calcola

Comportamento osservato:

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/extra-addons/l10n_it_fiscalcode/wizard/compute_fc.py", line 189, in compute_fc
    c_f = build(f.fiscalcode_surname, f.fiscalcode_firstname,
NameError: name 'build' is not defined

Comportamento atteso:
calcolo CF e salvataggio in field "fiscalcode"

**Comment by eLBati** [comment]
Probabilmente `codicefiscale` non è installato correttamente.
Controlla se nel log vedi un WARNING che dice `codicefiscale library not found`.

**Comment by ivanpug** [comment]
La dipendenza python `codicefiscale==0.9` e' installata correttamente.
Compare solo questo messaggio di errore
`ERROR prova_cf odoo.http: Exception during JSON request handling.`
seguito da quello riportato sopra.

**Comment by eLBati** [comment]
È comunque un problema di installazione perchè se vado su https://runbot.odoo-community.org/runbot/repo/github-com-oca-l10n-italy-122 , nella build 12.0, ed eseguo i passi descritti non ottengo errore

**Comment by ivanpug** [comment]
Chiedo scusa, ho individuato la causa del problema:
quando sono installate le due librerie 
- codicefiscale
- python-codicefiscale
il sistema utilizza la seconda, ovviamente non trovando la funzione "build"
