### ISSUE TITLE
[12.0][l10n_it_corrispettivi] errore visualizzazione anteprima ricevuta su portal

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#1555]
Versioni coinvolte:

 - [ ] 10.0: ?
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1581

Passi per riprodurre:
1. installare website.
2. creare una ricevuta, utilizzando il flag corrispettivi.
3. Visualizzare la ricevuta da Fatturazione -> Cliente -> Ricevute
4. Visualizzare l'anteprima della ricevuta (su portal) 

Errore riprodotto anche su runbot.
Comportamento osservato:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7fadc57700d0>, 'l10n_it_corrispettivi.report_corrispettivi_document', ('en_US', True, None, False, False, 1))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.view', <function View.get_view_id at 0x7fadbebe7048>, 1, 'l10n_it_corrispettivi.report_corrispettivi_document', (1,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 372, in get_template
    document = options.get('load', self.load)(template, options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 122, in load
    template = env['ir.ui.view'].read_template(name)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1189, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-239>", line 2, in get_view_id
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 279, in get_view_id
    raise ValueError('View %r in website %r not found' % (xml_id, self._context['website_id']))
ValueError: View 'l10n_it_corrispettivi.report_corrispettivi_document' in website 1 not found

load could not load template
Template: l10n_it_corrispettivi.report_corrispettivi_document
```
Comportamento atteso:

Video/Screenshot (opzionale):

![png;base648cd1f2f9fe685426](https://user-images.githubusercontent.com/11652845/70336725-f4628d00-1849-11ea-9ac0-0932064080e5.png)

**Comment by GSLabIt** [comment]
@eLBati @SimoRubi potreste dare un'occhiata? Thx

**Comment by eLBati** [comment]
la 10 è affetta?

**Comment by GSLabIt** [comment]
@eLBati non ho verificato
