### ISSUE TITLE
[10]   crash dopo upgrade

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#1567]
Buon giorno,   poichè non riuscivo a importare l'archivio con il database di odoo10 da un pc all'altro appena reinstallato , ho provato a fare l'upgrade dei moduli di fatturpa 
Adesso mi ritrovo con un crash e questo errore

`2019-12-22 14:52:45,615 10713 INFO odoo odoo.sql_db: bad query:  SELECT "res_partner"."register_regdate" as "register_regdate","res_partner"."debit_limit" as "debit_limit","res_partner"."electronic_invoice_subjected" as "electronic_invoice_subjected","res_partner"."write_uid" as "write_uid","res_partner"."rea_code" as "rea_code","res_partner"."date" as "date","res_partner"."rea_member_type" as "rea_member_type","res_partner"."type" as "type","res_partner"."electronic_invoice_no_contact_update" as "electronic_invoice_no_contact_update","res_partner"."last_time_entries_checked" as "last_time_entries_checked","res_partner"."customer" as "customer","res_partner"."is_company" as "is_company","res_partner"."signup_expiration" as "signup_expiration","res_partner"."opt_out" as "opt_out","res_partner"."employee" as "employee","res_partner"."name" as "name","res_partner"."register_province" as "register_province","res_partner"."email" as "email","res_partner"."commercial_partner_id" as "commercial_partner_id","res_partner"."invoice_warn" as "invoice_warn","res_partner"."write_date" as "write_date","res_partner"."rea_capital" as "rea_capital","res_partner"."notify_email" as "notify_email","res_partner"."fax" as "fax","res_partner"."create_uid" as "create_uid","res_partner"."company_id" as "company_id","res_partner"."street2" as "street2","res_partner"."message_bounce" as "message_bounce","res_partner"."color" as "color","res_partner"."credit_limit" as "credit_limit","res_partner"."pa_partner_code" as "pa_partner_code","res_partner"."phone" as "phone","res_partner"."country_id" as "country_id","res_partner"."ipa_code" as "ipa_code","res_partner"."function" as "function","res_partner"."in_fiscal_document_type" as "in_fiscal_document_type","res_partner"."zip" as "zip","res_partner"."register_fiscalpos" as "register_fiscalpos","res_partner"."pec_destinatario" as "pec_destinatario","res_partner"."register" as "register","res_partner"."rea_office" as "rea_office","res_partner"."supplier" as "supplier","res_partner"."register_code" as "register_code","res_partner"."individual" as "individual","res_partner"."street" as "street","res_partner"."comment" as "comment","res_partner"."barcode" as "barcode","res_partner"."codice_destinatario" as "codice_destinatario","res_partner"."state_id" as "state_id","res_partner"."lastname" as "lastname","res_partner"."e_invoice_detail_level" as "e_invoice_detail_level","res_partner"."display_name" as "display_name","res_partner"."website" as "website","res_partner"."e_invoice_default_product_id" as "e_invoice_default_product_id","res_partner"."id" as "id","res_partner"."out_fiscal_document_type" as "out_fiscal_document_type","res_partner"."partner_share" as "partner_share","res_partner"."eori_code" as "eori_code","res_partner"."tz" as "tz","res_partner"."commercial_company_name" as "commercial_company_name","res_partner"."firstname" as "firstname","res_partner"."license_number" as "license_number","res_partner"."title" as "title","res_partner"."lang" as "lang","res_partner"."signup_type" as "signup_type","res_partner"."vat" as "vat","res_partner"."rea_liquidation_state" as "rea_liquidation_state","res_partner"."mobile" as "mobile","res_partner"."is_pa" as "is_pa","res_partner"."invoice_warn_msg" as "invoice_warn_msg","res_partner"."company_name" as "company_name","res_partner"."fiscalcode" as "fiscalcode","res_partner"."parent_id" as "parent_id","res_partner"."city" as "city","res_partner"."message_last_post" as "message_last_post","res_partner"."active" as "active","res_partner"."user_id" as "user_id","res_partner"."ref" as "ref","res_partner"."create_date" as "create_date","res_partner"."signup_token" as "signup_token" FROM "res_partner"
                        WHERE "res_partner".id IN (3)  ORDER BY "res_partner"."display_name"  
                    
2019-12-22 14:52:45,624 10713 ERROR odoo odoo.addons.base.ir.ir_cron: Unexpected exception while processing cron job {'function': u'_fetch_mails', 'create_uid': 1, 'args': u'()', 'user_id': 1, 'name': u'Fetchmail Service', 'interval_type': u'minutes', 'numbercall': -1, 'nextcall': '2019-12-22 10:38:28', 'priority': 5, 'model': u'fetchmail.server', 'doall': False, 'write_date': '2019-09-09 16:58:14.666599', 'active': True, 'create_date': '2019-01-10 16:18:28.733168', 'interval_number': 5, 'write_uid': 1, 'id': 4}
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_cron.py", line 233, in _acquire_job
    registry[cls._name]._process_job(job_cr, job, lock_cr)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_cron.py", line 147, in _process_job
    now = fields.Datetime.context_timestamp(cron, datetime.now())
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 1526, in context_timestamp
    tz_name = record._context.get('tz') or record.env.user.tz
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 980, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 935, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 928, in _compute_value
    self.compute(records)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 580, in _compute_related
    record[self.name] = other[field.name]
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 5191, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 971, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3061, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3001, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3129, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_partner.electronic_invoice_no_contact_update does not exist
RIGA 1: ... "rea_member_type","res_partner"."type" as "type","res_partn...
                                                             ^

2019-12-22 14:52:56,372 10713 INFO odoo odoo.sql_db: bad query:  SELECT "res_partner"."register_regdate" as "register_regdate","res_partner"."debit_limit" as "debit_limit","res_partner"."electronic_invoice_subjected" as "electronic_invoice_subjected","res_partner"."write_uid" as "write_uid","res_partner"."rea_code" as "rea_code","res_partner"."date" as "date","res_partner"."rea_member_type" as "rea_member_type","res_partner"."type" as "type","res_partner"."electronic_invoice_no_contact_update" as "electronic_invoice_no_contact_update","res_partner"."last_time_entries_checked" as "last_time_entries_checked","res_partner"."customer" as "customer","res_partner"."is_company" as "is_company","res_partner"."signup_expiration" as "signup_expiration","res_partner"."opt_out" as "opt_out","res_partner"."employee" as "employee","res_partner"."name" as "name","res_partner"."register_province" as "register_province","res_partner"."email" as "email","res_partner"."commercial_partner_id" as "commercial_partner_id","res_partner"."invoice_warn" as "invoice_warn","res_partner"."write_date" as "write_date","res_partner"."rea_capital" as "rea_capital","res_partner"."notify_email" as "notify_email","res_partner"."fax" as "fax","res_partner"."create_uid" as "create_uid","res_partner"."company_id" as "company_id","res_partner"."street2" as "street2","res_partner"."message_bounce" as "message_bounce","res_partner"."color" as "color","res_partner"."credit_limit" as "credit_limit","res_partner"."pa_partner_code" as "pa_partner_code","res_partner"."phone" as "phone","res_partner"."country_id" as "country_id","res_partner"."ipa_code" as "ipa_code","res_partner"."function" as "function","res_partner"."in_fiscal_document_type" as "in_fiscal_document_type","res_partner"."zip" as "zip","res_partner"."register_fiscalpos" as "register_fiscalpos","res_partner"."pec_destinatario" as "pec_destinatario","res_partner"."register" as "register","res_partner"."rea_office" as "rea_office","res_partner"."supplier" as "supplier","res_partner"."register_code" as "register_code","res_partner"."individual" as "individual","res_partner"."street" as "street","res_partner"."comment" as "comment","res_partner"."barcode" as "barcode","res_partner"."codice_destinatario" as "codice_destinatario","res_partner"."state_id" as "state_id","res_partner"."lastname" as "lastname","res_partner"."e_invoice_detail_level" as "e_invoice_detail_level","res_partner"."display_name" as "display_name","res_partner"."website" as "website","res_partner"."e_invoice_default_product_id" as "e_invoice_default_product_id","res_partner"."id" as "id","res_partner"."out_fiscal_document_type" as "out_fiscal_document_type","res_partner"."partner_share" as "partner_share","res_partner"."eori_code" as "eori_code","res_partner"."tz" as "tz","res_partner"."commercial_company_name" as "commercial_company_name","res_partner"."firstname" as "firstname","res_partner"."license_number" as "license_number","res_partner"."title" as "title","res_partner"."lang" as "lang","res_partner"."signup_type" as "signup_type","res_partner"."vat" as "vat","res_partner"."rea_liquidation_state" as "rea_liquidation_state","res_partner"."mobile" as "mobile","res_partner"."is_pa" as "is_pa","res_partner"."invoice_warn_msg" as "invoice_warn_msg","res_partner"."company_name" as "company_name","res_partner"."fiscalcode" as "fiscalcode","res_partner"."parent_id" as "parent_id","res_partner"."city" as "city","res_partner"."message_last_post" as "message_last_post","res_partner"."active" as "active","res_partner"."user_id" as "user_id","res_partner"."ref" as "ref","res_partner"."create_date" as "create_date","res_partner"."signup_token" as "signup_token" FROM "res_partner"
                        WHERE "res_partner".id IN (3)  ORDER BY "res_partner"."display_name"  
                    
2019-12-22 14:52:56,402 10713 ERROR odoo odoo.addons.base.ir.ir_cron: Unexpected exception while processing cron job {'function': u'process_email_queue', 'create_uid': 1, 'args': u'()', 'user_id': 1, 'name': u'Email Queue Manager', 'interval_type': u'hours', 'numbercall': -1, 'nextcall': '2019-12-22 11:18:19', 'priority': 5, 'model': u'mail.mail', 'doall': False, 'write_date': '2019-01-10 16:18:18.899347', 'active': True, 'create_date': '2019-01-10 16:18:18.899347', 'interval_number': 1, 'write_uid': 1, 'id': 2}
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_cron.py", line 233, in _acquire_job
    registry[cls._name]._process_job(job_cr, job, lock_cr)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_cron.py", line 147, in _process_job
    now = fields.Datetime.context_timestamp(cron, datetime.now())
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 1526, in context_timestamp
    tz_name = record._context.get('tz') or record.env.user.tz
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 980, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 935, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 928, in _compute_value
    self.compute(records)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 580, in _compute_related
    record[self.name] = other[field.name]
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 5191, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 971, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3061, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3001, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3129, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_partner.electronic_invoice_no_contact_update does not exist
RIGA 1: ... "rea_member_type","res_partner"."type" as "type","res_partn...
                                                             ^

2019-12-22 14:52:56,405 10713 INFO odoo odoo.sql_db: bad query:  SELECT "res_partner"."register_regdate" as "register_regdate","res_partner"."debit_limit" as "debit_limit","res_partner"."electronic_invoice_subjected" as "electronic_invoice_subjected","res_partner"."write_uid" as "write_uid","res_partner"."rea_code" as "rea_code","res_partner"."date" as "date","res_partner"."rea_member_type" as "rea_member_type","res_partner"."type" as "type","res_partner"."electronic_invoice_no_contact_update" as "electronic_invoice_no_contact_update","res_partner"."last_time_entries_checked" as "last_time_entries_checked","res_partner"."customer" as "customer","res_partner"."is_company" as "is_company","res_partner"."signup_expiration" as "signup_expiration","res_partner"."opt_out" as "opt_out","res_partner"."employee" as "employee","res_partner"."name" as "name","res_partner"."register_province" as "register_province","res_partner"."email" as "email","res_partner"."commercial_partner_id" as "commercial_partner_id","res_partner"."invoice_warn" as "invoice_warn","res_partner"."write_date" as "write_date","res_partner"."rea_capital" as "rea_capital","res_partner"."notify_email" as "notify_email","res_partner"."fax" as "fax","res_partner"."create_uid" as "create_uid","res_partner"."company_id" as "company_id","res_partner"."street2" as "street2","res_partner"."message_bounce" as "message_bounce","res_partner"."color" as "color","res_partner"."credit_limit" as "credit_limit","res_partner"."pa_partner_code" as "pa_partner_code","res_partner"."phone" as "phone","res_partner"."country_id" as "country_id","res_partner"."ipa_code" as "ipa_code","res_partner"."function" as "function","res_partner"."in_fiscal_document_type" as "in_fiscal_document_type","res_partner"."zip" as "zip","res_partner"."register_fiscalpos" as "register_fiscalpos","res_partner"."pec_destinatario" as "pec_destinatario","res_partner"."register" as "register","res_partner"."rea_office" as "rea_office","res_partner"."supplier" as "supplier","res_partner"."register_code" as "register_code","res_partner"."individual" as "individual","res_partner"."street" as "street","res_partner"."comment" as "comment","res_partner"."barcode" as "barcode","res_partner"."codice_destinatario" as "codice_destinatario","res_partner"."state_id" as "state_id","res_partner"."lastname" as "lastname","res_partner"."e_invoice_detail_level" as "e_invoice_detail_level","res_partner"."display_name" as "display_name","res_partner"."website" as "website","res_partner"."e_invoice_default_product_id" as "e_invoice_default_product_id","res_partner"."id" as "id","res_partner"."out_fiscal_document_type" as "out_fiscal_document_type","res_partner"."partner_share" as "partner_share","res_partner"."eori_code" as "eori_code","res_partner"."tz" as "tz","res_partner"."commercial_company_name" as "commercial_company_name","res_partner"."firstname" as "firstname","res_partner"."license_number" as "license_number","res_partner"."title" as "title","res_partner"."lang" as "lang","res_partner"."signup_type" as "signup_type","res_partner"."vat" as "vat","res_partner"."rea_liquidation_state" as "rea_liquidation_state","res_partner"."mobile" as "mobile","res_partner"."is_pa" as "is_pa","res_partner"."invoice_warn_msg" as "invoice_warn_msg","res_partner"."company_name" as "company_name","res_partner"."fiscalcode" as "fiscalcode","res_partner"."parent_id" as "parent_id","res_partner"."city" as "city","res_partner"."message_last_post" as "message_last_post","res_partner"."active" as "active","res_partner"."user_id" as "user_id","res_partner"."ref" as "ref","res_partner"."create_date" as "create_date","res_partner"."signup_token" as "signup_token" FROM "res_partner"
                        WHERE "res_partner".id IN (3)  ORDER BY "res_partner"."display_name"  
                    
2019-12-22 14:52:56,415 10713 ERROR odoo odoo.addons.base.ir.ir_cron: Unexpected exception while processing cron job {'function': u'_fetch_mails', 'create_uid': 1, 'args': u'()', 'user_id': 1, 'name': u'Fetchmail Service', 'interval_type': u'minutes', 'numbercall': -1, 'nextcall': '2019-12-22 10:38:28', 'priority': 5, 'model': u'fetchmail.server', 'doall': False, 'write_date': '2019-09-09 16:58:14.666599', 'active': True, 'create_date': '2019-01-10 16:18:28.733168', 'interval_number': 5, 'write_uid': 1, 'id': 4}
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_cron.py", line 233, in _acquire_job
    registry[cls._name]._process_job(job_cr, job, lock_cr)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_cron.py", line 147, in _process_job
    now = fields.Datetime.context_timestamp(cron, datetime.now())
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 1526, in context_timestamp
    tz_name = record._context.get('tz') or record.env.user.tz
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 980, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 935, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 928, in _compute_value
    self.compute(records)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 580, in _compute_related
    record[self.name] = other[field.name]
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 5191, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 971, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3061, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3001, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3129, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_partner.electronic_invoice_no_contact_update does not exist
RIGA 1: ... "rea_member_type","res_partner"."type" as "type","res_partn...`

**Comment by bitit-it** [comment]
con l'upgrade mi installa queste versioni che mi danno problema
odoo10-addon-l10n-it-fatturapa 10.0.2.8.0
odoo10-addon-l10n-it-fatturapa-in-10.0.1.12.0
odoo10-addon-l10n-it-fatturapa-out-10.0.1.5.1
odoo10-addon-l10n-it-fatturapa-out-stamp-10.0.1.0.2

Enrico

**Comment by eLBati** [comment]
Se non l'avessi già fatto, ricordati di aggiornare i moduli modificati. Nel dubbio, aggiornali tutti.

Chiudo perchè non riproducibile

**Comment by bitit-it** [comment]
ok.. ma ho pres il dump e  caricato su in installazione fesca appena installata, per tanto dovrebbe essere aggiornata, crash, 
allora ho aggiornato l'installazione precedente, 
crash 

Comunque per adesso son riuscito a ricopaire dei vecchi moduli su  un installazione, mi rifuziona quasi tutto tranne la stampa. 

enrico

**Comment by eLBati** [comment]
> per tanto dovrebbe essere aggiornata

Il problema è che è il database a non essere aggiornato

**Comment by bitit-it** [comment]
ok.. cerco una soluzione, nel caso dovessi reimportare solo il database senza file allegati, dove li trovo i file delle fatture elettroniche?

**Comment by bitit-it** [comment]
Ho risolto comunque, ho reinstallato tutto da capo, facendo attenzione a tutte le dipendenze e va.
