### ISSUE TITLE
Error - l10n_it_vat_registries

### ISSUE THREAD

**Issue by greenstrategy** [OCA/l10n-italy#157]
Hi i'm new in github and odoo,
i have installed this module but when i try to print the report i receive this error:

Odoo Server Error
Traceback (most recent call last):
File "/opt/odoo/addons/report/controllers/main.py", line 125, in report_download
response = self.report_routes(reportname, converter='pdf', *dict(data))
File "/opt/odoo/openerp/http.py", line 388, in response_wrap
response = f(args, *kw)
File "/opt/odoo/addons/report/controllers/main.py", line 65, in report_routes
pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
File "/opt/odoo/openerp/api.py", line 237, in wrapper
return old_api(self, *args, *kwargs)
File "/opt/odoo/addons/report/models/report.py", line 186, in get_pdf
html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
File "/opt/odoo/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo/addons/report/models/report.py", line 161, in get_html
return particularreport_obj.render_html(cr, uid, ids, data=data, context=context)
File "/opt/odoo/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo/addons/report/models/abstract_report.py", line 64, in render_html
return self.pool['report'].render(cr, uid, [], self._template, docargs, context=context)
File "/opt/odoo/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo/addons/report/models/report.py", line 147, in render
return view_obj.render(cr, uid, template, values, context=context)
File "/opt/odoo/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo/addons/website/models/ir_ui_view.py", line 171, in render
return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
File "/opt/odoo/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1007, in render
return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
File "/opt/odoo/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 253, in render
return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
g_inner.append(self.render_node(current_node, qwebcontext))
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
result = self._render_tagt_render
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 426, in render_tag_call
d[0] = self.render_element(element, template_attributes, generated_attributes, d)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
g_inner.append(self.render_node(current_node, qwebcontext))
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
result = self._render_tagt_render
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 435, in render_tag_call
return self.render(cr, uid, template, d)
File "/opt/odoo/openerp/api.py", line 237, in wrapper
return old_api(self, args, *kwargs)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 253, in render
return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
g_inner.append(self.render_node(current_node, qwebcontext))
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
g_inner.append(self.render_node(current_node, qwebcontext))
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
g_inner.append(self.render_node(current_node, qwebcontext))
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
g_inner.append(self.render_node(current_node, qwebcontext))
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
g_inner.append(self.render_node(current_node, qwebcontext))
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
g_inner.append(self.render_node(current_node, qwebcontext))
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
result = self._render_tagt_render
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 367, in render_tag_esc
inner = widget.format(template_attributes['esc'], options, qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 982, in format
return escape(self._format(inner, options, qwebcontext))
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 979, in _format
return self.pool['ir.qweb'].eval_str(inner, qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 205, in eval_str
val = self.eval(expr, qwebcontext)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 197, in eval
raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 194, in eval
return qwebcontext.safe_eval(expr)
File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 80, in safe_eval
return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
File "/opt/odoo/openerp/tools/safe_eval.py", line 313, in safe_eval
return eval(c, globals_dict, locals_dict)
File "", line 1, in 
QWebException: "'NoneType' object is not callable" while evaluating
"context_timestamp(datetime.datetime.now()).strftime('%Y')"

Can you help me please ?

**Comment by dcorio** [comment]
can you please give us some infos on how to reproduce this error? how did you configure vat registries, are you using the standard pdc? demo data? etc

**Comment by greenstrategy** [comment]
Hi Davide, nice to meet you.
We use odoo 8 on google cloud engine with ubuntu.
Actually we have integrated crm, sales, purchase, porject ecc. 
Now we are started to use the account module to manage our contabilità.

So we use real data, becouse the sales & purchase invoices are registered and that's data are into sales journal and purchase journal. 

We have also installed the internal account sequence module to manage internal sequence to generate the italian general ledger.

I'm try to use the vat register module to extract the information about IVA.

![vat registry](https://cloud.githubusercontent.com/assets/10291121/11035049/2604cc96-86f0-11e5-93b4-4a3a9b20d433.png)

When i push print i recive the error.

Thanks in advance

**Comment by dcorio** [comment]
@greenstrategy can you try to exclude the opening journal?

**Comment by greenstrategy** [comment]
i recive the same error, do you need other configuration image ?

**Comment by eLBati** [comment]
Ciao @greenstrategy 
potresti descrivere i passi per generare il problema su un nuovo database?

**Comment by greenstrategy** [comment]
Ciao Lorenzo,
perfetto credo sia molto più facile comunicare in Italiano dato che questa è la comunità italiana, no ?

Vuoi che nel sistema crei un nuovo database e proceda con la reinstallazione di tutti i moduli ?

**Comment by dcorio** [comment]
mi sincererei prima di avere odoo e moduli della localizzazione aggiornati

**Comment by greenstrategy** [comment]
come posso controllare se sono installate le ultime versioni sia di odoo che dei moduli ? grazie mille

**Comment by dcorio** [comment]
@greenstrategy dipende da quando hai installato odoo e i moduli.
non ho incontrato problemi sui registri iva ultimamente.
hai provato con un database pulito?
