### ISSUE TITLE
10n_it_fatturapa_out_triple_discount genera errore nei test automatici

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1588]
Versioni coinvolte:

 - [ ] 10.0
 - [x] 12.0: ~https://github.com/OCA/l10n-italy/pull/1603~

Comportamento osservato:

Ad esempio
```
2020-01-13 13:00:26,096 5951 INFO openerp_test odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount: test_xml_export_triple_discount (odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount.TestInvoiceTripleDiscount)
2020-01-13 13:00:27,917 5951 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount: FAIL
2020-01-13 13:00:27,917 5951 INFO openerp_test odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount: ======================================================================
2020-01-13 13:00:27,917 5951 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount: FAIL: test_xml_export_triple_discount (odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount.TestInvoiceTripleDiscount)
2020-01-13 13:00:27,917 5951 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount: Traceback (most recent call last):
2020-01-13 13:00:27,917 5951 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount: `   File "/home/travis/build/OCA/l10n-italy/l10n_it_fatturapa_out_triple_discount/tests/test_fatturapa_triple_discount.py", line 50, in test_xml_export_triple_discount
2020-01-13 13:00:27,918 5951 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount: `     module_name='l10n_it_fatturapa_out_triple_discount')
2020-01-13 13:00:27,918 5951 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount: `   File "/home/travis/build/OCA/l10n-italy/l10n_it_fatturapa_out/tests/fatturapa_common.py", line 122, in check_content
2020-01-13 13:00:27,918 5951 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount: `     self.assertEqual(etree.tostring(test_fatt), etree.tostring(xml))
2020-01-13 13:00:27,918 5951 ERROR openerp_test odoo.addons.l10n_it_fatturapa_out_triple_discount.tests.test_fatturapa_triple_discount: ` AssertionError: b'<ns[2618 chars]ento>1.53</ImportoPagamento></DettaglioPagamen[65 chars]ica>' != b'<ns[2618 chars]ento>5.28</ImportoPagamento></DettaglioPagamen[65 chars]ica>'
```
(https://travis-ci.org/OCA/l10n-italy/jobs/636339731)

**Comment by eLBati** [comment]
@tafaRU @SimoRubi disabilitiamo i test del modulo nel frattempo?

**Comment by tafaRU** [comment]
@eLBati per me è ok. @SimoRubi tu che dici?

**Comment by SimoRubi** [comment]
Ciao! Per me disabilitare i test non è una buona idea: lasciando il problema aperto si spera che qualcuno prima o poi lo risolverà (se avessi il tempo di farlo proverei direttamente io), nasconderlo disabilitando i test lascia il problema latente e potrebbe rispuntare in futuro.

**Comment by eLBati** [comment]
Il problema andrà risolto, però ci sono PR aperte (tipo https://github.com/OCA/l10n-italy/pull/1482) su cui ho già lanciato 4 o 5 volte il comando di merge che è fallito per questo problema.

**Comment by OpenCode** [comment]
@eLBati L'alternativa sarebbe mergiare a mano le PR facendo bump manuale della versione nel file di manifest

**Comment by eLBati** [comment]
Non caricherei di lavoro i contributori a causa di un modulo che probabilmente non andava rilasciato, in quanto problematico.
A questo punto, visto che nessuno sembra interessato a sistemare il modulo (io non lo uso quindi non prevedo di aggiustarlo) piuttosto che rimuovere il modulo, disabilitiamo i test: https://github.com/OCA/l10n-italy/pull/1603

**Comment by tafaRU** [comment]
Sul branch `10.0` si verifica lo stesso problema?

**Comment by eLBati** [comment]
@tafaRU mi pare di sì
