### ISSUE TITLE
[SOLVED][11] errore esportazione fattura elettronica

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#1591]
ho importato i dati da odoo 10 con openupgrade, sembrava tutto ok, ma quando sono arrivato a formulare una nuova fattura, nell'esportazione  ho questo errore:

`
Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/odoo/addons/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 853, in exportFatturaPA
    inv, invoice_body)
  File "/usr/lib/python3.7/site-packages/odoo/addons/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 788, in setFatturaElettronicaBody
    self.setDettaglioLinee(inv, FatturaElettronicaBody)
  File "/usr/lib/python3.7/site-packages/odoo/addons/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 653, in setDettaglioLinee
    unidecode(line.uom_id.name)) or None,
NameError: name 'unidecode' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3.7/site-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3.7/site-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3.7/site-packages/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3.7/site-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3.7/site-packages/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3.7/site-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3.7/site-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3.7/site-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/odoo/addons/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 858, in exportFatturaPA
    except (SimpleFacetValueError, SimpleTypeValueError) as e:
NameError: name 'SimpleFacetValueError' is not defined
_`

**Comment by matteoopenf** [comment]
Forse è banale, ma unidecode lo hai installato?

**Comment by bitit-it** [comment]
HEM!!! no!, installato e funzione .. scusate :(
