### ISSUE TITLE
[8.0] Error export riba l10n_it_ricevute_bancarie

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#165]
Ciao a tutti,
mi dà un'errore sull'esportazione (anche sul runbot) (però non trovo la logica di test dell'esportazione, per cui non so se ho mancato di configurare qualcosa)
Segue errore:

Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/api.py", line 387, in old_api
    result = method(recs, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/models.py", line 5926, in onchange
    record.mapped(field_seq)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/models.py", line 5421, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/models.py", line 5401, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3136254-8-0-11a802/openerp/models.py", line 5639, in __getitem__
    return self._fields[key].__get__(self, type(self))
KeyError: 'riba_'

**Comment by eLBati** [comment]
Grazie @sergiocorato della segnalazione.
Guarda se queste modifiche https://github.com/OCA/l10n-italy/pull/166 risolvono
