### ISSUE TITLE
Errore in configurazione POS attivando "Fatturazione"

### ISSUE THREAD

**Issue by mrcast** [OCA/l10n-italy#1650]
Versioni coinvolte: v.12

Passi per riprodurre:
- Andare su configurazione punto vendita
- Spuntare fatturazione

Comportamento osservato:
ottengo errore

Odoo Server Error
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/.repo_requirements/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f6cb4cac6a8>, 'point_of_sale.pos_sale_journal')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/models.py", line 5524, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/.repo_requirements/odoo/odoo/models.py", line 5368, in _onchange_eval
    method_res = method(self)
  File "/home/odoo/OCB-12.0/addons/point_of_sale/models/pos_config.py", line 264, in _onchange_module_account
    self.invoice_journal_id = self.env.ref('point_of_sale.pos_sale_journal')
  File "/.repo_requirements/odoo/odoo/api.py", line 864, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_model.py", line 1429, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_model.py", line 1413, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_model.py", line 1402, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: point_of_sale.pos_sale_journal

Comportamento atteso:
non ottenere errore

Video/Screenshot (opzionale):

![Peek 21-02-2020 17-22_pos_invoice](https://user-images.githubusercontent.com/15906125/75051943-0fe74680-54cf-11ea-9893-95f80375ad94.gif)

Grazie

**Comment by eLBati** [comment]
Non riesco a riprodurlo su nuovo DB.

Idee?
