### ISSUE TITLE
[8.0] [l10n_it_ricevute_bancarie] Error from wizard RIBA generator if "Group Ri.Ba." is active

### ISSUE THREAD

**Issue by burnout75** [OCA/l10n-italy#170]
To replace the error from a blank installation with demo datas:
-> Install the module l10n_it_ricevute_bancarie
-> On tab Accounting of parter activate "Group Ri.Ba." and set payment as "RiBA 30 Days End of Month"
-> Create new customer invoice, insert a line and validate
-> From Ri.Ba -> Issue RiBa -> Select the line of relative invoice -> Wizard "Salvo buon fine" -> Error

**Comment by burnout75** [comment]
Still open?

`Traceback (most recent call last):
  File "/var/gestionale/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/var/gestionale/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/var/gestionale/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/gestionale/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/gestionale/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/var/gestionale/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/var/gestionale/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/var/gestionale/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/var/gestionale/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/var/gestionale/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/gestionale/openerp/api.py", line 387, in old_api
    result = method(recs, *args, **kwargs)
  File "/var/gestionale/.local/share/Odoo/addons/8.0/l10n_it_ricevute_bancarie/wizard/wizard_riba_issue.py", line 110, in create_list
    'move_line_id': grouped_line.id,
  File "/var/gestionale/openerp/api.py", line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/gestionale/openerp/models.py", line 4094, in create
    record = self.browse(self._create(old_vals))
  File "/var/gestionale/openerp/api.py", line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/gestionale/openerp/api.py", line 496, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/var/gestionale/openerp/models.py", line 4232, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/var/gestionale/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/var/gestionale/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: can't adapt type 'riba.distinta.line'`

**Comment by eLBati** [comment]
Ciao @burnout75 
this is fixed with https://github.com/OCA/l10n-italy/pull/201
