### ISSUE TITLE
[10.0] l10n_it_intrastat_statement: ValueError: External ID not found in the system: web.internal_layout

### ISSUE THREAD

**Issue by fredzamoabg** [OCA/l10n-italy#1897]
Versioni coinvolte:
10.0

Passi per riprodurre:
andare su Contabilita' > Registrazioni Sezionale > Dichiarazioni intrastat
seleziono una dichiarazione
andate in Stampa (bottone in alto)
selezionare, ad esempio, Mod INTRA 1-bis

Comportamento osservato:
salta l'eccezione:

Traceback (most recent call last):
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/report/models/report.py", line 181, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/report/models/report.py", line 147, in get_html
    return self.render(report.report_name, docargs)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/report/models/report.py", line 123, in render
    return view_obj.render_template(template, values)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 1069, in render
    return self.env[engine].render(self.id, qcontext)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 249, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 318, in _compiled_fn
    raise e
QWebException: None
Traceback (most recent call last):
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 342, in get_template
    document = options.get('load', self.load)(template, options)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 81, in load
    template = env['ir.ui.view'].read_template(name)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 944, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 956, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_model.py", line 1094, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_model.py", line 1085, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-5>", line 2, in xmlid_lookup
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/srv/odoo-10-endian10-prod/endian10/odoo/lib/python2.7/site-packages/odoo/addons/base/ir/ir_model.py", line 1074, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: web.internal_layout

load could not load template
Template: web.internal_layout

da una breve analisi sembrerebbe essere legato dalla rimozione del modulo "web" tra le dipendenze.

Comportamento atteso:
assenza di eccezioni

**Comment by fredzamoabg** [comment]
errore visto anche su runbot (10.0)

Traceback (most recent call last):
  File "/.repo_requirements/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/.repo_requirements/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/.repo_requirements/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/.repo_requirements/odoo/addons/report/models/report.py", line 181, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/.repo_requirements/odoo/addons/report/models/report.py", line 147, in get_html
    return self.render(report.report_name, docargs)
  File "/.repo_requirements/odoo/addons/report/models/report.py", line 123, in render
    return view_obj.render_template(template, values)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1052, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/.repo_requirements/odoo/addons/website/models/ir_ui_view.py", line 115, in render
    return super(View, self).render(values, engine=engine)
  File "/.repo_requirements/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1072, in render
    return self.env[engine].render(self.id, qcontext)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 251, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 320, in _compiled_fn
    raise e
QWebException: None
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 344, in get_template
    document = options.get('load', self.load)(template, options)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 81, in load
    template = env['ir.ui.view'].read_template(name)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 947, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-43>", line 2, in get_view_id
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/.repo_requirements/odoo/addons/website/models/ir_ui_view.py", line 87, in get_view_id
    return super(View, self).get_view_id(xml_id)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 959, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 1108, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 1099, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-6>", line 2, in xmlid_lookup
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 1088, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: web.internal_layout

load could not load template
Template: web.internal_layout

**Comment by eLBati** [comment]
Sulla 12 non si verifica?

**Comment by tafaRU** [comment]
@eLBati vedendo https://github.com/OCA/l10n-italy/pull/1920 direi di no.

**Comment by OpenCode** [comment]
Issue inerente la versione 10.0 che non è più supportata
