### ISSUE TITLE
[Odoo12] problema aggiornamento versione I10n_it_ddt

### ISSUE THREAD

**Issue by tobesmartcs** [OCA/l10n-italy#1904]
Versioni coinvolte: 12.0.1.6.1 - 12.0.1.8.0

Passi per riprodurre: aggiornamento tramite linea di comando o caricamento file via sftp

Comportamento osservato: ERROR: Could not find a version that satisfies the requirement odoo<12.1dev,>=12.0a (from odoo12-addon-l10n-it-ddt) (from versions: none)
ERROR: No matching distribution found for odoo<12.1dev,>=12.0a (from odoo12-addon-l10n-it-ddt)

Ragazzi, sto ricevendo l'errore descritto sopra quando provo ad aggiornare dalla versione 12.0.1.6.1 alla 12.0.1.8.0
Ho provato sia tramite linea di comando (Odoo12 installato su VPS con Centos7) si sovrascrivendo i file tramite caricamento sftp

**Comment by sergiocorato** [comment]
Altri moduli di Odoo installati tramite pip ti si installano senza problemi?

**Comment by tobesmartcs** [comment]
Si non ho avuto problemi con altri moduli. 
Questo non riesco ad installarlo neanche copiando la cartella via sftp ed installando dall'interfaccia web. O meglio lo installo ma non riesco ad accedere al menù Documento di trasporto.

**Comment by sergiocorato** [comment]
pip di per sè prende i file da web, non mi è chiaro cosa copi, il modulo su una cartella? Dall'interfaccia web installi un modulo già presente, quindi è irrilevante. Se lo installi e non vedi un menu, dovresti guardare se l'installazione è andata a buon fine.

**Comment by tobesmartcs** [comment]
Forse ho incasinato io la spiegazione... Allora avevo la versione 12.0.1.6.1 del modulo l10n-it-ddt. Mi sono reso conto che c'era un upgrade. Ho provato ad aggiornare via terminal con il comando pip, ma ottengo l'errore che ho postato.

Successivamente ho provato a caricare (quindi sovrascrivere) i file contenuti nell'archivio l10n-it-ddt via sftp nella cartella custom-addons. Quindi dall'interfaccia web di Odoo, nella sezione applicazioni ho cliccato su aggiorna. Il modulo non si aggiorna ed a schermo ottengo questo errore:

`Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo12/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_upgrade
  File "/opt/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 627, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo12/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/odoo12/odoo/modules/migration.py", line 181, in migrate_module
    mod = load_script(pyfile, name)
  File "/opt/odoo/odoo12/odoo/modules/migration.py", line 46, in load_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/odoo/odoo12-custom-addons/l10n_it_ddt/migrations/12.0.1.7.1/pre-migrate.py", line 4, in <module>
    from openupgradelib import openupgrade
ModuleNotFoundError: No module named 'openupgradelib'`
```

**Comment by sergiocorato** [comment]
È evidente che manca la libreria openupgradelib

**Comment by tobesmartcs** [comment]
Giusto!! Scusami ma sono novellino... Appena possibile installo la libreria e ti do feedback. 
Grazie

**Comment by sergiocorato** [comment]
Prego. Chiudo la issue, nel caso ne puoi aprire un'altra.
