### ISSUE TITLE
l10n_it_vat_registries: i test falliscono a cavallo della mezzanotte

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1921]
Versioni coinvolte:

 - [X] 11.0 - https://github.com/OCA/l10n-italy/pull/2160
 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/2172

Passi per riprodurre:

Lanciare una build travis a cavallo della mezzanotte

Comportamento osservato:

I test di `l10n_it_vat_registries` falliscono con
```
 ERROR openerp_test odoo.addons.l10n_it_vat_registries.tests.test_registry: ERROR: test_invoice_and_report (odoo.addons.l10n_it_vat_registries.tests.test_registry.TestRegistry)
 ERROR openerp_test odoo.addons.l10n_it_vat_registries.tests.test_registry: Traceback (most recent call last):
 ERROR openerp_test odoo.addons.l10n_it_vat_registries.tests.test_registry: `   File "/home/travis/build/OCA/l10n-italy/l10n_it_vat_registries/tests/test_registry.py", line 67, in test_invoice_and_report
 ERROR openerp_test odoo.addons.l10n_it_vat_registries.tests.test_registry: `     res = wizard.print_registro()
 ERROR openerp_test odoo.addons.l10n_it_vat_registries.tests.test_registry: `   File "/home/travis/build/OCA/l10n-italy/l10n_it_vat_registries/wizard/print_registro_iva.py", line 75, in print_registro
 ERROR openerp_test odoo.addons.l10n_it_vat_registries.tests.test_registry: `     move_ids = self._get_move_ids(wizard)
 ERROR openerp_test odoo.addons.l10n_it_vat_registries.tests.test_registry: `   File "/home/travis/build/OCA/l10n-italy/l10n_it_vat_registries/wizard/print_registro_iva.py", line 64, in _get_move_ids
 ERROR openerp_test odoo.addons.l10n_it_vat_registries.tests.test_registry: `     raise UserError(_('No documents found in the current selection'))
 ERROR openerp_test odoo.addons.l10n_it_vat_registries.tests.test_registry: ` odoo.exceptions.UserError: ('No documents found in the current selection', '')
```

Probabilmente perchè i test sono partiti prima di mezzanotte, quindi hanno creato fatture il giorno prima del lancio del registro IVA

**Comment by SilvioGregorini** [comment]
@eLBati se il problema è che le fatture vengono create prima di mezzanotte mentre la `search` dentro `_get_move_ids` viene eseguita dopo, si potrebbe aggiornare la creazione del wizard in `tests/test_registry.py` da così:
```
        wizard = self.env['wizard.registro.iva'].create({
            'from_date': fields.Date.today(),
            'to_date': fields.Date.today(),
            'tax_registry_id': tax_registry.id,
            'layout_type': 'supplier',
            'fiscal_page_base': 0,
        })
```
a così
```
        wizard = self.env['wizard.registro.iva'].create({
            'from_date': fields.Date.today() - relativedelta(days=1),
            'to_date': fields.Date.today() + relativedelta(days=1),
            'tax_registry_id': tax_registry.id,
            'layout_type': 'supplier',
            'fiscal_page_base': 0,
        })
```

In questo modo, si potrebbe risolvere il problema (ma magari non mi vengono in mente delle controindicazioni funzionali).

**Comment by eLBati** [comment]
Per v12: https://github.com/OCA/l10n-italy/pull/2172
