### ISSUE TITLE
[Odoo12] problema aggiornamento versione I10n_it_ddt

### ISSUE THREAD

**Issue by Zephyria77** [OCA/l10n-italy#1922]
Versioni coinvolte: 12.0.1.6.1 - 12.0.1.8.0

Passi per riprodurre: aggiornamento tramite interfaccia web

Comportamento osservato: Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1131, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 568, in raise_view_error
    raise ValueError(message)
ValueError: Il campo `show_price` non esiste

Comportamento atteso: aggiornamento andato a buon fine

Video/Screenshot (opzionale):

**Comment by matteoopenf** [comment]
Sera,
scusa ma hai utilizzato la versione nuova di openupgrade, se non la usi da errore, c'è scritto anche nel merge della PR

**Comment by Zephyria77** [comment]
Certo, ho seguito le istruzioni della pr usando questo comando
pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master
però in ogni caso ho questo errore 

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_upgrade
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 627, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/usr/lib/python3/dist-packages/odoo/modules/migration.py", line 181, in migrate_module
    mod = load_script(pyfile, name)
  File "/usr/lib/python3/dist-packages/odoo/modules/migration.py", line 46, in load_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/l10n-italy-12.0/l10n_it_ddt/migrations/12.0.1.7.1/pre-migrate.py", line 4, in <module>
    from openupgradelib import openupgrade
  File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade.py", line 57, in <module>
    from psycopg2 import sql
ImportError: cannot import name 'sql'

**Comment by matteoopenf** [comment]
Ciao ho letto ora, ma essendo Python3 non dovresti usare pip3 al posto di pip?
O è un refuso quello che hai scritto?


Matteo Mircoli
Developer | matteomircoli@openforce.it 

> Il giorno 17 ott 2020, alle ore 18:14, Zephyria77 <notifications@github.com> ha scritto:
> 
> ﻿
> Certo, ho seguito le istruzioni della pr usando questo comando
> pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master
> però in ogni caso ho questo errore
> 
> Odoo Server Error
> Traceback (most recent call last):
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
> return super(JsonRequest, self)._handle_exception(exception)
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
> raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
> File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
> raise value
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
> result = self._call_function(**self.params)
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
> return checked_call(self.db, *args, **kwargs)
> File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
> return f(dbname, *args, **kwargs)
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
> result = self.endpoint(*a, **kw)
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in call
> return self.method(*args, **kw)
> File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
> response = f(*args, **kw)
> File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
> action = self._call_kw(model, method, args, {})
> File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
> return call_kw(request.env[model], method, args, kwargs)
> File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
> return _call_kw_multi(method, model, args, kwargs)
> File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
> result = method(recs, *args, **kwargs)
> File "", line 2, in button_immediate_upgrade
> File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
> return method(self, *args, **kwargs)
> File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 627, in button_immediate_upgrade
> return self._button_immediate_function(type(self).button_upgrade)
> File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
> modules.registry.Registry.new(self._cr.dbname, update_module=True)
> File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
> odoo.modules.load_modules(registry._db, force_demo, status, update_module)
> File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 417, in load_modules
> force, status, report, loaded_modules, update_module, models_to_check)
> File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
> perform_checks=perform_checks, models_to_check=models_to_check
> File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 177, in load_module_graph
> migrations.migrate_module(package, 'pre')
> File "/usr/lib/python3/dist-packages/odoo/modules/migration.py", line 181, in migrate_module
> mod = load_script(pyfile, name)
> File "/usr/lib/python3/dist-packages/odoo/modules/migration.py", line 46, in load_script
> spec.loader.exec_module(module)
> File "", line 673, in exec_module
> File "", line 222, in _call_with_frames_removed
> File "/opt/l10n-italy-12.0/l10n_it_ddt/migrations/12.0.1.7.1/pre-migrate.py", line 4, in 
> from openupgradelib import openupgrade
> File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade.py", line 57, in 
> from psycopg2 import sql
> ImportError: cannot import name 'sql'
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 

_
Openforce Srls Unipersonale *| www.openforce.it 
<http://www.openforce.it/> |*__ 02 21119472 | Via Tiziano,32 20145 Milano_

**Comment by Zephyria77** [comment]
si certo, ho fatto copia e incolla,scusa
comunque ho usato pip3, stavo cercando info su psycopg2 ma ho concluso poco finora

**Comment by matteoopenf** [comment]
> si certo, ho fatto copia e incolla,scusa
> comunque ho usato pip3, stavo cercando info su psycopg2 ma ho concluso poco finora

Non so dirti di più mi spiace, da noi come ho suggerito sopra ha funzionato

**Comment by tafaRU** [comment]
> File "/usr/local/lib/python3.5/dist-packages/openupgradelib/openupgrade.py", line 57, in
> from psycopg2 import sql
> ImportError: cannot import name 'sql'

Forse perché nel tuo virtualenv non è installato `psycopg2`.

**Comment by Zephyria77** [comment]
Ho controllato e mi risulta installata la versione 2.6.2-1

**Comment by eLBati** [comment]
Direi che si tratta di un problema di deploy e comunque non un malfunzionamento del modulo. Chiudo
