### ISSUE TITLE
Installazione app: server timeout blocca installazioni senza segnalare problemi

### ISSUE THREAD

**Issue by Jorkut** [OCA/l10n-italy#1935]
**Versioni coinvolte:**
12.0

**Passi per riprodurre:**
Installare odoo, caricare tutti i moduli della community italiana, creare il database, selezionare la sezione "applicazioni" e installare **tutti e soli i moduli della community italiana** (eccetto il modulo "Italia - Fatturazione elettronica" che va in conflitto con "ITA - Fatturazione elettronica - Base") e avviare l'installazione

**Comportamento osservato:**
l'applicazione va in timeout e si riconnette senza segnalare errori; facendo il refresh della pagina, l'applicazione mostra i moduli installati nella lista delle app (pulsante del menù in alto a sinistra). Andando in "Impostazioni > Impostazioni generali", il server restituisce un errore (diverso ogni volta che si effettua il procedimento):

`Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1396, in load_views
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1396, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_config.py", line 395, in fields_view_get
    toolbar=toolbar, submenu=submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1482, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1131, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 568, in raise_view_error
    raise ValueError(message)
ValueError: Il campo `group_display_incoterm` non esiste

Contesto errore:
Vista `n/d`
[view_id: n/d, xml_id: n/d, model: n/d, parent_id: n/d]`

Il motivo del problema potrebbe risiedere nel fatto di installare molti moduli contemporaneamente: a quanto pare selezionare tutti i moduli insieme e avviare l'installazione, il tempo necessario manda in timeout la piattaforma che , successivamente, si riconnette bloccando probabilmente le installazioni in corso, **ma senza indicare alcun errore e confermando l'avvenuta riconnessione**; questo, oltre a dare la falsa impressione che sia andato tutto a buon fine, comporta il fatto che alcuni moduli potrebbero non essere stati completamente installati (infatti alcuni risultano ancora "da installare".

I moduli non completamente installati potrebbero aver alterato la parte relativa delle impostazioni, producendo quell'errore lato server; ri-selezionando i moduli e reinstallandoli il problema sembra non verificarsi più.

**Comportamento atteso:**
in caso di timeout segnalare un avviso sul fatto che l'installazione dei moduli potrebbe essere stata interrotta e di verificare se l'installazione sia andata a buon fine.

**Comment by eLBati** [comment]
Non è un malfunzionamento dei moduli di localizzazione. Probabilmente neanche di odoo, sembra un problema di deploy
