### ISSUE TITLE
[8.0] l10n_it_fatturapa_in: errore in configurazione round up e down account

### ISSUE THREAD

**Issue by PatosMarco** [OCA/l10n-italy#2005]
**Versioni coinvolte:**

- [X]  8.0 - https://github.com/OCA/l10n-italy/pull/2023

**Passi per riprodurre:**

Installare il modulo l10n_it_fatturapa_in e provare ad impostare i conti contabili per la gestione di arrotondamenti attivi e passivi all'interno delle impostazioni di contabilità, nella sezione configurazione.

**Comportamento osservato:**

In fase di scelta del conto contabile il sistema restituisce l'errore visibile di seguito. Al click del mouse su uno di quei campi: round up e round down. Lo stesso avviene se si prova a settarli dai parametri aziendali forzandone la comparsa nella vista dedicata.

```
Traceback (most recent call last):
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/buildout/parts/odoo/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/buildout/parts/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/buildout/parts/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/addons/account/account.py", line 622, in name_search
    ids = self.search(cr, user, args, context=context, limit=limit)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/addons/account/account.py", line 276, in search
    order, context=context, count=count)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/openerp/models.py", line 1650, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/openerp/models.py", line 4709, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/addons/account/account.py", line 260, in _where_calc
    return super(account_account, self)._where_calc(cr, uid, domain, active_test, context)
  File "/opt/odoo/buildout/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/openerp/models.py", line 4520, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/opt/odoo/buildout/parts/odoo/openerp/osv/expression.py", line 662, in __init__
    self.parse(cr, uid, context=context)
  File "/opt/odoo/buildout/parts/odoo/openerp/osv/expression.py", line 830, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'deprecated' in leaf "<osv.ExtendedLeaf: ('deprecated', '=', False) on account_account (ctx: )>"
```

**Comportamento atteso:**

Possibilità di scegliere i conti contabili senza errori e di conseguenza poter procedere all'import di quelle fatture passive che presentano il tag arrotondamento. Il problema sembra esser dovuto, o comunque collegato, al dominio collegato su quei campi: ('deprecated', '=', False) perché rimuovendolo è possibile associare senza problemi i conti desiderati.

![Schermata 2020-12-28 alle 23 48 56](https://user-images.githubusercontent.com/60786718/103247627-ccb7f880-4967-11eb-9216-4c834634a542.png)

Video/Screenshot (opzionale):

**Comment by vincenzoterzulli** [comment]
Grazie per la segnalazione.
Prendo in carico io la correzione. Ti avviso non appena faccio PR

**Comment by vincenzoterzulli** [comment]
PR creata.

**Comment by eLBati** [comment]
Se coinvolge solo la 8, si può chiudere

**Comment by vincenzoterzulli** [comment]
@PatosMarco potresti chiudere questa issue? Credo che ti basti modificare la issue e mettere la `x` tra le `[ ]` ovvero `[x]` per mettere il task a completato. Grazie

**Comment by OpenCode** [comment]
> @PatosMarco potresti chiudere questa issue? Credo che ti basti modificare la issue e mettere la `x` tra le `[ ]` ovvero `[x]` per mettere il task a completato. Grazie

Quale PR risolve questo problema?

**Comment by vincenzoterzulli** [comment]
> Quale PR risolve questo problema?
La #2023. C'è anche le menziona poco sopra. Risolsi questo problema già parecchio tempo fa.

**Comment by OpenCode** [comment]
Fatto. Grazie.
