### ISSUE TITLE
Errore nell'esportazione della fattura elettronica

### ISSUE THREAD

**Issue by account-vr** [OCA/l10n-italy#2024]
Versioni coinvolte: 12.0

Passi per riprodurre: esporta e-Fattura

Comportamento osservato:  dopo aver creato una fattura e pigiato il tasto esporta e-fattura compare la schermata dove propone di aggiungere un allegato, facendo esporta va in errore come specificato sotto.

Comportamento atteso: dopo aver pigiato esporta mi attendo la nuova schermata per l'invio allo SDI

Questa installazione è nuova ed è stato installato il modulo fattura pa e le sue dipendenze tramite pip "pip install --pre odoo12-addon-l10n-it-fatturapa-pec".
Ho altre installazioni dove gli addons sono stati installati scaricando il codice sorgente e funzionano perfettamente.

Avete qualche suggerimento?
Grazie mille per l'attenzione
Vincenzo

Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 967, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/odoo/addons/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 922, in exportFatturaPA
    attach = self.saveAttachment(fatturapa, number)
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/odoo/addons/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 111, in saveAttachment
    bds=fatturapaBDS,
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/basis.py", line 560, in toxml
    dom = self.toDOM(bds, element_name=element_name)
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/basis.py", line 532, in toDOM
    self._toDOM_csc(bds, element)
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/basis.py", line 2694, in _toDOM_csc
    content.elementDeclaration.toDOM(dom_support, parent, content.value)
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/content.py", line 1101, in toDOM
    value._toDOM_csc(dom_support, element)
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/basis.py", line 2694, in _toDOM_csc
    content.elementDeclaration.toDOM(dom_support, parent, content.value)
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/content.py", line 1101, in toDOM
    value._toDOM_csc(dom_support, element)
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/basis.py", line 2694, in _toDOM_csc
    content.elementDeclaration.toDOM(dom_support, parent, content.value)
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/content.py", line 1101, in toDOM
    value._toDOM_csc(dom_support, element)
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/basis.py", line 2680, in _toDOM_csc
    order = self._validatedChildren()
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/basis.py", line 2207, in _validatedChildren
    return self.__automatonConfiguration.sequencedChildren()
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/content.py", line 638, in sequencedChildren
    cfg = self._diagnoseIncompleteContent(symbols, symbol_set)
  File "/opt/odoo/odoo-venv/lib/python3.7/site-packages/pyxb/binding/content.py", line 493, in _diagnoseIncompleteContent
    raise pyxb.IncompleteElementContentError(self.__instance, cfg, symbols, symbol_set)
pyxb.exceptions_.IncompleteElementContentError: (<odoo.addons.l10n_it_fatturapa.bindings.binding.DatiAnagraficiRappresentanteType object at 0x7fc685d64518>, <pyxb.utils.fac.Configuration object at 0x7fc685d78d30>, [], {<pyxb.binding.content.ElementDeclaration object at 0x7fc67fddd518>: ['RGGVCN70E14B429H'], <pyxb.binding.content.ElementDeclaration object at 0x7fc67fddd588>: [<odoo.addons.l10n_it_fatturapa.bindings.binding.AnagraficaType object at 0x7fc685d786d8>]})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 714, in dispatch
    return self._handle_exception(e)
  File "/opt/odoo/odoo/odoo/http.py", line 676, in _handle_exception
    return self._json_response(error=error)
  File "/opt/odoo/odoo/odoo/http.py", line 644, in _json_response
    body = json.dumps(response, default=date_utils.json_default)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not ElementDeclaration

**Comment by eLBati** [comment]
Servono i passi precisi per riprodurlo

**Comment by account-vr** [comment]
Forse ho individuato il "problema".
Nelle impostazioni della contabilità, su Fatture elettroniche, ho rimosso il nome del rappresentante legale lasciando libero il campo, facendo così mi permette di esportare le fatture elettroniche.
Non so se questo comportamento è corretto, forse questo campo non è necessario?

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
