### ISSUE TITLE
Errore nell'upgrade alla verisone 12.0.1.5.0

### ISSUE THREAD

**Issue by c-amara** [OCA/l10n-italy#2065]
Versioni coinvolte:

Passi per riprodurre: aggiornare alla versione 12.0.1.5.0

Comportamento osservato: Effetuato l'aggiornamento si ottiene un errore: 
Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 1131, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 568, in raise_view_error
    raise ValueError(message)
ValueError: Il campo `riba_exclude_expenses` non esiste

Contesto errore:
Vista `res.parner.form.riba`
[view_id: 2453, xml_id: l10n_it_ricevute_bancarie.view_partner_form_riba, model: res.partner, parent_id: 113]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 3866, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 1522, in _load_records_write
    super(View, self)._load_records_write(values)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 3804, in _load_records_write
    self.write(values)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 445, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 3375, in write
    fields[0].determine_inverse(records)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/fields.py", line 1164, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 445, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 3349, in write
    self._write(store_vals)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 3485, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Errore nella validazione del vincolo\n\nIl campo `riba_exclude_expenses` non esiste\n\nContesto errore:\nVista `res.parner.form.riba`\n[view_id: 2453, xml_id: l10n_it_ricevute_bancarie.view_partner_form_riba, model: res.partner, parent_id: 113]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_upgrade
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_module.py", line 627, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/modules/loading.py", line 415, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/modules/loading.py", line 311, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/tools/convert.py", line 761, in parse
    pycompat.reraise(
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 3866, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 1522, in _load_records_write
    super(View, self)._load_records_write(values)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 3804, in _load_records_write
    self.write(values)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 445, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 3375, in write
    fields[0].determine_inverse(records)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/fields.py", line 1164, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/base/models/ir_ui_view.py", line 445, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 3349, in write
    self._write(store_vals)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 3485, in _write
    self._validate_fields(vals)
  File "/opt/odoo/odoo12/lib/python3.8/site-packages/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Errore nella validazione del vincolo

Il campo `riba_exclude_expenses` non esiste

Contesto errore:
Vista `res.parner.form.riba`
[view_id: 2453, xml_id: l10n_it_ricevute_bancarie.view_partner_form_riba, model: res.partner, parent_id: 113]
None" while parsing /opt/odoo/odoo12/lib/python3.8/site-packages/odoo/addons/l10n_it_ricevute_bancarie/views/partner_view.xml:7, near
<record id="view_partner_form_riba" model="ir.ui.view">
        <field name="name">res.parner.form.riba</field>
        <field name="model">res.partner</field>
        <field name="inherit_id" ref="base.view_partner_form"/>
        <field name="groups_id" eval="[(4, ref('account.group_account_user'))]"/>
        <field name="arch" type="xml">
            <field name="property_payment_term_id" position="after">
                <field name="group_riba"/>
                <field name="riba_exclude_expenses"/>
            </field>
        </field>
    </record>

Comportamento atteso:

Video/Screenshot (opzionale):

**Comment by tafaRU** [comment]
Il campo `riba_exclude_expenses` è stato aggiunto da https://github.com/OCA/l10n-italy/pull/2025
Pertanto ti è sufficiente aggiornare il modulo `l10n_it_ricevute_bancarie` per risolvere il problema.

**Comment by c-amara** [comment]
L'ultimo aggiornamento che vedo è 12.0.1.5.0 che è quello che mi genera l'errore. 
La versione precedente che ho installata è la 12.0.1.4.0.
Non capisco...

**Comment by tafaRU** [comment]
Con _aggiornare il modulo_ intendo non solo a livello di codice ma anche a livello di database!

**Comment by c-amara** [comment]
Era inteso che non bastava fare l'upload ma aggiornarlo anche... ma se si aggiorna da interfaccia si verifica l'errore.

**Comment by c-amara** [comment]
O almeno a me si verifica...

**Comment by tafaRU** [comment]
Ho appena provato ad installare il modulo aggiornato all'ultima versione su un nuovo db senza rilevare alcun problema.

**Comment by c-amara** [comment]
Non so che dirti... su 2 vm differenti entrambe con Odoo 12 CE mi ha dato lo stesso errore aggiornando dalla 12.0.1.4.0 alla 12.0.1.5.0.
