### ISSUE TITLE
l10n_it_fattura_in solleva errore quando si archivia un template con fornitore collegato

### ISSUE THREAD

**Issue by tafaRU** [OCA/l10n-italy#2186]
Versioni coinvolte:

- [x] 10.0: https://github.com/OCA/l10n-italy/pull/2194
- [x] 12.0: https://github.com/OCA/l10n-italy/pull/2187
- [x] 14.0: #2378

Passi per riprodurre:

- non abilitare le varianti
- definire su un template un fornitore (`product.supplierinfo`) specificando il suo Codice prodotto fornitore (`product_code`), es. `XXXXXX`
- archiviare il template (`product.template`) precedente 
- importare un file xml dove all'interno di uno dei suoi tag `<DettaglioLinee>` sia specificato in `<CodiceArticolo>` lo stesso codice indicato sopra
Es:
```
<DettaglioLinee>
<NumeroLinea>2</NumeroLinea>
<CodiceArticolo>
<CodiceTipo>Codice articolo fornitore</CodiceTipo>
<CodiceValore>XXXXXX</CodiceValore>
</CodiceArticolo>
```

Comportamento osservato:

Viene sollevato il seg. errore:

```
Traceback (most recent call last):
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1485, in importFatturaPA
    fatt, fatturapa_attachment, fattura, partner_id)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 929, in invoiceCreate
    FatturaBody, credit_account_id, partner, wt_founds, invoice_data)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/addons/l10n_it_fatturapa_in_rc/wizard/wizard_import_fatturapa.py", line 38, in set_invoice_line_ids
    FatturaBody, credit_account_id, partner, wt_found, invoice_data)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1391, in set_invoice_line_ids
    product = self.get_line_product(line, partner)
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 403, in get_line_product
    product = templates.product_variant_ids[0]
  File "/srv/odoo-12-customer-test/customer/odoo/lib/python3.6/site-packages/odoo/models.py", line 5152, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range
```

**Questo avviene perché l'archiviazione del template (`product.template`)  comporta anche quella dell'unica variante associata (`product.product`).**

Comportamento atteso:
il file viene importato correttamente.

**Comment by TheMule71** [comment]
#2378

**Comment by TheMule71** [comment]
Task list completata.
