### ISSUE TITLE
Registrazione pagamento di una fattura

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2223]
Versioni coinvolte: l10n_it 14.0 supermerge  - Odoo 14

Passi per riprodurre: attivazione del modulo witholding taxes. Disattivando i moduli l10n_it e riattivandoli un ad uno manualmente si osserve che con il modulo withholding taxes attivato si genera questo compotamento 

Comportamento osservato: alla registrazione di un pagamento di una fattura estera o italiana viene generato un errore 

Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/addons/account/wizard/account_payment_register.py", line 531, in action_create_payments
    payments = self._create_payments()
  File "/home/odoo/src/odoo/addons/account/wizard/account_payment_register.py", line 524, in _create_payments
    (payment_lines + lines)\
  File "/home/odoo/src/odoo/addons/account_edi/models/account_move.py", line 257, in reconcile
    res = super().reconcile()
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 4597, in reconcile
    partials = self.env['account.partial.reconcile'].create(sorted_lines._prepare_reconciliation_partials())
  File "<decorator-gen-226>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 326, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/odoo/api.py", line 326, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/user/odoo-italia/l10n-italy/l10n_it_withholding_tax/models/account.py", line 57, in create
    if invoice and invoice.withholding_tax and invoice.amount_net_pay:
  File "/home/odoo/src/odoo/odoo/fields.py", line 963, in __get__
    record.ensure_one()
  File "/home/odoo/src/odoo/odoo/models.py", line 4991, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: account.move(36, 80)

Comportamento atteso: registrazione pagamento

**Comment by mpfoodex** [comment]
anche dopo aggiornamento all'ultima versione appena si attiva l10n_it_withholding_tax le registrazioni di fatture e la creazione di note di credito a partire da una fattura di vendita falliscono. 
Probabilmente il motivo è sempre lo stesso visto che uqando si crea una nc odoo procede subito anche alla registrazione.

**Comment by TheMule71** [comment]
Questa issue è ancora valida per il branch ufficiale 14.0?

**Comment by francescapenso** [comment]
no è stata sistemata da Davide Corio un mesetto fa almeno, mi pareva avessi
detto di chiudere la issue..forse è sfuggita

Il giorno mar 1 giu 2021 alle ore 19:25 Marco Colombo <
***@***.***> ha scritto:
