### ISSUE TITLE
[14.0] fatturapa_in errore bloccante importazione fatture 

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2271]
14.0 supermege
Importare una fattura in  
Errore 

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/odoo-italia/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1525, in importFatturaPA
    invoice = self.invoiceCreate(
  File "/home/odoo/src/user/odoo-italia/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1002, in invoiceCreate
    self.set_roundings(FatturaBody, invoice)
  File "/home/odoo/src/user/odoo-italia/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1171, in set_roundings
    self.env["account.move.line"].with_context(
  File "<decorator-gen-175>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 3860, in create
    lines = super(AccountMoveLine, self).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 3868, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/odoo/models.py", line 4026, in _create
    field.create([
  File "/home/odoo/src/odoo/odoo/fields.py", line 3038, in create
    self.write_batch(record_values, True)
  File "/home/odoo/src/odoo/odoo/fields.py", line 3064, in write_batch
    return self.write_real(records_commands_list, create)
  File "/home/odoo/src/odoo/odoo/fields.py", line 3632, in write_real
    cr.execute(query, pairs)
  File "<decorator-gen-3>", line 2, in execute
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.DatatypeMismatch: column "account_tax_id" is of type integer but expression is of type boolean
LINE 1: ...count_move_line_id, account_tax_id) VALUES (1396, false) ON ...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

**Comment by mpfoodex** [comment]
altro problema. 
non funziona correttamente la features collega a fattura fornitore 
noltre, non so se questo comportamento è voluto, posso solo collegarla a fatture fornitore in bozza 

Di seguito anche la copia completa dell'errore 
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/odoo-italia/l10n-italy/l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py", line 147, in link
    line.link()
  File "/home/odoo/src/user/odoo-italia/l10n-italy/l10n_it_fatturapa_in/wizard/link_to_existing_invoice.py", line 61, in link
    import_wiz.set_summary_data(FatturaBody, self.invoice_id.id)
  File "/home/odoo/src/user/odoo-italia/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1376, in set_summary_data
    invoice_id = invoice.id
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'int' object has no attribute 'id'

**Comment by TheMule71** [comment]
> 14.0 supermege
> Importare una fattura in
> Errore

Hai modo di provare:

```diff --git a/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py b/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
index 9c6b06459..7702b3718 100644
--- a/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
+++ b/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
@@ -1169,8 +1169,10 @@ class WizardImportFatturapa(models.TransientModel):
                         "account_id": arrotondamenti_account_id,
                         "price_unit": abs(to_round),
                         "exclude_from_invoice_tab": True,
-                        "tax_ids": [(6, 0, [invoice_line_tax_id])],
                     }
+                    if invoice_line_tax_id:
+                        upd_vals["tax_ids"] = [(6, 0, [invoice_line_tax_id])]
+
                     # Valutare se in caso di importazione senza rounding sia meglio
                     # lavorare su debito e credito invece di
                     # mettere una tassa sul valore !!
```

**Comment by TheMule71** [comment]
> AttributeError: 'int' object has no attribute 'id'

Dovrebbe essere sistemato in 455d406e0

**Comment by francescapenso** [comment]
> > AttributeError: 'int' object has no attribute 'id'
> 
> Dovrebbe essere sistemato in [455d406](https://github.com/OCA/l10n-italy/commit/455d406e00017983000e2e654e2e9f827bdfcd91)

Si ho aggiornato e questo ok
Ho anche provato il suggerimento che mi hai detto sopra e mi pare funzionare

**Comment by francescapenso** [comment]
> > 14.0 supermege
> > Importare una fattura in
> > Errore
> 
> Hai modo di provare:
> 
> ```diff
> index 9c6b06459..7702b3718 100644
> --- a/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +++ b/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> @@ -1169,8 +1169,10 @@ class WizardImportFatturapa(models.TransientModel):
>                          "account_id": arrotondamenti_account_id,
>                          "price_unit": abs(to_round),
>                          "exclude_from_invoice_tab": True,
> -                        "tax_ids": [(6, 0, [invoice_line_tax_id])],
>                      }
> +                    if invoice_line_tax_id:
> +                        upd_vals["tax_ids"] = [(6, 0, [invoice_line_tax_id])]
> +
>                      # Valutare se in caso di importazione senza rounding sia meglio
>                      # lavorare su debito e credito invece di
>                      # mettere una tassa sul valore !!
> ```

Provato a importa correttamente la fattura.

**Comment by francescapenso** [comment]
Non del tutto. Una parte di per l'altra bisogna procedere con un merge con
la modifica suggerita da Marco

Il giorno lun 10 mag 2021 alle ore 17:04 Lorenzo Battistini <
***@***.***> ha scritto:

**Comment by TheMule71** [comment]
La modifica che ho fatto si limita a gestire il caso lato python.  Andrebbe valutato perché succede e se va gestito il problema a monte. In pratica perché dà per scontato che invoice_line_tax_id esista? Se è un errore del codice allora la fix va bene, se invece la tax_ids deve essere popolata, bisogna analizzare perché non lo è nel caso specifico...

**Comment by francescapenso** [comment]
Sto facendo delle verifiche
Il motivo potrebbe essere questa incongruenza....?
[image: image.png]
La natura 3.1 ho cercato ed è "non impo art 8 a e b"
Se il motivo è questo forse il messaggio di errore è fuorviante


Il giorno mer 12 mag 2021 alle ore 21:55 Marco Colombo <
***@***.***> ha scritto:

**Comment by TheMule71** [comment]
Non so perché ma non vedo l'immagine...

**Comment by francescapenso** [comment]
![image](https://user-images.githubusercontent.com/19937703/118150232-9c529180-b412-11eb-9366-fdcf2b4a9bc8.png)

ci riprovo se no la mando su discord

**Comment by TheMule71** [comment]
Adesso si legge
