### ISSUE TITLE
[14.0] fatturapa_out con note

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2463]
Versioni coinvolte:

- [x] #2485

Passi per riprodurre: azienda con aliquota iva base al 10% 
creare una fattura o una nc con una riga di prodotto con  aliquota al 10% e una riga di note.
Fare esporta fattura 

Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/odoo-italia/l10n-italy/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 151, in exportFatturaPA
    attach = self.saveAttachment(fatturapa, progressivo_invio)
  File "/home/odoo/src/user/odoo-italia/l10n-italy/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 52, in saveAttachment
    attach_str = fatturapa.to_xml(self.env)
  File "/home/odoo/src/user/odoo-italia/l10n-italy/l10n_it_fatturapa_out/wizard/efattura.py", line 302, in to_xml
    content = env.ref(
  File "/home/odoo/src/odoo/addons/web_editor/models/ir_ui_view.py", line 28, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1717, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/home/odoo/src/enterprise/web_studio/models/ir_qweb.py", line 44, in _render
    return super(IrQWeb, self)._render(template, values=values, **options)
  File "/home/odoo/src/user/OCA/web/web_decimal_numpad_dot/web_company_color/models/ir_qweb.py", line 79, in _render
    return super()._render(id_or_xml_id, values=values, **options)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 55, in _render
    result = super(IrQWeb, self)._render(id_or_xml_id, values=values, **context)
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 258, in _render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    raise e
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_it_fatturapa_out_account_invoice_it_FatturaPA_export_132
  File "<template>", line 12, in foreach_131
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    raise e
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_it_fatturapa_out_account_invoice_it_fattura_elettronica_body_264
  File "<template>", line 43, in foreach_241
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 338, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.addons.base.models.qweb.QWebException: tuple index out of range
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_it_fatturapa_out_account_invoice_line_it_FatturaPA_341
  File "/home/odoo/src/odoo/odoo/models.py", line 5672, in __getitem__
    return self.browse((self._ids[key],))
IndexError: tuple index out of range

Error to render compiling AST
IndexError: tuple index out of range
Template: l10n_it_fatturapa_out.account_invoice_line_it_FatturaPA
Path: /t/t
Node: <t t-set="tax_ids" t-value="line.tax_ids[0]"/>

**Comment by eLBati** [comment]
La 12 non dovrebbe soffrirne , giusto?

**Comment by francescapenso** [comment]
Ho rifatto test anche con la versione OCA del modulo e non più quella supermerge e in 14 il risultato non cambia

**Comment by francescapenso** [comment]
> La 12 non dovrebbe soffrirne , giusto?

io non ho provato in 12 m ricordo che ne avevo parlato con @TheMule71 e non mi pareva che la 12 avesse lo stesso problema mai

**Comment by eLBati** [comment]
Quindi questa si può chiudere?
