### ISSUE TITLE
Errore caricando fattura cliente

### ISSUE THREAD

**Issue by iidmitaly** [OCA/l10n-italy#2527]
## Module
l10n_it_fatturapa_in

## Describe the bug
Quando provo a importare una fattura cliente
Clienti->Fattura cliente -> Carica

mi da quest'errore:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/account/models/account_journal.py", line 619, in create_invoice_from_attachment
    invoice.with_context(no_new_invoice=True).message_post(attachment_ids=[attachment.id])
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 1829, in message_post
    record_name = record_name or self.display_name
  File "/odoo/odoo-server/odoo/fields.py", line 1021, in __get__
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/odoo/odoo-server/odoo/models.py", line 4062, in _compute_field_value
    getattr(self, field.compute)()
  File "/odoo/odoo-server/odoo/models.py", line 1728, in _compute_display_name
    names = dict(self.name_get())
  File "/opt/odoo/addons/l10n-italy/l10n_it_fatturapa_in/models/account.py", line 251, in name_get
    result = super(AccountInvoice, self).name_get()
  File "/odoo/odoo-server/addons/account/models/account_move.py", line 2048, in name_get
    name = move._get_move_display_name(show_ref=True)
  File "/odoo/odoo-server/addons/account/models/account_move.py", line 2258, in _get_move_display_name
    draft_name += {
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'other'

## To Reproduce

Clienti->Fattura cliente -> Carica

Selezionare una fattura formato xml

**Affected versions**:
14

1.Clienti->Fattura cliente -> Carica
2.Selezionare una fattura formato xml
3.

**Expected behavior**
caricamento della fattura

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
