### ISSUE TITLE
[14.0] l10n_it_account errore nel calcolo liquidazione iva

### ISSUE THREAD

**Issue by stefano-ooops** [OCA/l10n-italy#2577]
1. Ho creato una nuova imposta (gruppo di imposte) agganciando le imposte già esistenti 
![immagine](https://user-images.githubusercontent.com/97095425/148046771-479b9a4f-9842-4c3b-b575-15659c70cb7e.png)
![immagine](https://user-images.githubusercontent.com/97095425/148047743-40d2ee6f-2c19-41f7-bf80-61654240b57d.png)
![immagine](https://user-images.githubusercontent.com/97095425/148047789-2c7e7a86-a0b9-426d-873e-645d945bb006.png)

2. Ho registrato fatture fornitori con imposta creata 
![immagine](https://user-images.githubusercontent.com/97095425/148047941-c05c39dd-7cf4-43e3-ae57-a89cf201ba7e.png)
![immagine](https://user-images.githubusercontent.com/97095425/148047995-625db8f8-21e2-41a4-9015-18b0b56717c1.png)

3. Andando a calcolare la liquidazione periodica da errore nel momento in cui aggiungo il periodo
![immagine](https://user-images.githubusercontent.com/97095425/148048300-2b0a6166-0371-4ad2-8296-ffd935197baa.png)
![immagine](https://user-images.githubusercontent.com/97095425/148048364-ec94df17-f54f-4648-b892-07776778c957.png)

Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/.repo_requirements/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1396, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1384, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/l10n-italy/setup/account_vat_period_end_statement/odoo/addons/account_vat_period_end_statement/wizard/add_period.py", line 33, in add_period
    statement.compute_amounts()
  File "/home/odoo/build/OCA/l10n-italy/setup/l10n_it_vat_statement_split_payment/odoo/addons/l10n_it_vat_statement_split_payment/models/statement.py", line 17, in compute_amounts
    res = super().compute_amounts()
  File "/home/odoo/build/OCA/l10n-italy/setup/account_vat_period_end_statement/odoo/addons/account_vat_period_end_statement/models/account.py", line 655, in compute_amounts
    credit_line_ids, debit_line_ids = self._get_credit_debit_lines(statement)
  File "/home/odoo/build/OCA/l10n-italy/setup/account_vat_period_end_statement/odoo/addons/account_vat_period_end_statement/models/account.py", line 754, in _get_credit_debit_lines
    self._set_credit_lines(tax, credit_line_ids, statement)
  File "/home/odoo/build/OCA/l10n-italy/setup/account_vat_period_end_statement/odoo/addons/account_vat_period_end_statement/models/account.py", line 714, in _set_credit_lines
    "registry_type": "supplier",
  File "/home/odoo/build/OCA/l10n-italy/setup/l10n_it_account/odoo/addons/l10n_it_account/models/account_tax.py", line 196, in _compute_totals_tax
    if child.account_id:
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'account.tax' object has no attribute 'account_id'

**Comment by stefano-ooops** [comment]
@tafaRU si la #2931 risolve inserendo direttamente le percentuali di detrazione nell'imposta

**Comment by tafaRU** [comment]
grazie del test e della review @stefano-ooops
