### ISSUE TITLE
[12.0][l10n_it_fatturapa_in] errore su _compute_xml_data

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#2699]
## Module
`l10n_it_fatturapa_in`

## Describe the bug
All'aggiornamento del modulo si verifica un errore sul calcolo del campo `is_self_invoice`, se è presente un file xml con xmlns: 

`xmlns:pfx6: 'http://www.tibco.com/ns/no_namespace_schema_location/NBS_FAT_WRITER/Schemas/XSD riepilogo_fattura_ordinaria_v1.2_mod.xsd'`

Errore completo:

```
2022-03-06 03:08:37,596 23001 WARNING odoo.addons.l10n_it_fatturapa.bindings.fatturapa: lxml was unable to parse xml: xmlns:pfx6: 'http://www.tibco.com/ns/no_namespace_schema_location/NBS_FAT_WRITER/Schemas/XSD riepilogo_fattura_ordinaria_v1.2_mod.xsd' is not a valid URI, line 1, column 378 (<string>, line 1)

2022-03-06 03:08:37,601 23001 ERROR  odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 803

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1064, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('fatturapa.attachment.in(803,).is_self_invoice', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/l10n-italy/l10n_it_fatturapa/bindings/fatturapa.py", line 81, in CreateFromDocument
    root = etree.fromstring(xml_string)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79003)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118334)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117014)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111258)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "<string>", line 1
lxml.etree.XMLSyntaxError: xmlns:pfx6: 'http://www.tibco.com/ns/no_namespace_schema_location/NBS_FAT_WRITER/Schemas/XSD riepilogo_fattura_ordinaria_v1.2_mod.xsd' is not a valid URI, line 1, column 378

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 321, in init_models
    models[0].recompute()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5322, in recompute
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5322, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5169, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1068, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1157, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1135, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1126, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo/custom/l10n-italy/l10n_it_fatturapa_in/models/attachment.py", line 92, in _compute_xml_data
    fatt = wiz_obj.get_invoice_obj(att)
  File "/opt/odoo/custom/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1551, in get_invoice_obj
    return fatturapa.CreateFromDocument(xml_string)
  File "/opt/odoo/custom/l10n-italy/l10n_it_fatturapa/bindings/fatturapa.py", line 84, in CreateFromDocument
    return _CreateFromDocument(xml_string)
  File "/opt/odoo/custom/l10n-italy/l10n_it_fatturapa/bindings/binding.py", line 74, in CreateFromDocument
    saxer.parse(io.BytesIO(xmld))
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.6/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: syntax error
2022-03-06 03:08:37,611 23001 ERROR click_odoo.env_options: exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 803

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1064, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('fatturapa.attachment.in(803,).is_self_invoice', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/l10n-italy/l10n_it_fatturapa/bindings/fatturapa.py", line 81, in CreateFromDocument
    root = etree.fromstring(xml_string)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79003)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118334)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117014)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111258)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "<string>", line 1
lxml.etree.XMLSyntaxError: xmlns:pfx6: 'http://www.tibco.com/ns/no_namespace_schema_location/NBS_FAT_WRITER/Schemas/XSD riepilogo_fattura_ordinaria_v1.2_mod.xsd' is not a valid URI, line 1, column 378

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/.local/lib/python3.6/site-packages/click_odoo/env_options.py", line 211, in _invoke
    database=database, rollback=rollback, ctx=ctx
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/click_odoo_contrib/update.py", line 272, in OdooEnvironmentWithUpdate
    ignore_addons,
  File "/usr/local/lib/python3.6/dist-packages/click_odoo_contrib/update.py", line 244, in _update_db
    ignore_addons,
  File "/usr/local/lib/python3.6/dist-packages/click_odoo_contrib/update.py", line 215, in _update_db_nolock
    Registry.new(database, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 321, in init_models
    models[0].recompute()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5322, in recompute
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5322, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5169, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1068, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1157, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1135, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1126, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo/custom/l10n-italy/l10n_it_fatturapa_in/models/attachment.py", line 92, in _compute_xml_data
    fatt = wiz_obj.get_invoice_obj(att)
  File "/opt/odoo/custom/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1551, in get_invoice_obj
    return fatturapa.CreateFromDocument(xml_string)
  File "/opt/odoo/custom/l10n-italy/l10n_it_fatturapa/bindings/fatturapa.py", line 84, in CreateFromDocument
    return _CreateFromDocument(xml_string)
  File "/opt/odoo/custom/l10n-italy/l10n_it_fatturapa/bindings/binding.py", line 74, in CreateFromDocument
    saxer.parse(io.BytesIO(xmld))
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.6/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: syntax error

```

## To Reproduce
**Affected versions**:
- [x] 10.0: https://github.com/OCA/l10n-italy/pull/2905 (risolta in quanto non più supportata)
- [x] 12.0: https://github.com/OCA/l10n-italy/pull/2705 + ~~https://github.com/OCA/l10n-italy/pull/2748~~ https://github.com/OCA/l10n-italy/pull/2788
- [x] 14.0: https://github.com/OCA/l10n-italy/pull/3475
- [ ] 16.0: #3785 

1. Update module

**Comment by sergiocorato** [comment]
Il record 803 in `fatturapa.attachment.in` esiste?

**Comment by GSLabIt** [comment]
Si, esiste

<img width="813" alt="Schermata 2022-03-10 alle 15 52 24" src="https://user-images.githubusercontent.com/11652845/157687625-5fab9120-c4c9-4d58-a836-ca83e86d6d12.png">

**Comment by sergiocorato** [comment]
Vuoi caricare l'xml anonimizzato?

**Comment by GSLabIt** [comment]
La cosa strana è che importando la fattura da wizard non da il problema. Ho creato uno script di pre migrazione e sembrerebbe, finalmente, aver risolto il problema. Sostanzialmente crea il campo `is_self_invoice` e lo inizializza a `False` prima dell'aggiornamento del modulo.

```
    if not openupgrade.column_exists(
        env.cr, 'fatturapa_attachment_in', "is_self_invoice"
    ):
        openupgrade.add_fields(
            env,
            [(
                "is_self_invoice",
                "fatturapa.attachment.in",
                "fatturapa_attachment_in",
                "boolean",
                False,
                "l10n_it_fatturapa_in",
            )],
        )
```

**Comment by GSLabIt** [comment]
> Vuoi caricare l'xml anonimizzato?

Verifico che il pre-migration script funzioni correttamente; nel caso non funzionasse, invio il file anonimizzato.

**Comment by sergiocorato** [comment]
Confermo l'errore, @GSLabIt puoi creare una PR?

**Comment by GSLabIt** [comment]
> Confermo l'errore, @GSLabIt puoi creare una PR?

Ok. 

Una domanda, perché fare un campo calcolato per `is_self_invoice`, e leggere il file quando arriva, piuttosto che farlo all'import?

**Comment by sergiocorato** [comment]
> > Confermo l'errore, @GSLabIt puoi creare una PR?
> 
> Ok.
> 
> Una domanda, perché fare un campo calcolato per `is_self_invoice`, e leggere il file quando arriva, piuttosto che farlo all'import?

Non ho seguito la cosa, credo sia stato perchè si vuole sapere già dall'inizio quali sono le autofatture, andandole poi ad escludere dalle fatture importabili appunto.

**Comment by TheMule71** [comment]
Per me il baco è altrove.

La _compute_xml_data() dovrebbe:
1. gestire gli errori di parsing correttamente
2. attivare il wizard di import FE solo sugli attachment che sono effettivamente FE

A me pare che in questo caso ci sia un errore di parsing.
`2022-03-06 03:08:37,596 23001 WARNING odoo.addons.l10n_it_fatturapa.bindings.fatturapa: lxml was unable to parse xml: xmlns:pfx6: 'http://www.tibco.com/ns/no_namespace_schema_location/NBS_FAT_WRITER/Schemas/XSD riepilogo_fattura_ordinaria_v1.2_mod.xsd' is not a valid URI, line 1, column 378 (<string>, line 1)`
 dovuto allo spazio nell'url credo.

Comunque, cos'è quel allegato? Che XML è, per curiosità?  Ha qualcosa a che fare con #902?

> Una domanda, perché fare un campo calcolato per is_self_invoice, e leggere il file quando arriva, piuttosto che farlo all'import?

L'idea era quella non fare l'import. Almeno all'epoca: #2552

**Comment by eLBati** [comment]
Ho fatto quindi https://github.com/OCA/l10n-italy/pull/2748

**Comment by matteoopenf** [comment]
Buon Pomeriggio,

ho aperto questa piccola patch https://github.com/OCA/l10n-italy/pull/2858 riguardo la pr di questa issue, la pr così com'è blocca la CI CD di odoo.sh perchè vedendo l'errore di parsing, viene letto error e si blocca, ci potrebbero essere fatture che hanno errori di vario tipo, inoltre ci sono le fatture elettroniche semplificate che non sono ancora supportate. 
Quindi scattando il metodo da errore e si blocca la CI/CD di odoo.sh.
Quindi  per evitare il blocco ho pensato di cambiare .error a .info, l'errore di parsing è salvaguardato perchè salvato in un campo apposito e non cambio la logica attualmente inserita

**Comment by Borruso** [comment]
allego PR per risoluzione errore
https://github.com/OCA/l10n-italy/pull/2940

**Comment by francesco-ooops** [comment]
@SirAionTech cambio la domanda allora: #2705 è già presente per la 14 (ed eventualmente la 16)?

**Comment by SirAionTech** [comment]
> @SirAionTech cambio la domanda allora: #2705 è già presente per la 14?

Da quello che vedo nella descrizione della issue, #2705 + #2788 dovrebbero essere state portate entrambe alla `14.0` da #3475, però in effetti nel titolo della #3475 si parla solo della #2788 quindi forse la #2705 potrebbe mancare.

>  (ed eventualmente la 16)

In descrizione non si parla della `16.0`: se queste modifiche ci sono o meno dipende da quando sono state mergiate e da quando è stata fatta la migrazione.

---
In entrambi i casi per sapere con precisione cosa c'è e cosa non c'è serve guardare i commit o ancora meglio il codice.
Oppure, a livello funzionale, si può provare a riprodurre il problema descritto.
