### ISSUE TITLE
Errore Canale SDI dopo ultimo aggiornamento fatture elettroniche in ingresso 

### ISSUE THREAD

**Issue by wowstore87** [OCA/l10n-italy#2712]
Prima dell'aggiornamento non c'èrano errori e il modulo funzionava, aggiornato all ultima versione ho questo errore quando vado a controllare le e-fatture in ingresso

Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 905, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 927, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/opt/odoo12/odoo/odoo/models.py", line 4615, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/opt/odoo12/odoo/odoo/models.py", line 1581, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo12/odoo/odoo/models.py", line 4165, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/opt/odoo12/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column fatturapa_attachment_in.is_self_invoice does not exist
LINE 1: ...rapa_attachment_in"."registered" = false )  AND  ("fatturapa...
                                                             ^

**Comment by matteoopenf** [comment]
Ma hai fatto un update all, prima di riavviare il servizio?

**Comment by wowstore87** [comment]
Avevo verificato se ci fossero aggiornamenti disponibili, avevo da aggiornare uno due moduli legati a fattura pa in, ed ho scaricato il modulo, sovrascritto la cartella con il modulo nuovo e fatto aggiorna, e come sempre andato tutto liscio e funziona,

stessa procedura per il modulo l10n_it_sdi_channel ma all'utilizzo mi da quell erorre, e si ho riavviato odoo completamente, potrei provare tornando alla versione precedente in caso

**Comment by matteoopenf** [comment]
Dovresti vedere nei log se scatta la migrazione altrimenti conviene che commenti la issue che ha portato a questo

**Comment by tafaRU** [comment]
Vedi anche https://github.com/OCA/l10n-italy/issues/2716#issuecomment-1076058595

**Comment by tafaRU** [comment]
Chiudo in virtù di https://github.com/OCA/l10n-italy/issues/2716#issuecomment-1078937086
