### ISSUE TITLE
l10n_it_fatturapa_in psycopg2.ProgrammingError: column fatturapa_attachment_in.is_self_invoice does not exist

### ISSUE THREAD

**Issue by wowstore87** [OCA/l10n-italy#2716]
Dopo aggiornamento del modulo l10n_it_fatturapa_in 

in ogni fattura in ingresso, quando provo ad aprirla mi ritorna questo errore,

stessa cosa ce apro la sezione e-fatture in ingresso, 
prima dell aggiornamento del modulo non avevo problemi

Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 497

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/fields.py", line 1032, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo12/odoo/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('fatturapa.attachment.in(497,).display_name', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 497

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/fields.py", line 1032, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo12/odoo/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('fatturapa.attachment.in(497,).name', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 497

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/fields.py", line 1032, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo12/odoo/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('fatturapa.attachment.in(497,).ir_attachment_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 963, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/models.py", line 2835, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/opt/odoo12/odoo/odoo/fields.py", line 2231, in convert_to_read
    return (value.id, value.sudo().display_name)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1036, in __get__
    self.determine_value(record)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1149, in determine_value
    self.compute_value(recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1103, in compute_value
    self._compute_value(records)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1094, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo12/odoo/odoo/models.py", line 1590, in _compute_display_name
    names = dict(self.name_get())
  File "/opt/odoo12/odoo/odoo/models.py", line 1609, in name_get
    result.append((record.id, convert(record[name], record)))
  File "/opt/odoo12/odoo/odoo/models.py", line 5167, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo12/odoo/odoo/fields.py", line 1036, in __get__
    self.determine_value(record)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1149, in determine_value
    self.compute_value(recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1103, in compute_value
    self._compute_value(records)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1096, in _compute_value
    self.compute(records)
  File "/opt/odoo12/odoo/odoo/fields.py", line 646, in _compute_related
    values = [first(value[name]) for value in values]
  File "/opt/odoo12/odoo/odoo/fields.py", line 646, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/opt/odoo12/odoo/odoo/models.py", line 5167, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo12/odoo/odoo/fields.py", line 1036, in __get__
    self.determine_value(record)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1139, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo12/odoo/odoo/models.py", line 2880, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/opt/odoo12/odoo/odoo/models.py", line 2818, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo12/odoo/odoo/models.py", line 2945, in _read_from_database
    cr.execute(query_str, params)
  File "/opt/odoo12/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column fatturapa_attachment_in.is_self_invoice does not exist
LINE 1: ...urapa_attachment_in"."registered" as "registered","fatturapa...
                                                             ^

**Comment by tafaRU** [comment]
Il campo `fatturapa.in.attachment.is_self_invoice` è stato aggiunto con https://github.com/OCA/l10n-italy/pull/2666.
Ciò comporta che oltre ad aggiornare il codice di `l10n_it_fatturapa_in` devi anche aggiornare il modulo stesso in modo che la nuova colonna venga creata.

**Comment by tafaRU** [comment]
Chiudo perché duplicato di https://github.com/OCA/l10n-italy/issues/2712

**Comment by mktsrl** [comment]
Mi aggangio a questa issue per fornire qualche ulteriore indicazione derivata dalla nostra esperienza dopo aver eseguito l'aggiornamento del modulo `l10n_it_fatturapa_in` e introdotto il campo "`is_self_invoice`".
Nel nostro caso alcune istanze sono risultate regolarmente funzionanti dopo l'aggiornamento, mentre altre istanze che abbiamo collegato con nostri servizi esterni dai quali vengono scaricate in Odoo le fatture elettroniche, viene presentato un errore quando si tenta di aprire il dettaglio della fattura (dalla lista fatture fornitore, aprendo il dettaglio, compare l'errore).
In particolare Odoo segnala: `"psycopg2.errors.UndefinedColumn: column fatturapa_attachment_in.is_self_invoice does not exist"`
 
Abbiamo verificato che il campo` fatturapa_attachment_in.is_self_invoice` effettivamente non esiste a DB e questo dipende dal fatto che l'aggiornamento di `l10n_it_fatturapa_in` va in errore su quella particolare istanza, bloccandosi senza aggiungere quindi il nuovo campo. L'errore riportato nei log d'aggiornamento è il seguente: `odoo.exceptions.CacheMiss: ('fatturapa.attachment.in(510,).is_self_invoice', None)`
 
A questo punto, per le sole istanze coinvolte nel problema abbiamo adottato le seguenti soluzioni che, al momento, hanno risolto il problema:

1. ricreare il campo a mano nel DB

2. sul campo is_self_invoice togliere temporaneamente il riferimento alla `compute="_compute_xml_data"` e alla` store=True` impostandolo non obbligatorio; eseguire l'aggiornamento del modulo, per poi ripristinare il campo come era originariamente (con la _compute e lo store) ed eseguendo di nuovo l'aggiornamento 

 
Mi chiedo a questo punto se il problema riscontrato sia relativo all’algoritmo del metodo `_compute_xml_data `oppure se non dipenda solamente dal fatto che il campo essendo impostato con "store=True" vada quindi in errore su quelle istanze Odoo per le quali esistono già dei record (`fatturapa_attachment_in`) privi però di cache sul campo `is_self_invoice `(sarebbe lecito pensarlo dal momento che l’errore è di tipo `exceptions.CacheMiss`).

**Comment by mktsrl** [comment]
Ecco in allegato la fattura anonimizzata, ma suggerisco di verificare che il problema non sia legato al campo di tipo “store=True”.
Luca

**Comment by mktsrl** [comment]
Ecco in allegato la fattura anonimizzata, ma suggerisco di verificare che il problema non sia legato al campo di tipo “store=True”.

[ZGEXQROO37831 anonimizzata.zip](https://github.com/OCA/l10n-italy/files/8339489/ZGEXQROO37831.anonimizzata.zip)

**Comment by wowstore87** [comment]
Grazie!!!

con aggiornamento l10n_it_fatturapa_in-12.0.2.9.1 sembra essere stato risolto!!

**Comment by tafaRU** [comment]
@wowstore87 pertanto si può chiudere anche https://github.com/OCA/l10n-italy/issues/2712 ?

**Comment by wowstore87** [comment]
Si grazie!

Inviato da Yahoo Mail su Android 
 
  Il ven, 25 mar, 2022 alle 12:40, Alex ***@***.***> ha scritto:   


@wowstore87 pertanto si può chiudere anche #2712 ?

**Comment by mktsrl** [comment]
> l10n_it_fatturapa_in-12.0.2.9.1

In realtà, la mia segnalazione derivava proprio da una verifica sulla versione 12.0.2.9.1. Anche con questa versione infatti, se a db sono presenti record fatturapa_attachment_in privi però di cache sul campo is_self_invoice si verifica il problema.

**Comment by matteoopenf** [comment]
Anche io ho avuto problemi con vecchie fatture del 2018 mettendo questa ultima versione 

Matteo Mircoli
Developer | ***@***.*** 

> Il giorno 30 mar 2022, alle ore 18:04, MKT Srl ***@***.***> ha scritto:
> 
> ﻿
> l10n_it_fatturapa_in-12.0.2.9.1
> 
> In realtà, la mia segnalazione derivava proprio da una verifica sulla versione 12.0.2.9.1. Anche con questa versione infatti, se a db sono presenti record fatturapa_attachment_in privi però di cache sul campo is_self_invoice si verifica il problema.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.

-- 

_
Openforce Srls Unipersonale *| www.openforce.it 
<http://www.openforce.it/> |*__ 02 21119472 | Via Tiziano,32 20145 Milano_

**Comment by tafaRU** [comment]
@mktsrl apri pure una nuova issue se lo ritieni opportuno.

**Comment by TheMule71** [comment]
Segnalo https://github.com/OCA/l10n-italy/issues/2699#issuecomment-1065867986

Invece di evitare di chiamare la `_compute_xml_data()`, andrebbe fixata.  Da quello che ho capito, probabilmente si può intervenire in https://github.com/OCA/l10n-italy/blob/15efbccb5a29fa3ec270c155d26161a1a1511e2d/l10n_it_fatturapa_in/wizard/efattura.py#L128

perché è errore nel file, e il parser non la prende bene.

**Comment by francesco-ooops** [comment]
Chiudo perchè la issue originale è stata risolta https://github.com/OCA/l10n-italy/issues/2716#issuecomment-1078902750
