### ISSUE TITLE
14.0 fattura fornitore in reverse charge modifica post conferma

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2738]
Fattura fornitore in regime di RC confermata con relativa autofattura generata.
Aprire e rimettere in bozza la fattura. Effettuare una modifica (es. il numero del conto nei movimenti contabili). 
A questo punto sia la ft fornitore che quella generata da RC sono in bozza.
Confermare la fattura fornitore originale. 

SI genera un errore 

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 357, in checked_call
    self._cr.precommit.run()
  File "/home/odoo/src/odoo/odoo/tools/misc.py", line 1152, in run
    func()
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 550, in _finalize_tracking
    tracking = records.with_context(context).message_track(fnames, initial_values)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 629, in message_track
    record.message_post(subtype_id=subtype.id, tracking_value_ids=tracking_value_ids)
  File "/home/odoo/src/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
    message = super(MailThread, self).message_post(**kwargs)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 1832, in message_post
    record_name = record_name or self.display_name
  File "/home/odoo/src/odoo/odoo/fields.py", line 1021, in __get__
    self.compute_value(recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/addons/base_automation/models/base_automation.py", line 363, in _compute_field_value
    return _compute_field_value.origin(self, field)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/odoo/models.py", line 4069, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/odoo/odoo/models.py", line 1728, in _compute_display_name
    names = dict(self.name_get())
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_fatturapa_in/models/account.py", line 251, in name_get
    result = super(AccountInvoice, self).name_get()
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 2058, in name_get
    name = move._get_move_display_name(show_ref=True)
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 2281, in _get_move_display_name
    return (draft_name or self.name) + (show_ref and self.ref and ' (%s%s)' % (self.ref[:50], '...' if len(self.ref) > 50 else '') or '')
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

**Comment by TheMule71** [comment]
Dovrebbe essere sistemata con la #2833

**Comment by francesco-ooops** [comment]
risolta in #2873, se così non fosse puoi riaprire
