### ISSUE TITLE
l10n_it_reverse_charge Impossibile confermare fattura

### ISSUE THREAD

**Issue by AlessandroSkab** [OCA/l10n-italy#2743]
## Module
l10n_it_reverse_charge

## Describe the bug
Quando provo a confermare una fattura per un fornitore Reverse Charge mi viene fuori un errore.

## To Reproduce
**Affected versions**:
14.0 Odoo Enterprise

1. Creare una fattura selezionando un cliente che ha una posizione fiscale agganciata ad un Tipo RC Intra-EU (Self-invoice) 
2. Aggiungere un qualsiasi prodotto alla fattura e verificare che il flag RC all'interno della riga prodotto sia True.
3. Confermare fattura

**Expected behavior**
La fattura viene confermata

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

ERRORE:

Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/ABC-Strategie-GitHub/abc_contabilita_italiana/OCA/l10n-italy/l10n_it_fatturapa_in/models/account.py", line 75, in action_post
    return super().action_post()
  File "/home/odoo/src/user/ABC-Strategie-GitHub/abc_contabilita_italiana/OCA/l10n-italy/l10n_it_ricevute_bancarie/models/account.py", line 152, in action_post
    super(AccountMove, self).action_post()
  File "/home/odoo/src/user/ABC-Strategie-GitHub/abc_contabilita_italiana/OCA/l10n-italy/l10n_it_withholding_tax/models/account.py", line 433, in action_post
    res = super().action_post()
  File "/home/odoo/src/user/ABC-Strategie-GitHub/abc_contabilita_italiana/OCA/l10n-italy/l10n_it_intrastat/models/account.py", line 278, in action_post
    super().action_post()
  File "/home/odoo/src/user/ABC-Strategie-GitHub/abc_contabilita_italiana/OCA/l10n-italy/l10n_it_declaration_of_intent/models/account_move.py", line 81, in action_post
    res = super().action_post()
  File "/home/odoo/src/odoo/addons/sale/models/account_move.py", line 14, in action_post
    res = super(AccountMove, self).action_post()
  File "/home/odoo/src/user/ABC-Strategie-GitHub/abc_contabilita_italiana/OCA/l10n-italy/l10n_it_reverse_charge/models/account_move.py", line 319, in action_post
    invoice.generate_self_invoice()
  File "/home/odoo/src/user/ABC-Strategie-GitHub/abc_contabilita_italiana/OCA/l10n-italy/l10n_it_reverse_charge/models/account_move.py", line 251, in generate_self_invoice
    inv_vals = self.rc_inv_vals(rc_partner, rc_type, rc_invoice_lines, rc_currency)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: rc_inv_vals() missing 1 required positional argument: 'currency'

**Comment by TheMule71** [comment]
Ciao,
per caso c'è un modulo locale che fa l'override di `rc_inv_vals()` con un parametro in più?

**Comment by AlessandroSkab** [comment]
> Ciao, per caso c'è un modulo locale che fa l'override di `rc_inv_vals()` con un parametro in più?
@TheMule71 
Ciao, 
avevo installato il modulo l10n_it_vat_settlement_date pur essendo della 12.0 per la 14.0. Nella funzione rc_inv_vals() all'interno di account_invoice.py veniva passato un argomento in più, il quale creava problemi sul reverse. Togliendo "account" dalla lista degli argomenti passati in rc_inv_vals() funziona.

**Comment by dcorio** [comment]
Ciao @AlessandroSkab quindi questo problema riguarda il modulo l10n_it_vat_settlement_date non ancora portato alla versione 14?

**Comment by francesco-ooops** [comment]
@AlessandroSkab se si dovesse ripetere riapri pure, grazie!
