### ISSUE TITLE
14 l10n_it_fatturapa_out_wt 

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#2887]
## Module
l10n_it_fatturapa_out

## Describe the bug
quando si esporta una fattura si ottiene:
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.addons.base.models.qweb.QWebException: 'NoneType' object has no attribute 'amount_currency'
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_it_fatturapa_out_account_invoice_it_fattura_elettronica_body_575
  File "<template>", line 1, in foreach_569
AttributeError: 'NoneType' object has no attribute 'amount_currency'

Error to render compiling AST
AttributeError: 'NoneType' object has no attribute 'amount_currency'
Template: l10n_it_fatturapa_out.account_invoice_it_fattura_elettronica_body
Path: /t/FatturaElettronicaBody/DatiPagamento/t/DettaglioPagamento/ImportoPagamento[1]
Node: <ImportoPagamento t-esc="format_numbers_two(wt_hack_rate * (move_line.amount_currency or move_line.debit or 0.0))"/>

## To Reproduce
step:
1 Creazione di una fattura in uscita, validarla
2 tentare l'esportazione della fattura

**Expected behavior**
esportazione della fattura

**Additional context**
[Add any other context about the problem here. (e.g. OS, Python version, ...)](https://github.com/OCA/l10n-italy/pull/2787  ) il campo amount_currency è stato introdotto da questa pr

**Comment by matteoopenf** [comment]
chiudo colpa mia usavo la vecchia versione del mega merge di l10n_it_fatturapa_out_wt usando l'ultima si risolve
