### ISSUE TITLE
Errore importazione Fattura Passiva con ImponibileImporto = 0 in DatiRiepilogo

### ISSUE THREAD

**Issue by maurobraggio** [OCA/l10n-italy#2930]
## Module
[l10n_it_fatturapa_in](https://github.com/OCA/l10n-italy/tree/14.0/l10n_it_fatturapa_in)

## Describe the bug
Quando si tenta di importare un file xml passivo e questo ha un Imponibile Importo uguale a zero, non viene creata la fattura passiva

## To Reproduce
1. Importare il file xml, [test.txt](https://github.com/OCA/l10n-italy/files/9533944/test.txt)
2. selezionare il file importato
3. Azione -> Importa Fattura elettronica

**Expected behavior**
Creazione della fattura passiva

**Additional context**
```
Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1761, in importFatturaPA
    invoice = self.invoiceCreate(
  File "/usr/lib/python3/dist-packages/odoo/addons/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1099, in invoiceCreate
    invoice._recompute_dynamic_lines()
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 1125, in _recompute_dynamic_lines
    invoice._recompute_tax_lines(tax_rep_lines_to_recompute=delta_tax_rep_lines)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: _recompute_tax_lines() got an unexpected keyword argument 'tax_rep_lines_to_recompute'
```

**Comment by tafaRU** [comment]
Ho provato ad importare il file che hai allegato sull’ultima istanza di runboat disponbile: http://oca-l10n-italy-14-0-c9d568c3eb0c.runboat.odoo-community.org

Non riesco però a riprodurre l'errore che segnali, vengo bloccato prima:
![image](https://user-images.githubusercontent.com/3512779/189329541-2e901f8e-cde0-4af5-bee3-63310bab852f.png)
Puoi verificare il contenuto del file ed eventualmente correggerlo?

**Comment by TheMule71** [comment]
![image](https://user-images.githubusercontent.com/915043/191936658-f7ccf61e-7d69-43e1-9e24-07ea90359efa.png)

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
