### ISSUE TITLE
Errore in esportazione autofattura

### ISSUE THREAD

**Issue by esafocus** [OCA/l10n-italy#2974]
## 14.0 
10n_it_fatturapa_out_rc

## Describe the bug
Quando esporto una autofattura elettronica va in errore

## To Reproduce
**Affected versions**:

1. Configurare un tipo di reverse charge con autofattura passiva aggiuntiva
2. Creare una fattura fornitore
3. Su autofatture vendita esportare la fattura elettronica

**Expected behavior**
Esportare correttamente la fattura elettronica

**Additional context**
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo14/odoo-custom-addons/oca/l10n-italy/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 161, in exportFatturaPA
    partner, invoice_ids, context=context_partner
  File "/opt/odoo14/odoo-custom-addons/oca/l10n-italy/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 138, in exportInvoiceXML
    invoice_ids.preventive_checks()
  File "/opt/odoo14/odoo-custom-addons/oca/l10n-italy/l10n_it_fatturapa_out_rc/models/account_move.py", line 76, in preventive_checks
    rc_suppliers = invoices._get_original_suppliers()
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'account.move' object has no attribute '_get_original_suppliers'

**Comment by TheMule71** [comment]
https://github.com/OCA/l10n-italy/blob/29dbd9fdb507cdcbecf64e301251791291222e9b/l10n_it_fatturapa_out_rc/models/account_move.py#L73-L79

la chiamata alla funzione `_get_original_suppliers` non c'è.

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
