### ISSUE TITLE
[14.0][l10n_it_fatturapa_in] Posizione Fisciale

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#3013]
## Module
l10n_it_fatturapa_in

## Describe the bug
Importando una fattura di un cliente che ha impostata la posizione fiscale ottengo:
File "/home/odoo/src/user/b_OCA/l10n-italy/l10n_it_intrastat/models/account.py", line 304, in create

    self.env["account.fiscal.position"]

  File "/home/odoo/src/odoo/odoo/fields.py", line 998, in __get__

    recs._fetch_field(self)

  File "/home/odoo/src/odoo/odoo/models.py", line 3071, in _fetch_field

    self._read(fnames)

  File "/home/odoo/src/odoo/odoo/models.py", line 3138, in _read

    cr.execute(query_str, params + [sub_ids])

  File "<decorator-gen-3>", line 2, in execute

  File "/home/odoo/src/odoo/odoo/sql_db.py", line 101, in check

    return f(self, *args, **kwargs)

  File "/home/odoo/src/odoo/odoo/sql_db.py", line 300, in execute

    res = self._obj.execute(query, params)

  File "/usr/lib/python3/dist-packages/psycopg2/extensions.py", line 120, in getquoted

    pobjs = [adapt(o) for o in self._seq]

  File "/usr/lib/python3/dist-packages/psycopg2/extensions.py", line 120, in <listcomp>

    pobjs = [adapt(o) for o in self._seq]

Exception

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):

  File "/home/odoo/src/odoo/odoo/http.py", line 639, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/home/odoo/src/odoo/odoo/http.py", line 315, in _handle_exception

    raise exception.with_traceback(None) from new_cause

psycopg2.ProgrammingError: can't adapt type 'account.fiscal.position'

## To Reproduce
**Affected versions**:

- 14. 0  https://github.com/OCA/l10n-italy/pull/3014

1. importare una fattura di un contatto che ha la posizione fiscale impostata
2. nel form cliccare importa
3. errore:
4. File "/home/odoo/src/user/b_OCA/l10n-italy/l10n_it_intrastat/models/account.py", line 304, in create

    self.env["account.fiscal.position"]

  File "/home/odoo/src/odoo/odoo/fields.py", line 998, in __get__

    recs._fetch_field(self)

  File "/home/odoo/src/odoo/odoo/models.py", line 3071, in _fetch_field

    self._read(fnames)

  File "/home/odoo/src/odoo/odoo/models.py", line 3138, in _read

    cr.execute(query_str, params + [sub_ids])

  File "<decorator-gen-3>", line 2, in execute

  File "/home/odoo/src/odoo/odoo/sql_db.py", line 101, in check

    return f(self, *args, **kwargs)

  File "/home/odoo/src/odoo/odoo/sql_db.py", line 300, in execute

    res = self._obj.execute(query, params)

  File "/usr/lib/python3/dist-packages/psycopg2/extensions.py", line 120, in getquoted

    pobjs = [adapt(o) for o in self._seq]

  File "/usr/lib/python3/dist-packages/psycopg2/extensions.py", line 120, in <listcomp>

    pobjs = [adapt(o) for o in self._seq]

Exception

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):

  File "/home/odoo/src/odoo/odoo/http.py", line 639, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/home/odoo/src/odoo/odoo/http.py", line 315, in _handle_exception

    raise exception.with_traceback(None) from new_cause

psycopg2.ProgrammingError: can't adapt type 'account.fiscal.position'

**Expected behavior**
Non ottenere l'errore

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by matteoopenf** [comment]
chiudo che la pr relativa è stata mergiata oggi
