### ISSUE TITLE
Aggiornando da versione 12.0.2.3.0  a 12.0.3.0.3 ricevo questo errore: alueError: Modello non trovato: fatturapa.attachment  Contesto errore: Vista `Form view for SdI file`

### ISSUE THREAD

**Issue by wowstore87** [OCA/l10n-italy#3072]
Come descritto nel titolo sto aggiornando come si vede da foto e ricevo questo errore:

![image](https://user-images.githubusercontent.com/102078482/204153372-5ca5d084-d808-4a5e-95bb-a2bbdf30ea4f.png)

Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/models.py", line 1128, in _validate_fields
    check(self)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 1105, in postprocess_and_fields
    self.raise_view_error(_('Model not found: %(model)s') % dict(model=model), view_id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 568, in raise_view_error
    raise ValueError(message)
ValueError: Modello non trovato: fatturapa.attachment

Contesto errore:
Vista `Form view for SdI file`
[view_id: 1420, xml_id: n/d, model: fatturapa.attachment, parent_id: n/d]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/odoo/models.py", line 3908, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/odoo/odoo/models.py", line 3822, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/models.py", line 3639, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1168, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 445, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/odoo/models.py", line 3364, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3500, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Errore nella validazione del vincolo\n\nModello non trovato: fatturapa.attachment\n\nContesto errore:\nVista `Form view for SdI file`\n[view_id: 1420, xml_id: n/d, model: fatturapa.attachment, parent_id: n/d]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 963, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-67>", line 2, in button_immediate_upgrade
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 627, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/odoo/models.py", line 3908, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/odoo/odoo/models.py", line 3822, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/models.py", line 3639, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1168, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 445, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/odoo/models.py", line 3364, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3500, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 1132, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Errore nella validazione del vincolo

Modello non trovato: fatturapa.attachment

Contesto errore:
Vista `Form view for SdI file`
[view_id: 1420, xml_id: n/d, model: fatturapa.attachment, parent_id: n/d]
None" while parsing /opt/odoo12/odoo-custom-addons/l10n_it_fatturapa/views/fatturapa_attachment_views.xml:7, near
<record id="fatturapa_attachment_view_form" model="ir.ui.view">
        <field name="name">Form view for SdI file</field>
        <field name="model">fatturapa.attachment</field>
        <field name="arch" type="xml">
            <form string="SdI file">
                <sheet>
                    <group>
                        <group name="preview">
                            <field name="id" invisible="1"/>
                            <label for="datas"/>
                            <div>
                                <div>
                                    <field name="datas" filename="datas_fname"/>
                                </div>
                                <div>
                                    <button type="object" name="ftpa_preview" string="Show preview" style="margin-bottom:10px;" attrs="{'invisible': [('id', '=', False)]}"/>
                                </div>
                            </div>
                            <field name="datas_fname" invisible="True"/>
                            <field name="name" invisible="True"/>
                        </group>
                    </group>
                    <notebook>
                        <page name="history" string="History">
                            <label for="create_uid" string="Created by"/>
                            <div name="creation_div">
                                <field name="create_uid" readonly="1" class="oe_inline"/> on
                                <field name="create_date" readonly="1" class="oe_inline"/>
                            </div>
                        </page>
                    </notebook>
                </sheet>
                <div class="oe_chatter">
                    <field name="message_follower_ids" widget="mail_followers"/>
                    <field name="message_ids" widget="mail_thread"/>
                </div>
            </form>
        </field>
    </record>

**Comment by matteoopenf** [comment]
Hai già provato un update all?

**Comment by wowstore87** [comment]
No update all non l'ho mai utilizzato, ma si esegue da riga di comando?

**Comment by matteoopenf** [comment]
> No update all non l'ho mai utilizzato, ma si esegue da riga di comando? 

Si

**Comment by matteoopenf** [comment]
https://www.odoo.com/it_IT/forum/assistenza-1/is-there-any-way-upgrade-all-installed-modules-101096

Poi dipende dall'installazione, ma ecco un aiuto

**Comment by wowstore87** [comment]
Spero di arrivarne a capo, mi mancavano qualche dipendenza fra cui psycopg2 e dopo averle installate quando chiamo lúpdate all ora ricevo questo errore grave, qualche consiglio su cosa ho fatto?

psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "odoo12"

**Comment by wowstore87** [comment]
Per questo mi autorispondo 

bisogna modificare il file di configurazione pg_hba.conf 

come suggerito qua

https://stackoverflow.com/questions/18664074/getting-error-peer-authentication-failed-for-user-postgres-when-trying-to-ge

peró sto comunque avendo altri problemi

**Comment by wowstore87** [comment]
Ad ora  

questo é l'errore che ricevo

File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by wowstore87** [comment]
Fatto tutto quello il necessario, ora lanciando update all, rimane un trattino e non succede niente,

nel file lgo trovo questo come ultimo messaggio:


  File "/opt/odoo12/odoo/odoo/models.py", line 3419, in _write
    single_lang = len(self.env['res.lang'].get_installed()) <= 1
  File "/opt/odoo12/odoo/odoo/api.py", line 831, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'res.lang' - - -

**Comment by wowstore87** [comment]
ho ripristinato i moduli vecchi, e funziona. riproveró in futuro

**Comment by matteoopenf** [comment]
> ho ripristinato i moduli vecchi, e funziona. riproveró in futuro

crea un ambiente di test e provi lì l'update ecc e poi replichi in produzione
