### ISSUE TITLE
[16.0] l10n_it_withholding_tax rompe vista tree account.move

### ISSUE THREAD

**Issue by andreampiovesana** [OCA/l10n-italy#3085]
## Module
l10n_it_withholding_tax

## Describe the bug
Dopo l'installazione non sono usabili le fatture cliente, la vista tree va in errore js owl

1. installare l10n_it_withholding_tax
2. andare in fatturazione - fatture cliente

**Expected behavior**
non bloccare la fatturazione

**Additional context**
la vista errata è la seguente:
l10n_it_withholding_tax.invoice_supplier_tree_wt
<field name="amount_residual_signed" position="after">
       <field name="amount_net_pay" widget="monetary" options="{'currency_field': 'currency_id'}" sum="Net to pay"/>
</field>

**Comment by SirTakobi** [comment]
Grazie della segnalazione! Puoi riportare lo stacktrace dell'errore?

**Comment by primes2h** [comment]
@andreampiovesana 
Ho provato a seguire i passi che hai indicato su un nuovo database e funziona tutto correttamente.
Penso sia qualche problema legato al tuo ambiente di prova/sviluppo.

**Comment by SirTakobi** [comment]
Io ho trovato che viene sollevato un errore JS (ma non so se è lo stesso segnalato da @andreampiovesana): 

https://user-images.githubusercontent.com/101628000/206140367-810bca59-571f-4fc9-a51d-91f775b685e7.mp4
Lo stack trace è:
```
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://localhost:8069/web/assets/debug/web.assets_common.js:16294:35) (/web/static/lib/owl/owl.js:124)
    at owl.App.handleError (http://localhost:8069/web/assets/debug/web.assets_common.js:21844:20) (/web/static/lib/owl/owl.js:5674)
    at Fiber._render (http://localhost:8069/web/assets/debug/web.assets_common.js:17794:30) (/web/static/lib/owl/owl.js:1624)
    at Fiber.render (http://localhost:8069/web/assets/debug/web.assets_common.js:17783:18) (/web/static/lib/owl/owl.js:1613)
    at ComponentNode.initiateRender (http://localhost:8069/web/assets/debug/web.assets_common.js:18505:23) (/web/static/lib/owl/owl.js:2335)

Caused by: TypeError: Cannot read properties of undefined (reading '0')
    at get currencyId [as currencyId] (http://localhost:8069/web/assets/debug/web.assets_backend.js:32817:63) (/web/static/src/views/fields/monetary/monetary_field.js:26)
    at get formattedValue [as formattedValue] (http://localhost:8069/web/assets/debug/web.assets_backend.js:32848:30) (/web/static/src/views/fields/monetary/monetary_field.js:57)
    at MonetaryField.template (eval at compile (http://localhost:8069/web/assets/debug/web.assets_common.js:21606:16), <anonymous>:16:21) (/web/static/lib/owl/owl.js:5436)
    at Fiber._render (http://localhost:8069/web/assets/debug/web.assets_common.js:17791:38) (/web/static/lib/owl/owl.js:1621)
    at Fiber.render (http://localhost:8069/web/assets/debug/web.assets_common.js:17783:18) (/web/static/lib/owl/owl.js:1613)
    at ComponentNode.initiateRender (http://localhost:8069/web/assets/debug/web.assets_common.js:18505:23) (/web/static/lib/owl/owl.js:2335)
```

Come si vede nel video, per risolvere ho dovuto attivare un'altra valuta.

**Comment by primes2h** [comment]
> Come si vede nel video, per risolvere ho dovuto attivare un'altra valuta.

Confermo, nel mio caso erano attivate due valute (USD, EUR) e il problema non si presentava.
Disattivando quella non già in uso viene sollevata l'eccezione.

**Comment by andreampiovesana** [comment]
novità?

**Comment by odooNextev** [comment]
> novità?

Non so se nel frattempo abbiano aggiornato qualcosa nel core di Odoo, ma a noi sembra funzionare sia in locale che nel runboat anche con solo una valuta attiva: http://oca-l10n-italy-16-0-pr3103-fb152b387336.runboat.odoo-community.org/web

**Comment by tafaRU** [comment]
@odooNextev grazie della segnalazione. @andreampiovesana puoi verificare?

**Comment by andreampiovesana** [comment]
ok adesso funziona
