### ISSUE TITLE
error in export fattura elettronica

### ISSUE THREAD

**Issue by OpenValueConsulting** [OCA/l10n-italy#3152]
ho effettuato un export della fattura elettronica senza inserire un attachment ma ho indicato un attachment report (invoices).
il sistema ha un dump il cui log è riportato sotto.
grazie

File "/opt/odoo/custom-addons/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 262, in exportFatturaPA
    fatturapa, progressivo_invio = self.exportInvoiceXML(
  File "/opt/odoo/custom-addons/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 250, in exportInvoiceXML
    self.generate_attach_report(inv)
  File "/opt/odoo/custom-addons/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py", line 296, in generate_attach_report
    attachment, attachment_type = report_model._render_qweb_pdf(inv.ids)
  File "/opt/odoo/addons/account/models/ir_actions_report.py", line 49, in _render_qweb_pdf
    if self._get_report(report_ref).report_name in ('account.report_invoice_with_payments', 'account.report_invoice'):
  File "/opt/odoo/odoo/addons/base/models/ir_actions_report.py", line 505, in _get_report
    report = self.env.ref(report_ref)
  File "/opt/odoo/odoo/api.py", line 582, in ref
    res_model, res_id = self['ir.model.data']._xmlid_to_res_model_res_id(
  File "/opt/odoo/odoo/addons/base/models/ir_model.py", line 2018, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-40>", line 2, in _xmlid_lookup
  File "/opt/odoo/odoo/tools/cache.py", line 95, in lookup
    return self.method(*args, **kwargs)
  File "/opt/odoo/odoo/addons/base/models/ir_model.py", line 2006, in _xmlid_lookup
    module, name = xmlid.split('.', 1)
AttributeError: 'list' object has no attribute 'split'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://80.211.237.115:8069/web/assets/306-8fa494c/web.assets_backend.min.js:974:163)
    at XMLHttpRequest.<anonymous> (http://80.211.237.115:8069/web/assets/306-8fa494c/web.assets_backend.min.js:981:13)

**Comment by primes2h** [comment]
Non hai indicato la versione di Odoo coinvolta (andrebbe sempre fatto). 
Ipotizzo sia la 16.0 per la quale esiste già una issue aperta (#3127), di conseguenza chiudo.
