### ISSUE TITLE
error when a quotation is send by email if module "l10n_it_withholding_tax" is installed - v16.0

### ISSUE THREAD

**Issue by ser-tec** [OCA/l10n-italy#3197]
## Module
l10n_it_withholding_tax

## Describe the bug
error when a quotation is send by email if module "l10n_it_withholding_tax" is installed

## To Reproduce
**Affected versions**: 16.0

1. install l10n_it_withholding_tax
2. create a new quotation from Sales
3. Send by email

**Additional context**
Odoo v. 16.0
Ubuntu v. 20.04
l10n_it_withholding_tax v. 16.0.1.0.0

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "<685>", line 232, in template_685
  File "<685>", line 120, in template_685_content
KeyError: 'o'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/16.0/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/16.0/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/16.0/odoo/http.py", line 1613, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/16.0/odoo/http.py", line 1810, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/16.0/odoo/addons/base/models/ir_http.py", line 149, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/16.0/odoo/http.py", line 699, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/16.0/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/16.0/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/16.0/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/16.0/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/16.0/odoo/models.py", line 6495, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/16.0/odoo/models.py", line 6206, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo/16.0/addons/mail/wizard/mail_compose_message.py", line 177, in _onchange_template_id_wrapper
    values = self._onchange_template_id(self.template_id.id, self.composition_mode, self.model, self.res_id)['value']
  File "/opt/odoo/16.0/addons/mail/wizard/mail_compose_message.py", line 575, in _onchange_template_id
    values = self.generate_email_for_composer(
  File "/opt/odoo/16.0/addons/mail/wizard/mail_compose_message.py", line 705, in generate_email_for_composer
    template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields)
  File "/opt/odoo/16.0/addons/account_edi/models/mail_template.py", line 35, in generate_email
    res = super().generate_email(res_ids, fields)
  File "/opt/odoo/16.0/addons/mail/models/mail_template.py", line 286, in generate_email
    result, report_format = self.env['ir.actions.report']._render_qweb_pdf(report, [res_id])
  File "/opt/odoo/16.0/addons/account/models/ir_actions_report.py", line 57, in _render_qweb_pdf
    return super()._render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
  File "/opt/odoo/16.0/odoo/addons/base/models/ir_actions_report.py", line 797, in _render_qweb_pdf
    collected_streams = self._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/opt/odoo/16.0/addons/account_edi_ubl_cii/models/ir_actions_report.py", line 58, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/opt/odoo/16.0/addons/account_edi/models/ir_actions_report.py", line 14, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/opt/odoo/16.0/addons/account/models/ir_actions_report.py", line 20, in _render_qweb_pdf_prepare_streams
    return super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/opt/odoo/16.0/odoo/addons/base/models/ir_actions_report.py", line 698, in _render_qweb_pdf_prepare_streams
    html = self.with_context(**additional_context)._render_qweb_html(report_ref, res_ids_wo_stream, data=data)[0]
  File "/opt/odoo/16.0/odoo/addons/base/models/ir_actions_report.py", line 874, in _render_qweb_html
    return self._render_template(report.report_name, data), 'html'
  File "/opt/odoo/16.0/odoo/addons/base/models/ir_actions_report.py", line 613, in _render_template
    return view_obj._render_template(template, values).encode()
  File "/opt/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2120, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/opt/odoo/16.0/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/opt/odoo/16.0/odoo/addons/base/models/ir_qweb.py", line 579, in _render
    result = ''.join(rendering)
  File "<782>", line 80, in template_782
  File "<782>", line 62, in template_782_content
  File "<782>", line 50, in template_782_t_call_0
  File "<781>", line 1599, in template_781
  File "<781>", line 1581, in template_781_content
  File "<781>", line 1154, in template_781_t_call_0
  File "<685>", line 238, in template_685
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'o'
Template: account.document_tax_totals
Path: /t/t[3]/tr[1]/td[2]/span
Node: <span t-field="o.withholding_tax_amount" t-options="{\'widget\': \'monetary\', \'display_currency\': o.currency_id}"/>

The above server error caused the following client error:
null
```

**Comment by tafaRU** [comment]
Just tried on http://oca-l10n-italy-16-0-b5d415f6f330.runboat.odoo-community.org --> **Confirmed.**

**Comment by ser-tec** [comment]
I didn't realize, there is a similar problem due to the same problem #3160

**Comment by tafaRU** [comment]
Duplicated of https://github.com/OCA/l10n-italy/issues/3160
