### ISSUE TITLE
[RFC] Migliorie processo di eleborazione allegati fattura elettronica

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#3376]
Non esattamente un bug, anche se non so esattamente che abbia. Vorrei raccogliere commenti al riguardo.

Mi sono reso conto che uno dei possibili percorsi che porta all'esecuzione di https://github.com/OCA/l10n-italy/blob/76e0c360adcb1c432ab76e97401ffd43a8be111f/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1693-L1695

è quello che parte da un cron(), passa per https://github.com/OCA/l10n-italy/blob/76e0c360adcb1c432ab76e97401ffd43a8be111f/l10n_it_fatturapa_pec/models/mail_thread.py#L143

e per https://github.com/OCA/l10n-italy/blob/76e0c360adcb1c432ab76e97401ffd43a8be111f/l10n_it_fatturapa_in/models/attachment.py#L151-L160

(quando viene fatta la `create()`)

e il codice che processa gli xml è infarcito di `UserError()` https://github.com/OCA/l10n-italy/blob/76e0c360adcb1c432ab76e97401ffd43a8be111f/l10n_it_fatturapa/models/ir_attachment.py#L108-L141

che non sono il massimo durante un cron(), primo perché sono pensati per generare un popup utente, secondo perché interrompono l'esecuzione senza mezzi termini.

Un possibile rapido workaround potrebbe essere (a seconda del livello dove decidiamo farlo) prendere l'eccezione `UserError` e gestirla per es. qui (basso livello):
https://github.com/OCA/l10n-italy/blob/76e0c360adcb1c432ab76e97401ffd43a8be111f/l10n_it_sdi_channel/models/sdi.py#L194
oppure qui (alto livello):
https://github.com/OCA/l10n-italy/blob/76e0c360adcb1c432ab76e97401ffd43a8be111f/l10n_it_fatturapa_pec/models/mail_thread.py#L70-L75

e segnalare in modo più chiaro l'errore, magari nel chatter stile: https://github.com/OCA/l10n-italy/blob/76e0c360adcb1c432ab76e97401ffd43a8be111f/l10n_it_sdi_channel/models/sdi.py#L196-L200
per evitare che uno debba andare a guardarsi i log.

Ovviamente la cosa migliore sarebbe gestire gli errori diversamente, lasciando UserError() per l'interfaccia, se uno processa un XML a mano. Andrebbero lasciate tracce durante un processo cron() per capire cosa è fallito esattamente e dove.

**Comment by sergiocorato** [comment]
Concordo per verificare se è un cron e registrarli dove li possa vedere in seguito l'utente e lasciarli invece esposti per l'utente che esegue direttamente l'azione.

**Comment by TheMule71** [comment]
Per dire: 
```
odoo.addons.base.models.ir_cron: Unexpected exception while processing cron job {'id': 8, 'ir_actions_server_id': 132, 'cron_name': 'Mail: Fetchmail Service', 'user_id': 1, 'active': True, 'interval_number': 5, 'interval_
type': 'minutes', 'numbercall': -1, 'doall': False, 'nextcall': datetime.datetime(2023, 6, 9, 8, 10, 36), 'lastcall': datetime.datetime(2023, 6
, 7, 0, 9, 3), 'priority': 5, 'create_uid': 1, 'create_date': datetime.datetime(2022, 6, 4, 8, 42, 36, 728947), 'write_uid': 2, 'write_date': d
atetime.datetime(2023, 6, 9, 8, 8, 42, 559526)} 
Traceback (most recent call last):
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_fatturapa/models/ir_attachment.py", line 137, in get_xml_string
    return self.cleanup_xml(data)
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_fatturapa/models/ir_attachment.py", line 104, in cleanup_xml
    xml_string = self.remove_xades_sign(xml_string)
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_fatturapa/models/ir_attachment.py", line 85, in remove_xades_sign
    for elem in root.iter("*"):
AttributeError: 'NoneType' object has no attribute 'iter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_cron.py", line 161, in _process_job
    cron.flush()
  File "/home/odoo/src/odoo/odoo/models.py", line 5469, in flush
    self.recompute()
  File "/home/odoo/src/odoo/odoo/models.py", line 5928, in recompute
    process(field)
  File "/home/odoo/src/odoo/odoo/models.py", line 5912, in process
    field.recompute(recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1176, in recompute
    self.compute_value(recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1198, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/odoo/models.py", line 4076, in _compute_field_value
    odoo.fields.determine(field.compute, self)
  File "/home/odoo/src/odoo/odoo/fields.py", line 82, in determine
    return needle(*args)
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_fatturapa_in/models/attachment.py", line 103, in _compute_xml_data
    fatt = wiz_obj.get_invoice_obj(att)
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1694, in get_invoice_obj
    xml_string = fatturapa_attachment.get_xml_string()
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_fatturapa/models/ir_attachment.py", line 141, in get_xml_string
    raise UserError(_("Invalid xml %s.") % e.args)
odoo.exceptions.UserError: Invalid xml 'NoneType' object has no attribute '
```

**Comment by SirTakobi** [comment]
> il codice che processa gli xml è infarcito di `UserError()`
>
> che non sono il massimo durante un cron(), primo perché sono pensati per generare un popup utente, secondo perché interrompono l'esecuzione senza mezzi termini.

Credo che il comportamento debba rimanere lo stesso quando le operazioni vengono fatte da un CRON o dall'utente: se aggiungiamo anche la variabile _da che processo è stato eseguito il metodo_, diventa ancora più difficile venire a capo di potenziali problemi.
Per _risolvere_ le osservazioni che hai fatto potrebbe essere sufficiente rendere più informativi i messaggi sollevati dagli `UserError`: così sarebbero più utili sia lato utente che quando sollevati nel CRON.
Potremmo creare delle nuove eccezioni dove, ad esempio, è necessario inserire il nome del file per poterle lanciare e verrà poi riportato nel messaggio di errore.

Per quanto riguarda interrompere l'esecuzione, è la soluzione più semplice e pulita: quando c'è un problema si ripristina in automatico la situazione precedente (quando c'è un'eccezione c'è anche rollback automatico).
Per avere un procedimento (sia lato utente che lato CRON) che _salti_ i problemi, si possono aggiungere dei `savepoint` intorno al processamento di ogni file in modo da fare rollback in caso di problemi.
In questo caso però sorge anche il problema di dove mostrare questi errori _saltati_: nel chatter del mail server (se esiste)? In delle fatture elettroniche fittizie che riportano solo il banner di errore?

> Andrebbero lasciate tracce durante un processo cron() per capire cosa è fallito esattamente e dove.

:+1: si possono aggiungere dei log di INFO/DEBUG durante il processamento.

> `odoo.exceptions.UserError: Invalid xml 'NoneType' object has no attribute '`

Un esempio per cui il messaggio di errore andrebbe migliorato rendendolo più informativo

**Comment by filipposaviori** [comment]
Ho riscontrato questo problema con un cliente settimana scorsa. 
Andando a operare manualmente l'azione di fetchmail per i servere di posta in ingresso mi veniva restituito l'errore seguente:
![image](https://github.com/OCA/l10n-italy/assets/107557432/bb81bbd1-01e2-4329-848b-2b25f2c5ab97)


Per risolverlo ho dovuto operare un inserimento manuale delle fatture elettroniche, finche non si è sbloccato il processo di scaricamento mail siccome le PEC problematiche erano state lette/segnate come lette.

**Comment by filipposaviori** [comment]
Questo è uno dei file XML che ha causato l'errore: 
[IT02046570426_4x5uW.xml.zip](https://github.com/OCA/l10n-italy/files/11743828/IT02046570426_4x5uW.xml.zip)

**Comment by filipposaviori** [comment]
Si potrebbe creare una PR per questo problema di scaricamento PEC?
