### ISSUE TITLE
[14.0] l10n_it_withholding_tax: exactly one of precision_digits and precision_rounding must be specified

### ISSUE THREAD

**Issue by odooNextev** [OCA/l10n-italy#3398]
Provando a registrare un pagamento di una fattura di vendita si ottiene l'errore riportato sotto

## Module
l10n_it_withholding_tax

## Describe the bug
```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1374, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_withholding_tax/models/account.py", line 512, in action_register_payment
    if not float_is_zero(amount_net_pay_residual):
  File "/home/odoo/src/odoo/odoo/tools/float_utils.py", line 123, in float_is_zero
    epsilon = _float_check_precision(precision_digits=precision_digits,
  File "/home/odoo/src/odoo/odoo/tools/float_utils.py", line 26, in _float_check_precision
    assert (precision_digits is not None or precision_rounding is not None) and \
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AssertionError: exactly one of precision_digits and precision_rounding must be specified
```

- [ ] 14.0

**Comment by odooNextev** [comment]
@sergiocorato

**Comment by odooNextev** [comment]
Chiudo la issue perchè questo commit risolve il problema: https://github.com/OCA/l10n-italy/commit/e5a9f2128af4c93e7aea3e35affe99f9e1cbd54d
