### ISSUE TITLE
[14.0] fatturapa_in errore importazione 

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#3519]
Importare un file xml in cui è dichiarata l'esistenza di un allegato ma lo stesso non è presente dentro l'XML 
Si ottiene questo questo errore

Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1374, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/Borruso/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1794, in importFatturaPA
    invoice = self.invoiceCreate(
  File "/home/odoo/src/user/Borruso/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1178, in invoiceCreate
    self.set_attachments_data(FatturaBody, invoice)
  File "/home/odoo/src/user/Borruso/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1241, in set_attachments_data
    self.env["fatturapa.attachment.in"].extract_attachments(
  File "/home/odoo/src/user/Borruso/l10n-italy/l10n_it_fatturapa_in/models/attachment.py", line 140, in extract_attachments
    content = attach.Attachment.encode()
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'NoneType' object has no attribute 'encode'

Qui sotto il file originale e lo stesso XML modificato in modo che non sia presente l'informazione relativa all'attachement 
![image](https://github.com/OCA/l10n-italy/assets/19937703/bd1df0ab-432c-4fd3-8401-5894faf0b3b8)

L'importazione non dovrebbe fallire ma solo segnalare che l'allegato indicato in XML non è presente nello stesso e non generare errore 

- [ ] 14.0
- [ ] 16.0 https://github.com/OCA/l10n-italy/pull/5320

**Comment by eLBati** [comment]
@francescapenso puoi allegare un XML che riproduce l'errore?

**Comment by matteoopenf** [comment]
Tutt'ora c'è il problema

**Comment by francesco-ooops** [comment]
@matteoopenf hai te un XML da allegare?
