### ISSUE TITLE
Errore modulo 10n_it_fatturapa_in 

### ISSUE THREAD

**Issue by mlopesbjj** [OCA/l10n-italy#3632]
<!-- Provide a general summary of the issue in the Title above.
Dopo di aver aggiornato il modulo èd andato in errore.

## Module
10n_it_fatturapa_in.

## Describe the bug
Errore quando prova caricare il modulo.

## To Reproduce
Versione 16.0

1. Aggiorna il modulo in ODOO.SH dopo di questo quando fa il build va in errore.

Messaggio di errore:
03/10/2023 12:58:00	ERROR	server	Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 208, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name}, new_install)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 526, in init_models
    model._auto_init()
  File "/home/odoo/src/odoo/odoo/models.py", line 2578, in _auto_init
    new = field.update_db(self, columns)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1006, in update_db
    self.update_db_column(model, column)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1042, in update_db_column
    self._convert_db_column(model, column)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1046, in _convert_db_column
    sql.convert_column(model._cr, model._table, self.name, self.column_type[1])
  File "/home/odoo/src/odoo/odoo/tools/sql.py", line 128, in convert_column
    _convert_column(cr, tablename, columnname, columntype, using)
  File "/home/odoo/src/odoo/odoo/tools/sql.py", line 147, in _convert_column
    cr.execute(query, log_exceptions=False)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.DatatypeMismatch: foreign key constraint "wizard_export_fatturapa_report_print_menu_fkey" cannot be implemented
DETAIL:  Key columns "report_print_menu" and "id" are of incompatible types: character varying and integer.

**Comment by mlopesbjj** [comment]
Ho aggiornato il modulo e quando ODOO.SH prova a fare rebuild va in errore, non riesci a caricare il modulo.
Versione: 16.0
errore:

03/10/2023 12:58:00	ERROR	server	Failed to load registry

DETAIL:  Key columns "report_print_menu" and "id" are of incompatible types: character varying and integer.

**Comment by michelerusti** [comment]
dai un'occhiata a #3649 quell'errore dovrebbe far parte di `fatturapa_out`

**Comment by tafaRU** [comment]
Chiudo in favore di https://github.com/OCA/l10n-italy/issues/3649
