### ISSUE TITLE
16.0 | l10n_it_delivery_note

### ISSUE THREAD

**Issue by mlopesbjj** [OCA/l10n-italy#3756]
Bungiorno,
Ho appena provato aggiornare il modulo di OCA dentro ODOO.SH, quando faccio l'aggiornamento va in errore: ModuleNotFoundError: No module named 'openupgradelib'
Però, questo modulo ('openupgradelib') èd installado.

Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 236, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/odoo/modules/migration.py", line 180, in migrate_module
    mod = load_script(pyfile, name)
  File "/home/odoo/src/odoo/odoo/modules/migration.py", line 25, in load_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_delivery_note/migrations/16.0.1.1.0/post-migration.py", line 1, in <module>
    from openupgradelib import openupgrade  # pylint: disable=W7936
ModuleNotFoundError: No module named 'openupgradelib'

![image](https://github.com/OCA/l10n-italy/assets/48922995/23000972-7c0c-4652-b0d4-462063f71fba)

**Comment by SirAionTech** [comment]
`openupgradelib` è una libreria Python che va installata seguendo https://github.com/OCA/openupgradelib#install, non come un submodule.

**Comment by mlopesbjj** [comment]
Grazie mille!
