### ISSUE TITLE
Errore nei test di currency_rate_update_boi

### ISSUE THREAD

**Issue by SirAionTech** [OCA/l10n-italy#3801]
> @Borruso puoi verificare gli errori sollevati in https://github.com/OCA/l10n-italy/actions/runs/6453424689/job/17516975924?

fatto, la chiamata a BOI nel weekend non restituisce dati creata funzione nei per verificare se data è sabato o domenica.

_Originally posted by @Borruso in https://github.com/OCA/l10n-italy/issues/3643#issuecomment-1761162885_

L'errore indicato nel commento continua a verificarsi: https://github.com/OCA/l10n-italy/actions/runs/7337345959/job/19978097725#step:8:807

**Comment by francesco-ooops** [comment]
@Borruso ci son diverse PR bloccate da questo bug, riesci a dargli un'occhiata?

**Comment by Borruso** [comment]
#3848

**Comment by SirAionTech** [comment]
Non posso riaprire, ma sembra che l'errore sia tornato a presentarsi in https://github.com/OCA/l10n-italy/pull/4079.

**Comment by francesco-ooops** [comment]
@SirAionTech qualcosa che ha a che fare con la pasqua?

**Comment by SirAionTech** [comment]
> @SirAionTech qualcosa che ha a che fare con la pasqua?

Grazie di aver riaperto; l'ho pensato anche io, può essere.

**Comment by SirAionTech** [comment]
Si è verificato di nuovo in https://github.com/OCA/l10n-italy/pull/3703:
```
2024-10-28 14:17:50,372 529 ERROR odoo odoo.addons.currency_rate_update_boi.tests.test_currency_rate_update_boi: FAIL: TestCurrencyRateUpdate.test_update_BOI_year
Traceback (most recent call last):
  File "/__w/l10n-italy/l10n-italy/currency_rate_update_boi/tests/test_currency_rate_update_boi.py", line 95, in test_update_BOI_year
    self.assertTrue(rates)
AssertionError: res.currency.rate() is not true
```
(da https://github.com/OCA/l10n-italy/actions/runs/11555600876/job/32161393710#step:8:1272)

**Comment by SirAionTech** [comment]
Si è verificato di nuovo in https://github.com/OCA/l10n-italy/pull/4298:
```
2025-01-07 15:18:47,042 533 ERROR odoo odoo.addons.currency_rate_update_boi.tests.test_currency_rate_update_boi: FAIL: TestCurrencyRateUpdate.test_foreign_base_currency
Traceback (most recent call last):
  File "/__w/l10n-italy/l10n-italy/currency_rate_update_boi/tests/test_currency_rate_update_boi.py", line 155, in test_foreign_base_currency
    self.test_update_BOI_yesterday()
  File "/__w/l10n-italy/l10n-italy/currency_rate_update_boi/tests/test_currency_rate_update_boi.py", line 73, in test_update_BOI_yesterday
    self.assertTrue(rates)
AssertionError: res.currency.rate() is not true
```
(da https://github.com/OCA/l10n-italy/actions/runs/12653935875/job/35260575777#step:8:1267)

**Comment by francesco-ooops** [comment]
Gli errori sembrano capitare sempre intorno ai giorni rossi del calendario...

@Borruso

**Comment by eLBati** [comment]
Qui https://github.com/OCA/l10n-italy/actions/runs/16116956525/job/45472962718?pr=4823 fallisce con `odoo.tests.common.BlockedRequest: External requests verboten`

Credo convenga fare un mock del sistema esterno
