### ISSUE TITLE
[16.0]|10n_it_fatturapa AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by mlopesbjj** [OCA/l10n-italy#3861]
**ODOO 16.0 | Odoo.sh**
Abbiamo installato il modulo di fattura eletronica Aruba che è stato svilupato da Openforce. 
Quando l'XML è caricato in automatico tramite il modulo Openforce il pulsante MOSTRA ANTEPRIMA va in errore: **AttributeError: 'bytes' object has no attribute 'encode'**
Però se carichiamo l'XML manualmente il pulsante funziona.

Sotto giro lo stack dell'errore:
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1591, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1618, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1732, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/user/OCA/l10n-italy/l10n_it_fatturapa/controllers/main.py", line 16, in pdf_preview
    pdf = request.env["ir.actions.report"]._run_wkhtmltopdf([html])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 450, in _run_wkhtmltopdf
    body_file.write(body.encode())
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by matteoopenf** [comment]
> @mlopesbjj penso dovresti verificare con Openforce se il problema è del loro modulo o c'è un modo di replicare l'errore con i soli moduli OCA Italy
> 
> cc @matteoopenf

gli sto dando supporto e fornito una prima soluzione per email
