### ISSUE TITLE
Errore File e-fatture in ingresso e esportati

### ISSUE THREAD

**Issue by maxgrassi** [OCA/l10n-italy#3880]
Buongiorno, prementto che i moduli funzionavano correttamente e che da fine scorsa settimana in File e-fatture in ingresso e in File fattura elettronica esportati cliccando su nuovo oppure cliccando su un file presente nell'elenco dei file ricevuti mi da il seguente errore.

**File e-fatture in ingresso**
UncaughtPromiseError > OwlError
Promise non rilevata > An error occured in the owl lifecycle (see this Error's "cause" property)

OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1472:101)
    at owl.App.handleError (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2098:29)
    at Fiber._render (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1497:19)
    at Fiber.render (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1495:6)
    at ComponentNode.initiateRender (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1563:47)

Caused by: TypeError: Cannot read properties of null (reading 'append')
    at append (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:1777:105)
    at FormCompiler.compile (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:16435:714)
    at compile (patch web_chatter_position) (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:1676:22)
    at useViewCompiler (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:5654:166)
    at FormRenderer.setup (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:3998:1320)
    at new ComponentNode (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1558:202)
    at https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2096:6
    at FormController.slot5 (eval at compile (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2056:374), <anonymous>:69:27)
    at callSlot (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1665:25)
    at Layout.template (eval at compile (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2056:374), <anonymous>:46:10)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1472:101)
    at owl.App.handleError (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2098:29)
    at Fiber._render (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1497:19)
    at Fiber.render (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1495:6)
    at ComponentNode.initiateRender (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1563:47)

Caused by: TypeError: Cannot read properties of null (reading 'append')
    at append (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:1777:105)
    at FormCompiler.compile (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:16435:714)
    at compile (patch web_chatter_position) (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:1676:22)
    at useViewCompiler (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:5654:166)
    at FormRenderer.setup (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:3998:1320)
    at new ComponentNode (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1558:202)
    at https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2096:6
    at FormController.slot5 (eval at compile (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2056:374), <anonymous>:69:27)
    at callSlot (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1665:25)
    at Layout.template (eval at compile (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2056:374), <anonymous>:46:10)

**File fattura elettronica esportati**
UncaughtPromiseError > OwlError
Promise non rilevata > An error occured in the owl lifecycle (see this Error's "cause" property)

OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1472:101)
    at owl.App.handleError (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2098:29)
    at Fiber._render (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1497:19)
    at Fiber.render (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1495:6)
    at ComponentNode.initiateRender (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1563:47)

Caused by: TypeError: Cannot read properties of null (reading 'append')
    at append (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:1777:105)
    at FormCompiler.compile (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:16435:714)
    at compile (patch web_chatter_position) (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:1676:22)
    at useViewCompiler (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:5654:166)
    at FormRenderer.setup (https://www.xxx.com/web/assets/73463-a7bd57e/web.assets_backend.min.js:3998:1320)
    at new ComponentNode (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1558:202)
    at https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2096:6
    at FormController.slot5 (eval at compile (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2056:374), <anonymous>:69:27)
    at callSlot (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:1665:25)
    at Layout.template (eval at compile (https://www.xxx.com/web/assets/73462-12f09e1/web.assets_common.min.js:2056:374), <anonymous>:46:10)

## Module
l10n_it_fatturapa_in
l10n_it_fatturapa_out
Odoo 16 CE

Prima del verificarsi del problema erano stati installati solamente: 
account_statement_import_online
account_statement_import_online_paypal
Ho provato a rimuovere entrambi i file  ma la problematica resta quindi non ritengo siano i responsabili.

Tutti i moduli fatturaPA sono aggiornati all'ultima versione e anche la versione di odoo 16 è aggiornata.

Grazie di un eventuale suggerimento per risolvere la problematica.

**Comment by francesco-ooops** [comment]
@maxgrassi è riproducibile su runboat?

**Comment by francesco-ooops** [comment]
@maxgrassi e questo è riprodotto su runboat giusto?

**Comment by francesco-ooops** [comment]
Chiuso perchè risolta
