### ISSUE TITLE
Liquidazione IVA - Bug creazione movimenti con termini di pagamento

### ISSUE THREAD

**Issue by hillmulo** [OCA/l10n-italy#3977]
Versioni coinvolte

- [ ] 16.0

Scenario: 
quando nella liquidazione IVA si selezionano i termini di pagamento, cliccando sul tasto 'crea movimento' viene restituito il seguente errore: 

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1633, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1660, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1864, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/OCA/l10n-italy/account_vat_period_end_statement/models/account.py", line 448, in create_move
    self._add_end_debit_vat_data(
  File "/home/odoo/src/user/OCA/l10n-italy/account_vat_period_end_statement/models/account.py", line 470, in _add_end_debit_vat_data
    due_list = statement.payment_term_id.compute(
AttributeError: 'account.payment.term' object has no attribute 'compute'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://apuliasoftware-senec16-stage-9820478.dev.odoo.com/web/assets/222720-826102e/web.assets_backend.min.js:999:163)
    at XMLHttpRequest.<anonymous> (https://apuliasoftware-senec16-stage-9820478.dev.odoo.com/web/assets/222720-826102e/web.assets_backend.min.js:1007:13)
```

https://github.com/OCA/l10n-italy/blob/f966a7972c332e73f890574c937184f6f428ea09/account_vat_period_end_statement/models/account.py#L470

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Puoi verificare se https://github.com/OCA/l10n-italy/pull/3729 risolve? Nel caso potresti approvarla, vedi https://www.odoo-italia.org/documentazione/14.0/sviluppo/review.html.

**Comment by hillmulo** [comment]
> Grazie della segnalazione! Puoi verificare se #3729 risolve? Nel caso potresti approvarla, vedi https://www.odoo-italia.org/documentazione/14.0/sviluppo/review.html.

Salve,
al momento la runbot della PR non risulta essere raggiungibile.
Grazie

**Comment by francesco-ooops** [comment]
@hillmulo ora dovrebbe andare

**Comment by odooNextev** [comment]
@SirAionTech confermo che la https://github.com/OCA/l10n-italy/pull/3729 risolve il problema

**Comment by hillmulo** [comment]
@SirAionTech @francesco-ooops test effettuati, la #3729 risolve il problema

**Comment by SirAionTech** [comment]
In `14.0` il problema non sussiste, vedi https://github.com/OCA/l10n-italy/pull/3729.
