### ISSUE TITLE
[10.0] l10n_it_fiscal_document_type error

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#441]
se un utente ha solo permessi sale manager, aprendo l'anagrafica clienti si verifica questo errore:

`Traceback (most recent call last):
  File "/opt/odoo/buildout/parts/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/buildout/parts/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/buildout/parts/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/buildout/parts/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/buildout/parts/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/buildout/parts/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/buildout/parts/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/buildout/parts/odoo/odoo/models.py", line 1334, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo/buildout/parts/odoo/odoo/models.py", line 1334, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/res/res_partner.py", line 312, in fields_view_get
    res = super(Partner, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 362, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo/buildout/parts/odoo/odoo/models.py", line 1393, in fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 668, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 617, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 595, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 468, in raise_view_error
    raise ValueError(message)
ValueError: L'elemento '<xpath expr="//field[@name='property_payment_term_id']">' non pu\xf2 esser localizzato nella vista genitore

Contesto errore:
Vista `res.partner.fiscal.document.type.form`
[view_id: 820, xml_id: l10n_it_fiscal_document_type.view_partner_fiscal_document_type, model: res.partner, parent_id: 124]`

se invece assegno permessi fatturazione, non si verifica nessun errore

**Comment by sergiocorato** [comment]
chiudo per inattività
