### ISSUE TITLE
Problema installazione modulo DDT su Odoo10

### ISSUE THREAD

**Issue by upsens** [OCA/l10n-italy#504]
Ciao a tutti,

ho un problema con installare il modulo DDT. Vedo che l'unica dipendenza che manca a questo 
pacchetto è il stock_picking_package_preparation_line di cui i dati:

Nome Tecnico | stock_picking_package_preparation_line
Licenza | Affero GPL-3
Ultima Versione | 10.0.1.0.1

se provo però ad installarlo ottengo questo errore:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/modules/loading.py", line 136, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/opt/odoo/odoo/modules/registry.py", line 322, in init_models
    model._auto_end()
  File "/opt/odoo/odoo/models.py", line 2584, in _auto_end
    cr.execute(query % (table1, column, table2, ondelete))
  File "/opt/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: there is no primary key for referenced table "stock_move"

se provo con il pacchetto ddt ottengo sempre l'errore there: is no primary key for referenced table "stock_move"

A cosa può essere dovuto? Grazie

**Comment by upsens** [comment]
Ciao, semplicemente premendo sul tasto installa del modulo DDT compare questo errore. Ho allora provato a vedere le dipendenze mancanti 

![image](https://user-images.githubusercontent.com/30519326/41081353-d4dda376-6a2a-11e8-9f9a-b694935a9121.png)

e provato ad installare il pacchetto mancante che mi restituisce lo stesso errore. Grazie!

**Comment by eLBati** [comment]
Se fosse sufficiente installare il modulo per sollevare questa eccezione, i test automatici fallirebbero. Ma sono verdi
https://travis-ci.org/OCA/stock-logistics-workflow/branches
https://travis-ci.org/OCA/l10n-italy/branches

Ti consiglio di verificare la tua installazione, assicurandoti di avere i moduli alla versione più recente e non avere moduli extra bacati
