### ISSUE TITLE
[8.0] Registri IVA - l10n_it_vat_registries

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#56]
I'm opening this because we are going to work on ```l10n_it_vat_registries``` for 8.0
Is anybody else working on it?
I think we should port them to qweb.

**Comment by greenstrategy** [comment]
Hi, i have installed this module but when i try to print the report i receive this error:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/addons/report/controllers/main.py", line 125, in report_download
    response = self.report_routes(reportname, converter='pdf', **dict(data))
  File "/opt/odoo/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/report/controllers/main.py", line 65, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 186, in get_pdf
    html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 161, in get_html
    return particularreport_obj.render_html(cr, uid, ids, data=data, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/abstract_report.py", line 64, in render_html
    return self.pool['report'].render(cr, uid, [], self._template, docargs, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/report/models/report.py", line 147, in render
    return view_obj.render(cr, uid, template, values, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/website/models/ir_ui_view.py", line 171, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1007, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 426, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 435, in render_tag_call
    return self.render(cr, uid, template, d)
  File "/opt/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 367, in render_tag_esc
    inner = widget.format(template_attributes['esc'], options, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 982, in format
    return escape(self._format(inner, options, qwebcontext))
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 979, in _format
    return self.pool['ir.qweb'].eval_str(inner, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 205, in eval_str
    val = self.eval(expr, qwebcontext)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 197, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 194, in eval
    return qwebcontext.safe_eval(expr)
  File "/opt/odoo/openerp/addons/base/ir/ir_qweb.py", line 80, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/opt/odoo/openerp/tools/safe_eval.py", line 313, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
QWebException: "'NoneType' object is not callable" while evaluating
"context_timestamp(datetime.datetime.now()).strftime('%Y')"

Can you help me please ?

**Comment by eLBati** [comment]
@greenstrategy please do not multi post your problem. Ref https://github.com/OCA/l10n-italy/issues/157
