### ISSUE TITLE
Unable to install l10n_it_fatturapa_in on Odoo10

### ISSUE THREAD

**Issue by AlessioRosi** [OCA/l10n-italy#651]
raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Errore durante la validazione del vincolo

Modello non trovato: wizard.import.fatturapa

Contesto errore:
Vista `Import Fattura Elettronica`
[view_id: 1060, xml_id: n/d, model: wizard.import.fatturapa, parent_id: n/d]
None" while parsing /opt/odoo/10.0/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa_view.xml:4, near
<record id="wizard_import_fatturapa_form_view" model="ir.ui.view">
            <field name="name">Import Fattura Elettronica</field>
            <field name="model">wizard.import.fatturapa</field>
            <field name="arch" type="xml">
                <form string="Import Fattura Elettronica">
                    <group>
                        <field name="e_invoice_detail_level"/>
                        <footer>
                            <button special="cancel" string="Cancel"/>
                            <button name="importFatturaPA" string="Import" type="object"/>
                        </footer>
                    </group>
                </form>
            </field>
        </record>

**Comment by eLBati** [comment]
`l10n_it_fatturapa_in` è installabile in odoo 10.
Controlla che l'installazione su file system sia completa e corretta.

**Comment by AlessioRosi** [comment]
sono riuscito ad installare facilmente tutti i moduli presenti in l10n-italy tranne:
l10n_it_fatturapa_in
l10n_it_fatturapa_in_purchase
l10n_it_fatturapa_out
l10n_it_fatturapa_out_ddt


....il modulo l10n_it_fatturapa è installato correttamente

tutta la localizzazione è stata scaricata da GIT


Riscrivo in maniera più completa l'errore di installazione che mi da su tutti e quattro i moduli che non riesco ad installare (ovviamente contestualizzato in relazione al Modello non trovato)




`Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 1182, in run
    result = request.env['ir.actions.server'].browse([action_id]).run()
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_actions.py", line 990, in run
    res = func(action, eval_context=eval_context)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_actions.py", line 805, in run_action_code_multi
    safe_eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/usr/lib/python2.7/site-packages/odoo/tools/safe_eval.py", line 301, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 412, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 486, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 377, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 270, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 96, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_model.py", line 1238, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 362, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3854, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 1046, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3567, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3731, in _write
    self._validate_fields(vals)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1081, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ValueError: <class 'odoo.tools.convert.ParseError'>: ""Errore durante la validazione del vincolo

Modello non trovato: wizard.import.fatturapa

Contesto errore:
Vista Import Fattura Elettronica
[view_id: 1070, xml_id: n/d, model: wizard.import.fatturapa, parent_id: n/d]
None" while parsing /opt/odoo/10.0/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa_view.xml:4, near
`
 
`<record id="wizard_import_fatturapa_form_view" model="ir.ui.view">
            <field name="name">Import Fattura Elettronica</field>
            <field name="model">wizard.import.fatturapa</field>
            <field name="arch" type="xml">
                <form string="Import Fattura Elettronica">
                    <group>
                        <field name="e_invoice_detail_level"/>
                        <footer>
                            <button special="cancel" string="Cancel"/>
                            <button name="importFatturaPA" string="Import" type="object"/>
                        </footer>
                    </group>
                </form>
            </field>
        </record>`
 while evaluating
u'records.button_immediate_install()'

**Comment by AlessioRosi** [comment]
lo avevo visto prima di scrivere ... e solo che non mi capacito :-( e volevo chiedere se a qualcuno fosse capitato e come avesse risolto.  Comunque graze :-)

**Comment by eLBati** [comment]
`Modello non trovato: wizard.import.fatturapa` è come se non trovasse il file python del model.
Ti consiglio di verificare l'integrità del tuo repository git locale. Eventualmente prova a riscaricarlo tutto.
