### ISSUE TITLE
[11] esportazione file xml

### ISSUE THREAD

**Issue by denisgottardello** [OCA/l10n-italy#806]
In fase di esportazione si ottiene il seguente errore
Errore:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 809, in exportFatturaPA
    company, partner, fatturapa)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 750, in setFatturaElettronicaHeader
    self.setDatiTrasmissione(company, partner, fatturapa)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 210, in setDatiTrasmissione
    self._setContattiTrasmittente(company, fatturapa)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 200, in _setContattiTrasmittente
    Telefono=Telefono, Email=Email)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 2098, in __init__
    fu.set(self, iv)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\content.py", line 1043, in set
    value = self.__elementBinding.compatibleValue(value, is_plural=self.isPlural())
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 1643, in compatibleValue
    return self.typeDefinition()._CompatibleValue(value, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 385, in _CompatibleValue
    return cls(value)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 943, in __init__
    self.xsdConstraintsOK(location)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 1069, in xsdConstraintsOK
    return self.XsdConstraintsOK(self, location)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 1064, in XsdConstraintsOK
    raise pyxb.SimpleFacetValueError(cls, value, f, location)
pyxb.exceptions_.SimpleFacetValueError: Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}TelFaxType pattern constraint violated by value +39.347.4070897

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 829, in exportFatturaPA
    except (SimpleFacetValueError, SimpleTypeValueError) as e:
NameError: name 'SimpleFacetValueError' is not defined

**Comment by caiuka** [comment]
Ad occhio e croce il numero di telefono è scritto in modo "errato", non seguendo un pattern consentito.
Probabilmente i punti tra i numeri...

> {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}TelFaxType pattern constraint violated by value **+39.347.4070897**

**Comment by denisgottardello** [comment]
Sistemato il numero ho il seguente errore relativo alla nazione, non capisco quale sia il campo da sistemare, se nel cliente o nell'azienda. Mi sempra infatti corretto ciò che c'è adesso.

Errore:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 809, in exportFatturaPA
    company, partner, fatturapa)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 753, in setFatturaElettronicaHeader
    self.setCessionarioCommittente(partner, fatturapa)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 482, in setCessionarioCommittente
    self._setDatiAnagraficiCessionario(partner, fatturapa)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 367, in _setDatiAnagraficiCessionario
    IdPaese=partner.vat[0:2], IdCodice=partner.vat[2:])
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 2098, in __init__
    fu.set(self, iv)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\content.py", line 1043, in set
    value = self.__elementBinding.compatibleValue(value, is_plural=self.isPlural())
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 1643, in compatibleValue
    return self.typeDefinition()._CompatibleValue(value, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 385, in _CompatibleValue
    return cls(value)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 943, in __init__
    self.xsdConstraintsOK(location)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 1069, in xsdConstraintsOK
    return self.XsdConstraintsOK(self, location)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 1064, in XsdConstraintsOK
    raise pyxb.SimpleFacetValueError(cls, value, f, location)
pyxb.exceptions_.SimpleFacetValueError: Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}NazioneType pattern constraint violated by value 09

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 829, in exportFatturaPA
    except (SimpleFacetValueError, SimpleTypeValueError) as e:
NameError: name 'SimpleFacetValueError' is not defined

**Comment by bitit-it** [comment]
neanche +39 mi risulta valido 
Enrico

**Comment by denisgottardello** [comment]
Attenzione, il numero è già stato sistemato. Ora c'è un secondo problema, codice nazione 
o similare.

In data mercoledì 9 gennaio 2019 08:07:27 CET, bitit-it ha scritto:
> neanche +39 mi risulta valido
> Enrico-- 
+39.347.4070897
www.labcsp.com[1] 
www.denisgottardello.it[2] 
GMT+1
Skype: mrdebug

--------
[1] http://www.labcsp.com
[2] http://www.denisgottardello.it

**Comment by bitit-it** [comment]
e anche quello dell'azienda, chiede: città, nazione , cap , paese ,  e in nazione chiede codice nazione, quando ti si apre la finestra di configurazione.  
Io ho messo la provincia, ma come ti dicevo, quando mettevo la sigla dela rpvincia mi dava errore, così ho messo la provincia per esteso. 
La prima volta, dandomi lo stesso errore che creo hai tu in esportazione,  non prendendomi la sigla della provincia avevo messo la sigla della nazione. 

Enrico

**Comment by denisgottardello** [comment]
Ho provato a mettere IT dappertutto ma njon cambia, sempre lo stesso errore.
Forse odoo 11 non converte da Italy ad IT

**Comment by denisgottardello** [comment]
Qual è la tabella che contiene l'anagrafica clienti?

**Comment by denisgottardello** [comment]
tabella trovata.
C'è un modo per patchare il sorgente di modo che possa creare il file con codice nazione IT fintantoché la cosa viene sistemata?
Sono infatti bloccato.

**Comment by bitit-it** [comment]
forse non parliamo dello stesso errore,  posta l'output.

Enrico

**Comment by denisgottardello** [comment]
Errore:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 809, in exportFatturaPA
    company, partner, fatturapa)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 753, in setFatturaElettronicaHeader
    self.setCessionarioCommittente(partner, fatturapa)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 482, in setCessionarioCommittente
    self._setDatiAnagraficiCessionario(partner, fatturapa)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 367, in _setDatiAnagraficiCessionario
    IdPaese=partner.vat[0:2], IdCodice=partner.vat[2:])
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 2098, in __init__
    fu.set(self, iv)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\content.py", line 1043, in set
    value = self.__elementBinding.compatibleValue(value, is_plural=self.isPlural())
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 1643, in compatibleValue
    return self.typeDefinition()._CompatibleValue(value, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 385, in _CompatibleValue
    return cls(value)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 943, in __init__
    self.xsdConstraintsOK(location)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 1069, in xsdConstraintsOK
    return self.XsdConstraintsOK(self, location)
  File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\pyxb\binding\basis.py", line 1064, in XsdConstraintsOK
    raise pyxb.SimpleFacetValueError(cls, value, f, location)
pyxb.exceptions_.SimpleFacetValueError: Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}NazioneType pattern constraint violated by value 09

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\l10n_it_fatturapa_out\wizard\wizard_export_fatturapa.py", line 829, in exportFatturaPA
    except (SimpleFacetValueError, SimpleTypeValueError) as e:
NameError: name 'SimpleFacetValueError' is not defined

**Comment by denisgottardello** [comment]
I dati sono giusti, ho messo pure la parte REA ma comunque ho sempre l'errore.

**Comment by eLBati** [comment]
`NazioneType` è definito così

```
  <xs:simpleType name="NazioneType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{2}" />
    </xs:restriction>
  </xs:simpleType>
```

quindi non può contenere `09`

**Comment by denisgottardello** [comment]
Sono d'accordo, il fatto è che non ho idea da dove abbia preso quello 09.
Vedo nella tabella clienti il valore del campo "commercial_company_name" = a 109, 109 corrisponde ad Italy, che lo prenda da lì forse?

**Comment by eLBati** [comment]
`NazioneType` è usato anche per `IdPaese`, quindi per il prefisso della P.IVA. Hai da qualche parte una P.IVA che inizia con `09` senza prefisso nazionale?

**Comment by denisgottardello** [comment]
Pare che sistemata la parte REA ci siamo...
