### ISSUE TITLE
[10] campo codice fiscale azienda 

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#808]
in odoo10 mi manca come settare il codice ficale delle aziende , mi manca qualche modulo?
Enrico

**Comment by eLBati** [comment]
In quale caso serve?

**Comment by bitit-it** [comment]
è obbligatorio in fattura , a quanto mi dice il commercialista.
Enrico

**Comment by eLBati** [comment]
Il campo `CodiceFiscale` è obbligatorio quando non viene valorizzato `IdFiscaleIVA`. Ora, assumendo che stia parlando della tua azienda che emette fattura (visto che per i tuoi clienti è ovviamente possibile inserire il codice fiscale), dovrebbe esserti sufficiente inserire la P.IVA

**Comment by bitit-it** [comment]
https://www.commercialistatelematico.com/documenti/codicefiscale.htm

**Comment by bitit-it** [comment]
Buon giorno, ho seguito questo consiglio per inserire il mio codice fiscale, ed è sparito anche l'errore che avevo sul file xml 
Enrico 

FriCk

URL : https://www.odoo-italia.org/index.php/kunena/8-contabilita-e-finanza/14940-sviluppo-fattura-elettronica-b2b/32516

Messaggio
-----
In merito al problema del codice, bisogna inserire il codice fiscale nel contatto utilizzato nella Company. Vai su clienti, togli il filtro clienti in alto a dx, inserisci il nome della tua azienda, troverai un contatto che in realtà è la tua azienda. Entra e inserisci il codice fiscale, rigeneri xml e funziona 99.9%
-------------

**Comment by eLBati** [comment]
@bitit-it prova per favore questa patch https://github.com/OCA/l10n-italy/pull/845

**Comment by bitit-it** [comment]
@eLBati  buona sera , ho rifatto un istallazione fresca , poi ho modificato  e aggiunto quanto da te descritto , ho riavviato odoo e tentato di installare fatturapa, con il segunete errore e interefaccia pianrtata con i menù spariti .
non so se ho sbagliato qualcosa ma ho cotrollato un paio di volte provato a togliere le modifiche e menu di oddo riapparso 
Enrico

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/site-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/site-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/site-packages/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_model.py", line 1188, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 353, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3823, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 999, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_ui_view.py", line 371, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3555, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3701, in _write
    self._validate_fields(vals)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1074, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

Modello non trovato: wizard.compute.fc

Contesto errore:
Vista `wizard.compute.fc.form`
[view_id: 515, xml_id: n/d, model: wizard.compute.fc, parent_id: n/d]
None" while parsing /usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fiscalcode/wizard/compute_fc_view.xml:3, near
<record id="wizard_compute_fc_form" model="ir.ui.view">
        <field name="name">wizard.compute.fc.form</field>
        <field name="model">wizard.compute.fc</field>
        <field name="type">form</field>
        <field name="arch" type="xml">
            <form string="Fiscal Code">
                <group col="2" width="250">
                    <group string="Individual Data">
                        <field name="fiscalcode_surname" colspan="2" default_focus="1"/>
                        <field name="fiscalcode_firstname" colspan="2"/>
                        <field name="sex" colspan="2"/>
                        <field name="birth_date" colspan="2"/>
                        <field name="birth_city"/>
                        <field name="birth_province"/>
                    </group>
                    <newline/>
                    <footer>
                        <button name="compute_fc" type="object" string="Compute" class="btn-primary"/>
                        <button string="Cancel" special="cancel" class="btn-default"/>
                    </footer>
                </group>
            </form>
        </field>
    </record>

**Comment by eLBati** [comment]
@bitit-it ottimo. Puoi mettere l'approvazione su https://github.com/OCA/l10n-italy/pull/845 ?
Vedi https://odoo-community.org/page/review come guida.

**Comment by eLBati** [comment]
@bitit-it per l'approvazione in sé devi andare nel tab `files changed` > `review changes` > `approve` > `submit`

**Comment by bitit-it** [comment]
Fatto. ancora grazie!
