### ISSUE TITLE
[8.0] l10n_it_fatturapa_pec non installabile

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#822]
Provando a installare il modulo in oggetto, si ottiene:
```
2019-01-10 11:54:43,624 10730 INFO odoo8-9771 openerp.modules.module: module l10n_it_fatturapa_pec: creating or updating database tables
2019-01-10 11:54:43,986 10730 INFO odoo8-9771 openerp.models: Storing computed values of account.invoice fields fatturapa_state
2019-01-10 11:54:43,988 10730 INFO odoo8-9771 openerp.modules.loading: loading l10n_it_fatturapa_pec/views/account.xml
2019-01-10 11:54:44,086 10730 INFO odoo8-9771 openerp.modules.loading: loading l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml
2019-01-10 11:54:44,120 10730 ERROR odoo8-9771 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/simone/work/odoo8/odoo/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/simone/work/odoo8/odoo/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/home/simone/work/odoo8/odoo/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/simone/work/odoo8/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/simone/work/odoo8/odoo/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/simone/work/odoo8/odoo/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/home/simone/work/odoo8/odoo/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/home/simone/work/odoo8/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/simone/work/odoo8/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/simone/work/odoo8/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/simone/work/odoo8/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/simone/work/odoo8/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/simone/work/odoo8/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/simone/work/odoo8/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/simone/work/odoo8/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/simone/work/odoo8/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/simone/work/odoo8/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/simone/work/odoo8/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/simone/work/odoo8/odoo/openerp/tools/convert.py", line 897, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/simone/work/odoo8/odoo/openerp/tools/convert.py", line 983, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/simone/work/odoo8/odoo/openerp/tools/convert.py", line 849, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/simone/work/odoo8/odoo/openerp/tools/convert.py", line 751, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/home/simone/work/odoo8/odoo/openerp/tools/convert.py", line 828, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/home/simone/work/odoo8/odoo/openerp/tools/convert.py", line 839, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/home/simone/work/odoo8/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/simone/work/odoo8/odoo/openerp/addons/base/ir/ir_model.py", line 909, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/home/simone/work/odoo8/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/home/simone/work/odoo8/odoo/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/simone/work/odoo8/odoo/openerp/addons/base/ir/ir_model.py", line 899, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: l10n_it_fatturapa_out.view_fatturapa_out_attachment_tree" while parsing /home/simone/work/odoo8/e-invoice/l10n_it_fatturapa_pec/views/fatturapa_attachment_out.xml:38, near
<record model="ir.ui.view" id="view_fatturapa_out_attachment_tree_state">
            <field name="name">view_fatturapa_out_attachment_tree_state</field>
            <field name="model">fatturapa.attachment.out</field>
            <field name="inherit_id" ref="l10n_it_fatturapa_out.view_fatturapa_out_attachment_tree"/>
            <field name="arch" type="xml">
                <field name="out_invoice_ids" position="after">
                    <field name="state"/>
                <field name="sending_date"/>
                <field name="delivered_date"/>
                </field>
            </field>
        </record>
```
Ho controllato Travis per il branch 8.0 e in effetti si blocca anche prima: durante i [test di l10n_it_fatturapa_out](https://travis-ci.org/OCA/l10n-italy/jobs/476869553#L1559)

**Comment by sergiocorato** [comment]
a me si installa, l'errore che segnali è comunque dovuto ad un'altra questione:
`from openerp.addons.account.tests.account_test_users import AccountTestUsers`
che sono test che esistono nella 10.0 e non nella 8.0 (io ci sto lavorando un po' per farli, ma non è banale, è stato fatto un merge senza che i test fossero stati fatti del tutto)

**Comment by sergiocorato** [comment]
(cioè erano i test della 10.0 copiati tali e quali senza modifiche)

**Comment by eLBati** [comment]
Aggiornamento: @SimoRubi non riusciva ad installare perchè prendeva i moduli da https://pypi.org/project/odoo8-addon-l10n-it-fatturapa-out dove l'ultima versione è `8.0.2.0.0.99` però di giugno.

Questo perchè nel porting alla 8 è stata erroneamente modificata la versione da `8.0.2.0.0` a `8.0.1.0.0`:
https://github.com/OCA/l10n-italy/commit/57c8bfdeb39106b2c90f5b0b5d44ab2847db4b07#diff-38398b63046830d1d3dec4b6921cd662

Quindi le successive build, ad esempio questa https://pypi.org/project/odoo8-addon-l10n-it-fatturapa-out/8.0.1.2.4.99.dev5 , sono state correttamente caricate ma con versione minore.

Quindi in questo momento con `pip install odoo8-addon-l10n-it-fatturapa-out` si installa una versione di giugno.
