### ISSUE TITLE
[10.0] Impossibile accedere alle fatture d'acquisto dopo aggiornamento

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#834]
Dopo l'aggiornamento dei moduli per la fattura elettronica **non è più possibile accedere alle fatture d'acquisto**.

Aggiornamenti:

l10n_it_fatturapa 10.0.2.2.2 --> 10.0.2.3.1
l10n_it_fatturapa_in 10.0.1.2.2 --> 10.0.1.3.0
l10n_it_fatturapa_in_purchase 10.0.1.0.0
l10n_it_fatturapa_out 10.0.1.2.4 --> 10.0.1.2.6
l10n_it_fatturapa_out_ddt 10.0.1.0.2
l10n_it_fatturapa_pec 10.0.1.2.1 --> 10.0.1.2.2

Accedendo a _Accounting > Purchases > Vendor Bills_ ottengo questo errore:

`
Traceback (most recent call last):
  File "/opt/odoo/OCB/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/OCB/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/OCB/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/OCB/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/OCB/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/OCB/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/OCB/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/OCB/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/OCB/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/OCB/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/OCB/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/OCB/odoo/models.py", line 1337, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo/OCB/odoo/models.py", line 1337, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo/OCB/addons/account/models/account_invoice.py", line 386, in fields_view_get
    return super(AccountInvoice, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo/OCB/addons/mail/models/mail_thread.py", line 364, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo/OCB/odoo/models.py", line 1416, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/odoo/OCB/odoo/addons/base/ir/ir_ui_view.py", line 916, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo/OCB/odoo/addons/base/ir/ir_ui_view.py", line 474, in raise_view_error
    raise ValueError(message)
ValueError: Field `virtual_stamp` does not exist

Error context:
View `account.invoice.supplier.form`
[view_id: 421, xml_id: account.invoice_supplier_form, model: account.invoice, parent_id: n/a]

`

**Comment by dcorio** [comment]
Cercando nei sorgenti dei moduli per la 10, non vedo nessun campo virtual_stamp. Magari era presente in una versione precedente dei moduli ed è stato rimosso senza aggiungere l'opportuna migration. O problemi simili...

Io rimuoverei le viste che ereditano dalla 421 e anche la 421 e poi fare un update del db
