### ISSUE TITLE
wizard import fatturapa: variabile sovrascritta se ci sono DatiFattureCollegate

### ISSUE THREAD

**Issue by sherpya** [OCA/l10n-italy#915]
se ci sono variabile sovrascritta se ci sono DatiFattureCollegate:

alla linea 968 di wizard_import_fatturapa.py
```python
for invoice in RelInvoices:
```
ma sovrascrive invoce di qualche riga sopra di tipo `account.invoice`, mentre diventa `DatiDocumentiCorrelatiType`

poi fallisce con:
```
  File "/opt/odoo/10.0/ce/prod/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1046, in invoiceCreate
    invoice.write(delivery_dict)
AttributeError: 'DatiDocumentiCorrelatiType' object has no attribute 'write'
```

ho sostituito con
```python
            for rel_invoice in RelInvoices:
                doc_datas = self._prepareRelDocsLine(
                    invoice_id, rel_invoice, 'invoice')
                if doc_datas:
                    for doc_data in doc_datas:
                        rel_docs_model.create(doc_data)
```

sostituendo il parametro in _prepareRelDocsLine rel_invoice ma non so se basta/è corretto non avendo guardato la logica

**Comment by eLBati** [comment]
@sherpya puoi fare PR? Così lo vediamo meglio, vengono fatti i test automatici e possiamo anche testare su runbot

**Comment by sherpya** [comment]
dovrei aggiungere un test apposito però

**Comment by eLBati** [comment]
@sherpya sarebbe l'ideale, ma non è bloccante se non riesci.

Chiarimento PS: su runbot i test si possono fare manuali

**Comment by sherpya** [comment]
al momento la branch 10.0 (oca) mi fallisce 4 test, ho rotto qualcosa io?

```
FAIL: test_04_xml_import (odoo.addons.l10n_it_fatturapa_in.tests.test_import_fatturapa_xml.TestFatturaPAXMLValidation)
: Traceback (most recent call last):
: `   File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py", line 197, in test_04_xml_import
: `     u"Company Name field contains 'Societa\' "
: ` AssertionError: u'Il campo nome azienda contiene "Societa\' Alpha SRL", il sistema contiene "SOC [truncated]... != u"Company Name field contains 'Societa' Alpha SRL'. Your System contains 'SOCIET [truncated]...
: ` - Il campo nome azienda contiene "Societa' Alpha SRL", il sistema contiene "SOCIETA' ALPHA SRL"
: ` + Company Name field contains 'Societa' Alpha SRL'. Your System contains 'SOCIETA' ALPHA SRL'
: `   
: ` - L'imponibile calcolato 25.0 \xe8 diverso da quello dei dati di riepilogo 26.0+ Computed amount untaxed 25.0 is different from summary data 26.0


FAIL: test_09_xml_import (odoo.addons.l10n_it_fatturapa_in.tests.test_import_fatturapa_xml.TestFatturaPAXMLValidation)
: Traceback (most recent call last):
: `   File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py", line 263, in test_09_xml_import
: `     'Computed amount untaxed 1030.42 is different from'
: ` AssertionError: u"L'imponibile calcolato 1030.42 \xe8 diverso da quello dei dati di riepilogo 1173.6" != 'Computed amount untaxed 1030.42 is different from summary data 1173.6'

FAIL: test_13_xml_import (odoo.addons.l10n_it_fatturapa_in.tests.test_import_fatturapa_xml.TestFatturaPAXMLValidation)
: Traceback (most recent call last):
: `   File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py", line 321, in test_13_xml_import
: `     u"Company Name field contains 'Societa\' "
: ` AssertionError: u'Il campo nome azienda contiene "Societa\' Alpha SRL", il sistema contiene "SOC [truncated]... != u"Company Name field contains 'Societa' Alpha SRL'. Your System contains 'SOCIET [truncated]...
: ` - Il campo nome azienda contiene "Societa' Alpha SRL", il sistema contiene "SOCIETA' ALPHA SRL"
: ` + Company Name field contains 'Societa' Alpha SRL'. Your System contains 'SOCIETA' ALPHA SRL'
: `   
: ` - L'imponibile calcolato 25.0 \xe8 diverso da quello dei dati di riepilogo 26.0+ Computed amount untaxed 25.0 is different from summary data 26.0

FAIL: test_14_xml_import (odoo.addons.l10n_it_fatturapa_in.tests.test_import_fatturapa_xml.TestFatturaPAXMLValidation)
: Traceback (most recent call last):
: `   File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py", line 344, in test_14_xml_import
: `     u"Company Name field contains 'Societa\' "
: ` AssertionError: u'Il campo nome azienda contiene "Societa\' Alpha SRL", il sistema contiene "SOC [truncated]... != u"Company Name field contains 'Societa' Alpha SRL'. Your System contains 'SOCIET [truncated]...
: ` - Il campo nome azienda contiene "Societa' Alpha SRL", il sistema contiene "SOCIETA' ALPHA SRL"
: ` + Company Name field contains 'Societa' Alpha SRL'. Your System contains 'SOCIETA' ALPHA SRL'
: `   
: ` - Il file XML contiene l'imposta con aliquota "15.55", ma questa non esiste nel sistema.
: ` - Il file XML contiene l'imposta con aliquota "15.55", ma questa non esiste nel sistema.+ XML contains tax with percentage '15.55' but it does not exist in your system 
: ` + XML contains tax with percentage '15.55' but it does not exist in your system
```

**Comment by SimoRubi** [comment]
@sherpya L'ultima build del branch 10.0 è andata bene in Travis, quindi l'errore è probabilmente dovuto alle differenze tra il tuo ambiente e quello che costruisce Travis. Se fai PR vediamo come vanno i test automatici lì
