### ISSUE TITLE
[11.0] [12.0] IMP l10n_it_fatturapa_pec Server email in ingresso NON CONFERMATO

### ISSUE THREAD

**Issue by marcelofrare** [OCA/l10n-italy#925]
Vi segnalo che lo stato del connettore in ingresso della PEC passa allo stato NON CONFERMATO frequentemente.
Ad esempio oggi 2 volte su una installazione con odoo v12 e una con odoo v11
Il messaggio di errore é sempre stato lo stesso: (oggi)

![image](https://user-images.githubusercontent.com/25057933/52001808-9c882680-24c0-11e9-84b1-d31ba29d2df6.png)

**Comment by sergiocorato** [comment]
ciao @marcelofrare mi capita alcune volte, hai possibilità di prelevare la pec che genera l'errore?

**Comment by sergiocorato** [comment]
quel che ho io è un file che è stato firmato in maniera invalida sembra

**Comment by marcelofrare** [comment]
@sergiocorato intendi l'ultimo messaggio non letto da odoo?

**Comment by sergiocorato** [comment]
Si

Il giorno mer 30 gen 2019, 20:08 Marcelo Frare <notifications@github.com>
ha scritto:

**Comment by marcelofrare** [comment]
bene, la prossima volta che succederà lo prelevo e te lo faccio avere

**Comment by sergiocorato** [comment]
il file che mi hanno passato è arrivato dall'SdI e facendo un controllo risulta non integro, ecco l'errore:
`File non integro (firma non valida) - Errore di formato Il file firmato p7m non risulta integro | Verificare che il file sia firmato correttamente o che non sia stato modificato dopo l'apposizione della firma | 00102 -- | -- | --`

**Comment by sergiocorato** [comment]
@marcelofrare @eLBati il file che mi hanno passato era corrotto! lasciamo perdere...

**Comment by marcelofrare** [comment]
@sergiocorato: ti ho girato sulla tua posta l'ultimo messaggio scaricato correttamente e il successivo che non era scaricato

**Comment by bitit-it** [comment]
Mi è successo anche sulla [10]   sono rintrato in modalità sviluppatore, configurazione mail e ho riverificato il server mail di ingresso .
pensavo fosse un problema di perdita di parametri di configurazione della posta elettronica in ingresso, ma ho anche questo errore nel preview  delle fattura criptate che mi sono arrivate, @elBati quella patch vale anche per la [10] ?

errore preview fatture firmate, prima dell'importazione : 
 File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/controllers/main.py", line 13, in pdf_preview
    html = attach.get_fattura_elettronica_preview()
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/models/ir_attachment.py", line 152, in get_fattura_elettronica_preview
    xml_string = self.get_xml_string()
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/models/ir_attachment.py", line 137, in get_xml_string
    temp_file_name, xml_file_name)
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/models/ir_attachment.py", line 89, in decrypt_to_xml
    ) % e.args
UserError: (u'File XML firmato None.', None)
2019-02-01 15:41:57,661 1825 INFO odoo werkzeug: 127.0.0.1 - - [01/Feb/2019 15:41:57] "POST /longpolling/poll HTTP/1.1" 200 -
2019-02-01 15:42:22,202 1825 WARNING odoo odoo.addons.l10n_it_fatturapa.models.ir_attachment: 
2019-02-01 15:42:22,207 1825 INFO odoo werkzeug: 127.0.0.1 - - [01/Feb/2019 15:42:22] "GET /fatturapa/preview/462 HTTP/1.1" 500 -
2019-02-01 15:42:22,216 1825 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 182, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1280, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1471, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python2.7/site-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception                                
    return request._handle_exception(exception)                                                                                         
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 766, in _handle_exception                                                  
    return super(HttpRequest, self)._handle_exception(exception)                                                                        
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch                                        
    result = request.dispatch()                                                                                                         
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 825, in dispatch                                                           
    r = self._call_function(**self.params)                                                                                              
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function                                                     
    return checked_call(self.db, *args, **kwargs)                                                                                       
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper                                                   
    return f(dbname, *args, **kwargs)                                                                                                   
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call                                                       
    result = self.endpoint(*a, **kw)                                                                                                    
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__                                                           
    return self.method(*args, **kw)                                                                                                     
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap                                                      
    response = f(*args, **kw)                                                                                                           
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/controllers/main.py", line 13, in pdf_preview                    
    html = attach.get_fattura_elettronica_preview()                                                                                     
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/models/ir_attachment.py", line 152, in get_fattura_elettronica_preview
    xml_string = self.get_xml_string()
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/models/ir_attachment.py", line 137, in get_xml_string
    temp_file_name, xml_file_name)
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/models/ir_attachment.py", line 89, in decrypt_to_xml
    ) % e.args
UserError: (u'File XML firmato None.', None)
2019-02-01 15:42:47,700 1825 INFO odoo werkzeug: 127.0.0.1 - - [01/Feb/2019 15:42:47] "POST /longpolling/poll HTTP/1.1" 200 -
2019-02-01 15:43:37,744 1825 INFO odoo werkzeug: 127.0.0.1 - - [01/Feb/2019 15:43:37] "POST /longpolling/poll HTTP/1.1" 200 -
2019-02-01 15:43:44,460 1825 INFO odoo odoo.addons.l10n_it_fatturapa_pec.models.fetchmail: start checking for new e-invoices on pop server pec

**Comment by bitit-it** [comment]
e non mi importa le fatture dicendo che il file xml non è firmato .

Enrico

**Comment by eLBati** [comment]
@bitit-it prova questa correzione https://github.com/OCA/l10n-italy/pull/927

**Comment by bitit-it** [comment]
Perfettto. Funziona :) Grazie

Enrico
