### ISSUE TITLE
errore nell'import del modulo l10n_it_fiscalcode-8.0.0.1

### ISSUE THREAD

**Issue by ccandito** [OCA/l10n-italy#93]
l'import del modulo per il controllo dei codici fiscali italiani nella V8.0 fallisce per un errore di compilazione del codice python.
grazie
claudio

**Comment by dcorio** [comment]
Ciao,
dovresti però riportarci l'errore.
Probabilmente si tratta di questo?
https://github.com/OCA/l10n-italy/issues/33

**Comment by ccandito** [comment]
Ciao,
ti riporto l'errore nella compilazione.
Grazie
claudio

Odoo Server Error
Traceback (most recent call last):
  File "C:\Odoo 8.0\server\.\openerp\http.py", line 524, in _handle_exception
  File "C:\Odoo 8.0\server\.\openerp\http.py", line 545, in dispatch
  File "C:\Odoo 8.0\server\.\openerp\http.py", line 301, in _call_function
  File "C:\Odoo 8.0\server\.\openerp\service\model.py", line 113, in wrapper
  File "C:\Odoo 8.0\server\.\openerp\http.py", line 298, in checked_call
  File "C:\Odoo 8.0\server\.\openerp\http.py", line 761, in __call__
  File "C:\Odoo 8.0\server\.\openerp\http.py", line 394, in response_wrap
  File "C:\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 953, in call_button
  File "C:\Odoo 8.0\server\openerp\addons\web\controllers\main.py", line 941, in _call_kw
  File "C:\Odoo 8.0\server\.\openerp\api.py", line 237, in wrapper
  File "C:\Odoo 8.0\server\.\openerp\api.py", line 391, in old_api
  File "C:\Odoo 8.0\server\.\openerp\api.py", line 395, in new_api
  File "C:\Odoo 8.0\server\openerp\addons\base\module\wizard\base_module_update.py", line 15, in update_module
  File "C:\Odoo 8.0\server\.\openerp\api.py", line 235, in wrapper
  File "C:\Odoo 8.0\server\.\openerp\api.py", line 464, in new_api
  File "C:\Odoo 8.0\server\openerp\addons\base\module\module.py", line 654, in update_list
  File "C:\Odoo 8.0\server\.\openerp\http.py", line 1263, in load_addons
  File "C:\Odoo 8.0\server\.\openerp\modules\module.py", line 77, in load_module
  File "C:\Odoo 8.0\server\openerp\addons\l10n_it_fiscalcode\__init__.py", line 23, in <module>
  File "C:\Odoo 8.0\server\openerp\addons\l10n_it_fiscalcode\wizard\__init__.py", line 22, in <module>
  File "C:\Odoo 8.0\server\openerp\addons\l10n_it_fiscalcode\wizard\compute_fc.py", line 25, in <module>
ImportError: No module named codicefiscale

**Comment by dcorio** [comment]
quello è python che ti dice che il modulo codicefiscale non è installato, quindi ti basta "pip install codicefiscale" o equivalente

**Comment by antwal** [comment]
Salve,

io non riesco ad importarlo questo modulo; l'errore è il seguente:

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 494, in _button_immediate_function
    function(cr, uid, ids, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 417, in button_install
    self.state_update(cr, uid, ids, 'to install', ['uninstalled'], context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 408, in state_update
    self.check_external_dependencies(module.name, newstate)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 381, in check_external_dependencies
    raise orm.except_orm(_('Error'), msg % (module_name, e.args[0]))
except_orm: (u'Errore', u'Non \xe8 possibile installare il modulo "l10n_it_fiscalcode" perch\xe8 alcune dipendenze esterne non sono presenti: No module named codicefiscale')

il modulo installato è questo:
...
drwxr-xr-x   3 root root   4096  6 apr 18.14 cfnbootstrap
-rw-r--r--   1 root root   7531 14 lug 17.19 codicefiscale-0.8-py2.7.egg
drwxr-xr-x   2 root root   4096  6 apr 18.16 colorama
drwxr-xr-x   2 root root   4096  6 apr 18.16 colorama-0.3.3.egg-info
...

test python path inclusi:

Python 2.7.9 (default, Apr  1 2015, 18:18:03) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.path
['', '/usr/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/site-packages/pip-6.0.8-py2.7.egg', '/usr/local/lib/python2.7/site-packages/Werkzeug-0.10.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/codicefiscale-0.8-py2.7.egg', '/usr/local/lib/python2.7/site-packages/unicodecsv-0.13.0-py2.7.egg', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/local/lib64/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages', '/usr/lib64/python2.7/dist-packages', '/usr/lib64/python2.7/dist-packages/PIL']



se faccio un test con python facendo l'import funziona tutto, 
però non riesco ad installare questo modulo per il codice fiscale

Non sò quale sia il problema.

Grazie.
