### ISSUE TITLE
[10.0] Errore "Signed Xml file None" scaricando fattura elettronica

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#938]
Riporto in calce l'errore.

L'apertura del file .xml.P7M mostra:"_Impossibile visualizzare «IT************_?????.xml.P7M» Motivo: Dati non riconosciuti o non supportati._"

`Traceback (most recent call last):

  File "/opt/odoo/env-odoo/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)

  File "/opt/odoo/env-odoo/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)

  File "/opt/odoo/OCB/odoo/service/server.py", line 247, in app
    return self.app(e, s)

  File "/opt/odoo/OCB/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)

  File "/opt/odoo/OCB/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)

  File "/opt/odoo/OCB/odoo/http.py", line 1326, in __call__
    return self.dispatch(environ, start_response)

  File "/opt/odoo/OCB/odoo/http.py", line 1300, in __call__
    return self.app(environ, start_wrapped)

  File "/opt/odoo/env-odoo/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)

  File "/opt/odoo/OCB/odoo/http.py", line 1499, in dispatch
    result = ir_http._dispatch()

  File "/opt/odoo/OCB/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()

  File "/opt/odoo/OCB/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
    return cls._handle_exception(e)

  File "/opt/odoo/OCB/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)

  File "/opt/odoo/OCB/odoo/http.py", line 775, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)

  File "/opt/odoo/OCB/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()

  File "/opt/odoo/OCB/odoo/http.py", line 834, in dispatch
    r = self._call_function(**self.params)

  File "/opt/odoo/OCB/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)

  File "/opt/odoo/OCB/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)

  File "/opt/odoo/OCB/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)

  File "/opt/odoo/OCB/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)

  File "/opt/odoo/OCB/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)

  File "/opt/odoo/addons-extra/l10n-italy/l10n_it_fatturapa/controllers/main.py", line 13, in pdf_preview
    html = attach.get_fattura_elettronica_preview()

  File "/opt/odoo/addons-extra/l10n-italy/l10n_it_fatturapa/models/ir_attachment.py", line 176, in get_fattura_elettronica_preview
    xml_string = self.get_xml_string()

  File "/opt/odoo/addons-extra/l10n-italy/l10n_it_fatturapa/models/ir_attachment.py", line 161, in get_xml_string
    temp_file_name, xml_file_name)

  File "/opt/odoo/addons-extra/l10n-italy/l10n_it_fatturapa/models/ir_attachment.py", line 105, in decrypt_to_xml
    ) % e.args

UserError: (u'Signed Xml file None.', '')`

**Comment by eLBati** [comment]
@protontrigg3r ciao, puoi provare questa correzione https://github.com/OCA/l10n-italy/pull/927 ?

**Comment by protontrigg3r** [comment]
Si, la correzione risolve il problema. Grazie!
