### ISSUE TITLE
[10.0] l10n_it_fatturapa fails to identify not signed XML file

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#961]
Try to import the following XML file
```
<p:FatturaElettronica versione="FPR12" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:p="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2 http://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2/Schema_del_file_xml_FatturaPA_versione_1.2.xsd">
  <FatturaElettronicaHeader>
    <DatiTrasmissione>
      <IdTrasmittente>
        <IdPaese>IT</IdPaese>
        <IdCodice>05979361218</IdCodice>
      </IdTrasmittente>
      <ProgressivoInvio>00001</ProgressivoInvio>
      <FormatoTrasmissione>FPR12</FormatoTrasmissione>
      <CodiceDestinatario>0000000</CodiceDestinatario>
      <ContattiTrasmittente/>
    </DatiTrasmissione>
    <CedentePrestatore>
      <DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>IT</IdPaese>
          <IdCodice>02780790107</IdCodice>
        </IdFiscaleIVA>
        <Anagrafica>
          <Denominazione>SOCIETA' ALPHA SRL</Denominazione>
        </Anagrafica>
        <RegimeFiscale>RF01</RegimeFiscale>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>VIALE ROMA 543</Indirizzo>
        <CAP>07100</CAP>
        <Comune>SASSARI</Comune>
        <Provincia>SS</Provincia>
        <Nazione>IT</Nazione>
      </Sede>
    </CedentePrestatore>
    <CessionarioCommittente>
      <DatiAnagrafici>
        <CodiceFiscale>03533590174</CodiceFiscale>
        <Anagrafica>
          <Denominazione>BETA GAMMA</Denominazione>
        </Anagrafica>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>VIA TORINO 38-B</Indirizzo>
        <CAP>00145</CAP>
        <Comune>ROMA</Comune>
        <Provincia>RM</Provincia>
        <Nazione>IT</Nazione>
      </Sede>
    </CessionarioCommittente>
  </FatturaElettronicaHeader>
  <FatturaElettronicaBody>
    <DatiGenerali>
      <DatiGeneraliDocumento>
        <TipoDocumento>TD01</TipoDocumento>
        <Divisa>EUR</Divisa>
        <Data>2014-12-18</Data>
        <Numero>123</Numero>
        <Causale>LA FATTURA FA RIFERIMENTO AD UNA OPERAZIONE AAAA BBBBBBBBBBBBBBBBBB CCC DDDDDDDDDDDDDDD E FFFFFFFFFFFFFFFFFFFF GGGGGGGGGG HHHHHHH II LLLLLLLLLLLLLLLLL MMM NNNNN OO PPPPPPPPPPP QQQQ RRRR SSSSSSSSSSSSSS</Causale>
        <Causale>SEGUE DESCRIZIONE CAUSALE NEL CASO IN CUI NON SIANO STATI SUFFICIENTI 200 CARATTERI AAAAAAAAAAA BBBBBBBBBBBBBBBBB</Causale>
      </DatiGeneraliDocumento>
      <DatiOrdineAcquisto>
        <RiferimentoNumeroLinea>1</RiferimentoNumeroLinea>
        <IdDocumento>66685</IdDocumento>
        <NumItem>1</NumItem>
      </DatiOrdineAcquisto>
      <DatiTrasporto>
        <DatiAnagraficiVettore>				
          <IdFiscaleIVA>
            <IdPaese>IT</IdPaese>
            <IdCodice>04507990150</IdCodice>
          </IdFiscaleIVA>
          <Anagrafica>
            <Denominazione>Trasporto spa</Denominazione>
          </Anagrafica>
        </DatiAnagraficiVettore>
        <DataOraConsegna>2012-10-22T16:46:12.000+02:00</DataOraConsegna>
      </DatiTrasporto>
    </DatiGenerali>
    <DatiBeniServizi>
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <CodiceArticolo>
          <CodiceTipo>INT</CodiceTipo>
          <CodiceValore>ART123</CodiceValore>
        </CodiceArticolo>
        <Descrizione>LA DESCRIZIONE DELLA FORNITURA PUO' SUPERARE I CENTO CARATTERI CHE RAPPRESENTAVANO IL PRECEDENTE LIMITE DIMENSIONALE. TALE LIMITE NELLA NUOVA VERSIONE E' STATO PORTATO A MILLE CARATTERI</Descrizione>
        <Quantita>5.00</Quantita>
        <PrezzoUnitario>1.00</PrezzoUnitario>
        <PrezzoTotale>5.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>2</NumeroLinea>
        <Descrizione>FORNITURE VARIE PER UFFICIO</Descrizione>
        <Quantita>10.00</Quantita>
        <PrezzoUnitario>2.00</PrezzoUnitario>
        <PrezzoTotale>20.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DatiRiepilogo>
        <AliquotaIVA>22.00</AliquotaIVA>
        <ImponibileImporto>25.00</ImponibileImporto>
        <Imposta>5.50</Imposta>
        <EsigibilitaIVA>I</EsigibilitaIVA>
      </DatiRiepilogo>
    </DatiBeniServizi>
    <DatiPagamento>
      <CondizioniPagamento>TP01</CondizioniPagamento>
      <DettaglioPagamento>
        <ModalitaPagamento>MP01</ModalitaPagamento>
        <DataScadenzaPagamento>2015-01-30</DataScadenzaPagamento>
        <ImportoPagamento>32.50</ImportoPagamento>
      </DettaglioPagamento>
    </DatiPagamento>
  </FatturaElettronicaBody>
  <FatturaElettronicaBody>
    <DatiGenerali>
      <DatiGeneraliDocumento>
        <TipoDocumento>TD01</TipoDocumento>
        <Divisa>EUR</Divisa>
        <Data>2014-12-20</Data>
        <Numero>456</Numero>
        <Causale>LA FATTURA FA RIFERIMENTO AD UNA OPERAZIONE AAAA BBBBBBBBBBBBBBBBBB CCC DDDDDDDDDDDDDDD E FFFFFFFFFFFFFFFFFFFF GGGGGGGGGG HHHHHHH II LLLLLLLLLLLLLLLLL MMM NNNNN OO PPPPPPPPPPP QQQQ RRRR SSSSSSSSSSSSSS</Causale>
        <Causale>SEGUE DESCRIZIONE CAUSALE NEL CASO IN CUI NON SIANO STATI SUFFICIENTI 200 CARATTERI AAAAAAAAAAA BBBBBBBBBBBBBBBBB</Causale>
      </DatiGeneraliDocumento>
      <DatiOrdineAcquisto>
        <RiferimentoNumeroLinea>1</RiferimentoNumeroLinea>
        <IdDocumento>66685</IdDocumento>
        <NumItem>1</NumItem>
      </DatiOrdineAcquisto>
    </DatiGenerali>
    <DatiBeniServizi>
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <Descrizione>PRESTAZIONE DEL SEGUENTE SERVIZIO PROFESSIONALE: LA DESCRIZIONE DELLA PRESTAZIONE PUO' SUPERARE I CENTO CARATTERI CHE RAPPRESENTAVANO IL PRECEDENTE LIMITE DIMENSIONALE. TALE LIMITE NELLA NUOVA VERSIONE E' STATO PORTATO A MILLE CARATTERI</Descrizione>
        <PrezzoUnitario>2000.00</PrezzoUnitario>
        <PrezzoTotale>2000.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DatiRiepilogo>
        <AliquotaIVA>22.00</AliquotaIVA>
        <ImponibileImporto>2000.00</ImponibileImporto>
        <Imposta>440.00</Imposta>
        <EsigibilitaIVA>I</EsigibilitaIVA>
      </DatiRiepilogo>
    </DatiBeniServizi>
    <DatiPagamento>
      <CondizioniPagamento>TP01</CondizioniPagamento>
      <DettaglioPagamento>
        <ModalitaPagamento>MP19</ModalitaPagamento>
        <DataScadenzaPagamento>2015-01-28</DataScadenzaPagamento>
        <ImportoPagamento>2440.00</ImportoPagamento>
      </DettaglioPagamento>
    </DatiPagamento>
  </FatturaElettronicaBody>
</p:FatturaElettronica>
```

Even if accepted by SDI, l10n_it_fatturapa says `Signed Xml file Error parsing asn1crypto.cms.ContentInfo - tag should have been 16, but 28 was found`

Regular expression `re_xml = re.compile(br'(\xef\xbb\xbf)*\s*<\?xml', re.I)` doesn't match it

**Comment by eLBati** [comment]
@sherpya @warp10 uno di voi riesce a preparare la correzione? (includendo il test per il file riportato)

**Comment by sherpya** [comment]
ma è un xml senza `<?xml` davanti?

**Comment by eLBati** [comment]
@sherpya esatto

**Comment by eLBati** [comment]
@sherpya quelle di Amazon sono così

**Comment by sherpya** [comment]
@eLBati non è xml valido tecnicamente, pyxb se le accolla? se dobbiamo accettare ste robe bisogna capire come differenziare, il nome file non mi piace come idea

**Comment by sherpya** [comment]
roba da pazzi...

**Comment by eLBati** [comment]
@sherpya in `get_xml_string` procederei al contrario: se firmato cades, `extract_cades`; poi `cleanup_xml` in ogni caso.

Sai se c'è modo con asn1crypto di stabilire se un file è firmato cades? Altrimenti puoi usare il metodo rude con try except

**Comment by sherpya** [comment]
si può fare così:
- se è base64 -> decodo
- provo cades
- se fallisce presumo sia xml

no, non è agevole capire se è asn1 senza parsarlo

**Comment by eLBati** [comment]
Ok

**Comment by sherpya** [comment]
fatto la test_06_import_except fallisce in modo diverso da quello che si aspetta, va modificata

```
ERROR: test_06_import_except (odoo.addons.l10n_it_fatturapa_in.tests.test_import_fatturapa_xml.TestFatturaPAXMLValidation)

Traceback (most recent call last):
`    File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py", line 231, in test_06_import_except
`      'IT05979361218_fake.xml.p7m'
`    File "/home/sherpya/workspace/odoo/odoo/odoo/odoo/tests/common.py", line 129, in assertRaises
`      func(*args, **kwargs)
`    File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa_in/tests/test_import_fatturapa_xml.py", line 56, in run_wizard
`      'datas_fname': datas_fname
`    File "/home/sherpya/workspace/odoo/odoo/odoo/addons/mail/models/mail_thread.py", line 228, in create
`      thread = super(MailThread, self).create(values)
`    File "/home/sherpya/workspace/odoo/odoo/odoo/odoo/models.py", line 3847, in create
`      record = self.browse(self._create(old_vals))
`    File "/home/sherpya/workspace/odoo/odoo/odoo/odoo/models.py", line 4006, in _create
`      self.recompute()
`    File "/home/sherpya/workspace/odoo/odoo/odoo/odoo/models.py", line 5336, in recompute
`      vals = rec._convert_to_write({n: rec[n] for n in ns})
`    File "/home/sherpya/workspace/odoo/odoo/odoo/odoo/models.py", line 5336, in <dictcomp>
`      vals = rec._convert_to_write({n: rec[n] for n in ns})
`    File "/home/sherpya/workspace/odoo/odoo/odoo/odoo/models.py", line 5232, in __getitem__
`      return self._fields[key].__get__(self, type(self))
`    File "/home/sherpya/workspace/odoo/odoo/odoo/odoo/fields.py", line 915, in __get__
`      self.determine_value(record)
`    File "/home/sherpya/workspace/odoo/odoo/odoo/odoo/fields.py", line 1001, in determine_value
`      self.compute_value(recs)
`    File "/home/sherpya/workspace/odoo/odoo/odoo/odoo/fields.py", line 981, in compute_value
`      self._compute_value(records)
`    File "/home/sherpya/workspace/odoo/odoo/odoo/odoo/fields.py", line 972, in _compute_value
`      getattr(records, self.compute)()
`    File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa_in/models/attachment.py", line 43, in _compute_xml_data
`      fatt = self.env['wizard.import.fatturapa'].get_invoice_obj(att)
`    File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1161, in get_invoice_obj
`      xml_string = fatturapa_attachment.get_xml_string()
`    File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa_in/models/attachment.py", line 37, in get_xml_string
`      return self.ir_attachment_id.get_xml_string()
`    File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa/models/ir_attachment.py", line 99, in get_xml_string
`      return self.cleanup_xml(data)
`    File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa/models/ir_attachment.py", line 67, in cleanup_xml
`      xml_string = self.remove_xades_sign(xml_string)
`    File "/home/sherpya/workspace/odoo/odoo/addons/l10n_it_fatturapa/models/ir_attachment.py", line 47, in remove_xades_sign
```                                                                                                        ```

**Comment by sherpya** [comment]
faccio la PR, cmq mi sbagliavo:
```
XML declaration
    XML documents may begin with an XML declaration that describes some information about themselves. An example is <?xml version="1.0" encoding="UTF-8"?>.
```
